### ISSUE TITLE
Some modules don't show in the auto-complete

### ISSUE THREAD

**Issue by dcookdesign** [omz/Pythonista-Issues#10]
In Pythonista 3 (and 2 I think) some modules do not show up in auto-complete in the editor, but they will show up in the console.

I don't know which modules. I only noticed this when trying to import `pygments` before.

Compare:
![image](https://cloud.githubusercontent.com/assets/12954427/16140520/5bde9c6c-348c-11e6-87cf-2d00c4dd098d.jpeg)

Verses:
![image](https://cloud.githubusercontent.com/assets/12954427/16140522/5c3eb516-348c-11e6-9fc6-df94c882b8cc.jpeg)

**Comment by zrzka** [comment]
Just tried this in Pythonista 311014 and it works.

@dcookdesign if you encouter this issue again, please, feel free to reopen.
