### ISSUE TITLE
Allow more than 8 items in the wrench menu

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#101]
It would be great to be able to add more than 8 items to the wrench menu. A scrolling view would be sort of ok, but it will be still nice if on larger screens the popover could use more of the screen space and allow for extra items to be added

**Comment by dgelessus** [comment]
Wait, there's a limit? To be honest I don't have very many shortcuts (atm I only have two for stash and filenav, so I can run them quickly) but once #31 is fixed I will definitely have more.

**Comment by Phuket2** [comment]
I have a lot, well more than 8 wannabes 😁 Most are very simple, but just very convenient. Launching stash is also one of them 😱 But I can see using it more and more

**Comment by zrzka** [comment]
It seems that there's no more _8 limit_, was able to add 10 of them.

![41d07fbe-6a73-425c-9ef1-da91e30d50e5](https://user-images.githubusercontent.com/1084172/31865283-d6073bca-b76c-11e7-8f62-7439bcde4df6.jpeg)
