### ISSUE TITLE
Run button on the Keyboard

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#102]
This may sound like a stupid thing. But if you use a iPad Pro, that run button is very far away. After some hours, you really get sick of reaching and aiming for that little icon. I often close a tab accidentally. Even when sober.  
It would be great if I could sacrifice one of Pythonista's keyboard keys to be the run button. Ideally, you would be able to select which key to use. But anything on the keyboard would still be better than reaching all the time. I realise these needs to be an option. As many may not like this idea. When I was working on my iPad Air, this was never a problem. It's only with the larger iPad Pro 12' screen this is noticeable for me

**Comment by jsbain** [comment]
first world problems ;)

**Comment by zrzka** [comment]
I can understand your frustration, but closing this as well. I don't see this as a real issue.
