### ISSUE TITLE
View cannot be presented agin after being presented as popover

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#114]
Symptom:

```
>> > v=ui.View()
>>>v.present('popover')
# then, close the view... it can no longer be presented, even though it is closed
>>> v.present('popover')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: View is already being presented or animation is in progress
```

**Comment by beepbap** [comment]
The _trick_ is to open the new instance first and then close the old one when dealing with a `popover` view. It is a bit counterintuitive, but it works (for me). I am not sure if this behaviour could be considered to be bug, but here is a stripped down example, relaunching itself from the `popover` state:

`
    #!Python2
    import ui
    
    
    class ToggleView(ui.View):
        '''
        '''
    
        def __init__(self, is_expanded=False):
            '''
            '''
            self._is_expanded = is_expanded
            self.name = 'test'
            self.add_subview(ui.Button(title='toggle', 
                                       action=self.cmd_expand))
    
        def cmd_expand(self, sender):
            '''
            '''
            run(self)
    
        def show(self, location):
            '''
            '''
            if not self._is_expanded:
                self.present('popover',
                             hide_title_bar=True,
                             popover_location=location)
            else:
                self.present('panel',
                             hide_title_bar=True)
    
    def run(old_instance=None):
        '''
        '''
        location = (ui.get_window_size().w, 50)
        is_expanded = False
        if old_instance is not None:
            is_expanded = not old_instance._is_expanded
        ToggleView(is_expanded).show(location)
        if old_instance is not None:
            old_instance.close()
    
    
    if __name__ == '__main__':
        run()
`

**Comment by zrzka** [comment]
I just tested this in 311014 and it works if you wait reasonable amount of time. Closing it in favour of #450 and #392. When these two issues will be done, you will know when exactly you can present it again.
