### ISSUE TITLE
Console - Mute option. (Enhancement)

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#116]
Just an idea. When writing in Python or any language, you invariably do quite a few print statements to make sure all is correct/debugging. 
But these print statements can start to get in the way. However you don't want to remove them,,just yet. You are still testing...
But if you could essentially mute the console and unmute it in code could be a nice debugging feature. I know my jargon is not correct, could be console.suspend_output = True for example. 
Maybe a mechanism is in place for this already. I havnt seen though. 

Actually, I have had this problem many times but just accepted it and did what I needed to do to clean it up. In a redundant way. Commenting out print() lines etc...only to have to later uncomment them.

Food for thought

**Comment by cclauss** [comment]
```python
import logging
help(logging)
```

**Comment by Phuket2** [comment]
@ccc, I did think about logging. But sometimes you want it quick and dirty. I don't see a inherit problem will suspending/muting the console output. Maybe you can assign the console to null already. I am not sure. But, I just think it would be cool if I could just turn on and off console output. And I think it would be helpful

**Comment by cclauss** [comment]
The [Principle of Least Astonishment}(https://en.wikipedia.org/wiki/Principle_of_least_astonishment) should guide our approach here.  If many other implementations of Python enabled the turning on and off of standard out then it would be right and good for Pythonista to follow suit.  However the other implementation has chosen to push developers to use `logging` instead so Pythonista should follow suit.

It would be a real roadblock for initial users if `print('Hello World!')` did not work as expected.

**Comment by Phuket2** [comment]
ccc, I agree with you. But can't you normally point a terminal/TTL/console to a null device hence stopping the output. Look, really ,a long time since I have being doing that stuff. But I seem to remember something like that. I also don't want to break all the rules. I just thought that was normal in the console world like redirection is, and maybe it is a type of redirect. 
Look it's not critical, I will close this issue tomorrow,

**Comment by Phuket2** [comment]
Tomorrow already here now. So will just close this one. Don't mean to be a distraction, but maybe this one is.

**Comment by cclauss** [comment]
Try using logging...  I think you will really like it after a few daze.

**Comment by jsbain** [comment]
I would use logging more if it wasn't such a pain in the ass to set up.  I guess that is what Snippets is for... hmm.

@Phuket2 you could always monkey patch __builtins__.print, though i really don't advise it.

``` 
'''monkey patch console to disable print() when console.enable==False'''
import console
def print_replacement(*args):
	if not hasattr(console,'enabled') or console.enabled:
		print.print(*args)
if not hasattr(__builtins__.print,'print'):
	print_replacement.print=__builtins__.print
	__builtins__.print=print_replacement
	console.enabled=True
	del print_replacement
```

**Comment by Phuket2** [comment]
Thanks guys. It's funny, I actually didn't think this would be a big deal. I will give logging a go I guess, just wanted a quick and dirty control point to start and stop console output.  
I understand something like logging would have a lot of benefits when building a full app/service.  

But when you are just trying to look at someone's code from the forum or just playing around/testing/experimenting the easier the better

**Comment by Phuket2** [comment]
@cclauss , @jsbain 
Hmmm, I just come across something. It's sort of there, but not 100%.
In py3 print has a file param. 
So you can do the below. It's still ok for a quick and dirty.  
```
# opening here with 'a', could use 'w'
log = open('my_print_code.txt', 'a')

pfile = log
# does not print to console, prints to the log file (Just text)
for i in range(0, 100):
	print( i, file = pfile)

# this prints to the console, sys.stdout
pfile = None
for i in range(0, 10):
	print( i, file = pfile)

print('finshed') # file param not used, goes to sys.stdout
log.close()

```

**Comment by cclauss** [comment]
Rock & roll.

**Comment by omz** [comment]
If I'm not misunderstanding the issue here, you could also put something like this in the wrench menu to mute/unmute the console:

```python
#! python3
import console, sys
from io import StringIO

if isinstance(sys.stdout, StringIO):
	sys.stdout = sys._muted_stdout
	console.hud_alert('Console unmuted')
else:
	sys._muted_stdout = sys.stdout
	sys.stdout = StringIO()
	console.hud_alert('Console muted')
```

**Comment by Phuket2** [comment]
@omz , that's also a good one to have. Initially at the basic level  I was looking for something like console.mute = bool
Sometimes debugging print statements get out of control. But you don't want to go and comment them out or delete them just yet. So if you are debugging something that happens below a certain point, you could just put at the beginning of your main, console.mute = True, then at the point in your code you want the print statements again for debugging you could do console.mute = False

@omz in the scheme of things it's not a big deal. But to me it makes sense that console module would support that functionality. In some form or another
