### ISSUE TITLE
ui.View.frame ambiguous if passed , then presented in style = full_screen 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#119]
Not sure I am correct here, but this does not seem correct to me. 
If you create a ui.View(frame = (0, 0, 600, 800)), and then present it with style = 'full_screen', and you print the frame, in this example you get (0, 0, 600, 800). I know it's been implicitly set, but it's still incorrect. If you print out the bounds they are correct.  Also if you don't assign a frame it's correct.
I am sure my misunderstanding of how this works has created problems for me in the past. When presenting in full_screen mode, I would have thought that the frame would be automatically updated. 
If you don't know this, can easily lead to strange results. You are writing something that is being presented in a sheet, then all of a sudden you decide to test it presented in full_screen mode

Again, I don't know if this is a bug or not. But at minimum I would say confusing.

**Comment by jsbain** [comment]
Do you have example code?  This is what I get
``` 
>>> v=ui.View(frame=(0,0,600,800))
>>> v.present()
>>> v.frame
Rect(0.00, 64.00, 768.00, 960.00)
```

**Comment by Phuket2** [comment]
Looks like it may only affect classes subclassing ui.View
```
import ui

class MyClass(ui.View):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

if __name__ == '__main__':
	w, h = 600, 800
	f = (0, 0, w, h)
	
	mc = MyClass(frame=f, bg_color='white')
	mc.present('full_screen', animated=False)
	
	print(mc.frame)
	print(mc.bounds)
```

**Comment by jsbain** [comment]
your code produces
(0.00, 64.00, 768.00, 960.00)
(0.00, 0.00, 768.00, 960.00)
for me.  Are you getting something else?

**Comment by Phuket2** [comment]
Yes, get
frame (0.00, 0.00, 600.00, 800.00)
bounds (0.00, 0.00, 1024.00, 1302.00)
Could be to do with iPad Pro 12'

**Comment by Phuket2** [comment]
@omz, not sure if you can easily spot the problem here. But we are running the same code getting different results. I am using iPad Pro 12', iOS 9.3.3, latest beta py3. 
@jsbain , maybe you can say your system info

**Comment by Phuket2** [comment]
Ok, I think I have narrowed down the problem.  I think it's **animated = False** param to present. If I remove it I get the correct result. Still appears to be hardware specific if @jsbain still works. Maybe he is on different iOS version.

**Comment by jsbain** [comment]
I suspect if you put a short time.sleep, to allow the view time to present, it will work out. 
i am ipad3,ios8.4.

**Comment by Phuket2** [comment]
@jsbain , I think you are right about the delay. I got confused a little , I changed the super() call to ui.View.__init__(…) so I could run under 2.7. But then I noticed I was getting the right result sometimes then other times not. So I guess calling ui.View.__init__() maybe marginally slower than a call to super. But it starts to make sense. 
But regardless, its not correct and therefore a bug. Tricky one, but still a bug

**Comment by danrcook** [comment]
@phuket2 I dont think its buggy, its just that (*i think*) the appropriate place to get that info is in layout or draw:

```
import ui

class MyClass(ui.View):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		
	def layout(self):
		print('layout frame',self.frame)
		print('layout bounds',self.bounds)
		
	def draw(self):
		print('draw frame', self.frame)
		print('draw bounds', self.bounds)
		
if __name__ == '__main__':
	w, h = 600, 800
	f = (0, 0, w, h)
	
	mc = MyClass(frame=f, bg_color='white')
	mc.present('full_screen', animated=False)
	
	print('frame', mc.frame)
	print('bounds', mc.bounds)
```

**results as printed:**
frame (0.00, 0.00, 600.00, 800.00)
layout frame (0.00, 64.00, 1024.00, 704.00)
layout bounds (0.00, 0.00, 1024.00, 704.00)
draw frame (0.00, 64.00, 1024.00, 704.00)
draw bounds (0.00, 0.00, 1024.00, 704.00)
bounds (0.00, 0.00, 1024.00, 704.00)

**Comment by Phuket2** [comment]
@danrcook , that's not the answer because it happens on non-custom ui.View also meaning you have no draw function.
Look, I am not trying to be difficult. As @jsbain mentioned there is a work around, by inserting a delay.  I just couldnt work out what was going on.  I suspect this problem has only emerged with faster processors (I think), if that's true, it will get worse as the processors get faster.  I also like animations inside my ui's, I just don't like the start up animation, that's why I use the animated = False param.
Anyway, I will just leave it in @omz hands.

**Comment by jsbain** [comment]
not sure this a bug, or just user thread safe practices.
Does
`on_main_thread(mc.present)(animated=False)`
work for you?
If so, the issue is simply the dangers of living in s multithreaded environment, you have to make sure your code is threadsafe.  We were operating under the assumption that present was a blocking function, so assumed it was safe to read frame immediately after present.   But, it seems it does not, so you need to run it on the main thread to ensure things happen in the right order.  Actually, 
``` 
@on_main_thread
def present_and_check_frame():
    mc.present(....
    print(mc.frame ....
``` 
might be needed. not sure

**Comment by Phuket2** [comment]
@jsbain , sorry just got around to testing this. But your code works. on_main_thread(mc.present)(animated=False), I tried many ways to make it fail.  

But really? I can't believe this was how @omz intended that param to behave. So many beginners here, how are we suppose to figure out call by call which functions/params are thread safe and which are not.  That does not sound reasonable to me.  In my mind, it's a bug or ill conceived. 

Not trying to be smart. It just does not make sense to me that you have to know everything about threads to run the most basic of operations in Pythonista Ie, creating a view and presenting it.  
Then every method in Pythonista documentation   that can have issues on its on foundation classes with threads should be tagged as such and a defensive to deal with it and the ramifications of doing so.
The thing that comes to mind simlar was double dereferencing  handles on the old macs to ptrs. **h = ptr. You had to know if what you did whilst as a ptr if memory could move or not. Of course the defensive move was to do hlock(h), but it was all documented. 

Oh well. It is what it is I guess.  Again, I am not trying to be difficult, just seems so flimsy

**Comment by zrzka** [comment]
It's not a bug. Every UI operation is supposed to be made on the main thread. No exceptions. And it does include stuff like reading UI operation related properties like `frame`, `bounds`, ... If you would like to be 100% sure that you have latest `frame`, `bounds`, ... get it when `layout` is called or wrap it with `on_main_thread` and wait till the view is presented. Because you don't know when the view presentation is finished, I filled a new issues #448, which covers it. Also there's #392 that includes `UIViewController` controller callbacks like `did_appear`, `will_appear`, ... which can help as well.
