### ISSUE TITLE
Standard Library files not shown in Recent Files

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#120]
The "Open Recent" button does not seem to show files in the Standard Library.

I could imagine this might be a deliberate design decision to avoid confusion or cluttering up of the recent files display.  Showing these would be nice as an optional setting.  

Or, as an alternative, if there was a "favorites" or "project" system, whereby any file can be marked a favorite, and have an Open Favorite button under Open Recent, to allow quick access to commonly used files.   Projects might be either a second level of heirarchy of favorites, or else a way to save a tab list and order to restore at a later time.

A final alternative: ability to "pin" certain tabs so that they are not replaced when opening a new file from the file browser.  

Motivation:
It is tedious to find certain files in the Standard Library, and if such a tab is accidentally closed or a new file loaded into such a tab, it is annoying to find the reference file again.

for instance, in my current project, i basically need. few files open at all times for reference:

```
Modules-> Standard Library -> site-packages-> matplotlib -> backends -> backend_gtk.py
Modules-> Standard Library -> site-packages-> matplotlib -> backends -> backend_cairo.py
Modules-> Standard Library -> site-packages-> matplotlib -> backends_bases.py
```

which takes a lot of taps to restore when i accidentally close one.

**Comment by Phuket2** [comment]
@jsbain , sounds a lot like workspaces. Saved Workspaces would be excellent in Pythonista. Depends how you describe a workspace of course, but a minimum a set of files to be opened. Better again in a particular tab order. Then could have other settings globals etc....

**Comment by zrzka** [comment]
Standard Library files are listed in Recent File in 311014, closing.
