### ISSUE TITLE
Enable "Share" for folders, not just single files

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#121]
The wrench menu in current Pythonista editor allows you to click "Share..." to share a single file.

It would be useful for some workflows if you could do the same with a whole folder / directory.

**Comment by dgelessus** [comment]
In the file browser you can select multiple files and/or folders and share them. To be honest I don't see how sharing folders from the editor should work, after all you can only open single files and not folders in the editor. The file browser seems like a more logical place for this feature (though apparently it's not very discoverable there `;)`).

**Comment by cclauss** [comment]
@dgelessus Wow!  That totally works!  You are correct that Edit / Select / Share in the file browser was not intuitive to me but once you do it on a folder and then select `save to Working Copy`, you will be asked if you want to make a new repo or just a directory in Working Copy.  It magically does just the right thing.

Thanks much, closing.
