### ISSUE TITLE
Argument and Return types are ignored in Python 3.5

### ISSUE THREAD

**Issue by filippocld** [omz/Pythonista-Issues#124]
If you create a function and specify the argument and result types the syntax works and the script runs but the argument and result types are ignored.

Example:

```
#!python3
from sys import version
print(version)

def funcname(arg1: int) -> float:  # even if the types are wrong (they should be respectively str and int) it still works
	print(type(arg1))
	return len(arg1)

print(funcname('HelloWorld'))  # Syntax works, but argtypes are ignored
```

**Comment by lukaskollmer** [comment]
I don't think these annotations actually do anything.

**Comment by omz** [comment]
I don't consider this a bug. Type annotations are not enforced in any way by Python 3, and they're completely optional. You can think of them as a more formal type of comment that could be used by static analysis tools, code completion libraries, and so on, but they don't change anything about the runtime behavior of the code.
