### ISSUE TITLE
ui.ActivityIndicator() a bit more help in documentation would be nice

### ISSUE THREAD

**Issue by dcookdesign** [omz/Pythonista-Issues#130]
Maybe this is because I'm still new to Python and don't understand a lot of things yet, but I had a head-banging session trying to get `ui.ActivityIndicator()` to work. 

I had something like this going:

```
def do_some_data_something():
    activity_indicator.start()
    #do stuff that takes a bit of time
    activity_indicator.stop()
```

For the life of me I just couldn't get it going. I could get it with a button etc. I tried `bring_to_front()` and `send_to_back()`. But just on that function it wasn't working. Finally I tried the decorator `@ui.in_background` and it worked. 

Anyway- the point is just that if there was this small hint in the documentation that the activity indicator _may/will probably_ need to use the @ui.in_background decorator ...

**Comment by zrzka** [comment]
I'm not aware that this is really necessary (`@in_background`). Just tested this in 311014 and it nicely animates. Even tried _crazy_ things like start animation from background, main thread, ... Works. If you encounter this problem again, please, reopen or fill a new issue.
