### ISSUE TITLE
ui.load_view_str not documented- Documentation

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#132]
Also for ui.load_view() the params bindings=None, stackframe=None are not reflected in the documentation.

**Comment by zrzka** [comment]
311014 - `bindings` documented, `stackframe` not. I'm not sure if `stackframe` should be documented from the user documentation point of view. Can probably confuse lot of "scripting people" who have no idea what the `stackframe` is. @omz?

**Comment by omz** [comment]
I can't really think of a reason anyone would ever use the `stackframe` argument tbh, so I don't think it needs to be documented (and I might remove it at some point).

Since `bindings` are documented now, I'm closing this.
