### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by fuzzy76** [omz/Pythonista-Issues#135]
I consider the lack of an OS X version a huge bug :) Just being able to edit large scripts on my Mac and have them synced would be great.

**Comment by danrcook** [comment]
I know the syncing wouldn't be possible as a built in feature because of restrictions for iOS apps, but I upvote!

**Comment by cclauss** [comment]
Focus is the key to success.  Mac OS X would just be a big distraction.  Python 2.7.12 and 3.5.2 run fine on the Mac.  With the Atom editor and plugins you get autopep8, flake8, etc. plus you can automatically send files from Atom to a Pythonista FTP server running on your iOS device https://atom.io/packages/atom-ftp-editor

**Comment by disorientedperson** [comment]
I don't think not having a Mac version is an issue with Pythonista. This repo is for reporting bugs and enhancement requests for the _iOS_ app.

**Comment by Phuket2** [comment]
@fuzzy76 , it can not be considered a bug or even remotely like that.  You need to be a little realistic. I am not trying to be smart, but it's wrong to assert it's a bug not to have a Mac version. Pythonista is a first class program (well not first class, it's best in class) and then more for what it advertises itself be. It surpasses 99% of people's expectations.

**Comment by fuzzy76** [comment]
Perhaps my wording was a bit too cheeky, or my fantasies too unrealistic. Porting the runtime would probably be a lot of work, I realize that. The actual need was probably more the lines of an editor that could sync using iCloud (an app can only sync with itself AFAIK).

**Comment by lukaskollmer** [comment]
@fuzzy76 the runtime wouldn't need to be ported at all since macOS already ships with a default Python installation. iCloud sync wouldn't be possible at all because Apple doesn't allow apps to download executable code. The biggest reason not to make a Mac version of Pythonista is that there isn't really a need for it. If someone wants to write and run Python code on their Mac, they already can (just open the terminal and type `python` to test this).
iOS however, does not ship with a Python installation which means that Pythonista is pretty much the only app to write Python code on iOS.

**Comment by cclauss** [comment]
Macs can download executable code...  No sandbox here...  That is only an iOS restriction.

**Comment by Phuket2** [comment]
@fuzzy76 , ok fair enough. But these connections or lack of are imposed by Apple. Nothing to do with the App.  It is really a shame, but that's the way it is. If omz could do anything he wanted to, the exchange would be awesome. 
Try looking at this link, http://pythonista-tools.github.io/Pythonista-Tools/index.html . A lot of great tools. We all know, it's as good if it was built in. But still a great community helping out on many issues

**Comment by scj643** [comment]
My take on this is having the UI module in OS X

**Comment by lukaskollmer** [comment]
@scj643 porting the entire `ui` mofule to macOS is impossible. For historic reasons, the Mac handles ui different than iOS does. [Some have attempted such things but they failed](http://chameleonproject.org/).

**Comment by controversial** [comment]
@omz Can this be closed?
