### ISSUE TITLE
notification action_url ignored when app is closed

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#142]
Previously, action_url worked even when the app was closed.  Now it does not.  Example:

```
import notification,objc_util
notification.schedule('hi',5,action_url='https://google.com')
objc_util.ObjCInstance(1) #force crash to close app
# safari should be launched in 5 seconds
```

**Comment by zrzka** [comment]
Still valid in 311014 ...

**Pythonista is running, foreground**

Alert appears with OK button. When I tap on the OK button, Safari is launched with given URL.

**Pythonista is running, background**

System notification appears, when I tap on it, Pythonista is resumed and then Safari is launched with the given URL.

**Pythonista is killed**

System notification appears, when I tap on it, Pythonista is launched, pythonista_startup.py is processed, ... and that's all, nothing happens, no Safari.

**Comment by jsbain** [comment]
Fixed in 311015
