### ISSUE TITLE
Custom Views - did_present callback akin did_load callback - enhancement 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#143]
It seams to me it would be nice to have a did_present callback for custom views. Could help isolate some resizing code that you don't want to put into the layout callback. Alternatively, the did_load callback could serve a dual purpose. Not sure about the discrete differences that would exist if any between from a UI file or a memory view.

**Comment by cclauss** [comment]
What kind of resizing code would you not want to put into `layout()`?

**Comment by Phuket2** [comment]
@ccc, if presented with full_screen. Also could check if status_bar is hidden or not and adjust view size accordingly. Ok, could be done in layout, but why if you just want a one off call.  Also, I was trying to evaluate the root view of some nested views, but it was difficult because the entire view had not composited. Yes, can move the call further down the calling chain, but what could be a generic call becomes more specific. But I am sure there are reasons to to have this callback.

**Comment by Phuket2** [comment]
@cclauss , I just come another reason why did_load callback would be handy for Custom ui Classes.  If you want to add subviews using Transformations. It can still be done, but it's not so nice how you have to do it.  Well as far as I can see.  If you could present your subviews once did_load/did_present then showing them with transformations would be more natural in code

**Comment by zrzka** [comment]
Closing in favour of #392.
