### ISSUE TITLE
" 'NoneType' object is not callable" Exception thrown by "Python 2 to 3" Tool in Pythonista 3

### ISSUE THREAD

**Issue by RichardPotthoff** [omz/Pythonista-Issues#148]
When I try to use the "Python 2 to 3" conversion tool in Pythonista 3 v3.0(300018), I get the error:
<pre><code>PythonistaKit3.framework/pylib/site-packages/markupsafe/_speedups.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
TypeError: 'NoneType' object is not callable
</code></pre>
I was able to patch the bug by copying imp.py from StandardLibrary(3.5) to site-packages3, and then changing the last line in imp.py:
```python
-    load_dynamic = None
+    def load_dynamic(name, path, file=None):
+      raise ImportError  
```

I do not think this is a good solution, because I think whoever set <code>load_dynamic</code> to <code>None</code> will probably have statements like <code>if imp.load_dynamic: ...</code> somewhere else in the code. 

Another way to fix this problem would be to catch the exception in <code>\__bootstrap__ </code>, and raise an ImportError there:
```python
def __bootstrap__():
   global __bootstrap__, __loader__, __file__
   try:
     import sys, pkg_resources,imp
     __file__ = pkg_resources.resource_filename(__name__,'_speedups.so')
     __loader__ = None; del __bootstrap__, __loader__
     imp.load_dynamic(__name__,__file__)
   except:
     raise ImportError
__bootstrap__()
```
I would then leave <code>load_dynamic</code> undefined in <code>imp</code>, and use <code>hasattr(imp,'load_dynamic')</code> if I need to check whether or not it is there.

**Comment by controversial** [comment]
Not a problem with Pythonista, @omz didn't create the 2to3 tool. 2to3 is part of the Python standard library.

**Comment by RichardPotthoff** [comment]
I was talking about the "Python 2 to 3" tool that is integrated into Pythonista:
![img_0174](https://cloud.githubusercontent.com/assets/1579528/19017796/598a730e-8816-11e6-843e-49329003cea5.PNG)

The exception originates in "site-packages/markupsafe/_speedups.py" and ends up in "Pythonista3.app/pythonista_2to3.py". I do not think the Python standard library has anything to do with it.
Here is the complete traceback of the exception I get when I select the "Python 2 to 3" from Pythonista's "Tools" menu:
```
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/20F14F02-CC89-49AF-A45D-3F34F2D72A92/Pythonista3.app/pythonista_2to3.py", line 7, in <module>
    import editor, io, os, shutil, tempfile, sys, difflib, ui, time, jinja2
  File "/var/containers/Bundle/Application/20F14F02-CC89-49AF-A45D-3F34F2D72A92/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/var/containers/Bundle/Application/20F14F02-CC89-49AF-A45D-3F34F2D72A92/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/var/containers/Bundle/Application/20F14F02-CC89-49AF-A45D-3F34F2D72A92/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/jinja2/nodes.py", line 18, in <module>
    from jinja2.utils import Markup
  File "/var/containers/Bundle/Application/20F14F02-CC89-49AF-A45D-3F34F2D72A92/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/jinja2/utils.py", line 520, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "/var/containers/Bundle/Application/20F14F02-CC89-49AF-A45D-3F34F2D72A92/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/markupsafe/__init__.py", line 228, in <module>
    from markupsafe._speedups import escape, escape_silent, soft_unicode
  File "/var/containers/Bundle/Application/20F14F02-CC89-49AF-A45D-3F34F2D72A92/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/markupsafe/_speedups.py", line 7, in <module>
    __bootstrap__()
  File "/var/containers/Bundle/Application/20F14F02-CC89-49AF-A45D-3F34F2D72A92/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/markupsafe/_speedups.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
TypeError: 'NoneType' object is not callable
```

**Comment by controversial** [comment]
It is standard library: https://docs.python.org/3/library/2to3.html

**Comment by RichardPotthoff** [comment]
What are you trying to tell me? That `Pythonista3.app/pythonista_2to3.py` is the same as the standard Python 2to3 tool, and that it is therefore somehow O.K. that it does not work in Pythonista?

Just try it out yourself: 
 * open Pythonista
 * open a writable Python source file
 * select the Python 2to3 Tool from the Tools menu that opens up when you click on the wrench symbol in the top left of the screen. 

When I do this, I get the error I reported.

**Comment by controversial** [comment]
Does this same script work with the desktop 2to3 tool? If so, I'm wrong.
I'm just trying to tell you that Python's 2to3 tool is not intended to work
in 100% of cases; it's not perfect. It's supposed to help you out a lot of
the time. But it works fine for me.

On Sat, Oct 1, 2016 at 9:26 PM Richard Potthoff <notifications@github.com>
wrote:

What are you trying to tell me? That Pythonista3.app/pythonista_2to3.py is
the same as the standard Python 2to3 tool, and that it is therefore somehow
O.K. that it does not work in Pythonista?

Just try it out yourself:

   - open Pythonista
   - open a writable Python source file
   - select the Python 2to3 Tool from the Tools menu that opens up when you
   click on the wrench symbol in the top left of the screen.

When I do this, I get the error I reported.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/omz/Pythonista-Issues/issues/148#issuecomment-250947960>,
or mute the thread

**Comment by RichardPotthoff** [comment]
It works even in Pythonista when I patch `imp.py` as described in my original report. Without the patch, Pythonista gets stuck at the "Preparing..." step when trying to run `Pythonista3.app/pythonista_2to3.py`. Here is a screenshot:
![img_0175](https://cloud.githubusercontent.com/assets/1579528/19018068/e346c236-8821-11e6-82af-2ccabdcadb94.PNG)

**Comment by controversial** [comment]
All right.

**Comment by Leva7** [comment]
Has anyone figured out a solution? The problem here is not with the 2to3 tool, but rather with the `jinja2` module. You can try executing `import flask` and you'll get this error as well
