### ISSUE TITLE
Default values for _scene_types.Color() don't work 

### ISSUE THREAD

**Issue by RichardPotthoff** [omz/Pythonista-Issues#150]
According to the documentation, <code>_scene_types.Color()</code> should create a Color object with all attributes (r, g, b, a) initialized to a default value of 1.0, but an Exception is raised instead:

<pre><code>    _scene_types.Color()
TypeError: __init__() missing 4 required positional arguments: 'r', 'g', 'b', and 'a'
</code></pre>

The same is true for all Classes created with the class factory <code>_scene_types.recordtype</code>

The problem seems to be, that no default values are specified in the generated class definition. The following modification to <code>_scene_types.recordtype</code> fixes this problem:

``` python
    numfields = len(field_names)
-   argtxt = ', '.join(field_names)
    reprtxt = ', '.join('%s=%%r' % f for f in field_names)
+   if init_defaults:
+     argtxt = reprtxt%init_defaults
+   else:
+     argtxt = ', '.join(field_names)
    dicttxt = ', '.join('%r: self.%s' % (f,f) for f in field_names)
```

**Comment by Dutcho** [comment]
see issue #149

**Comment by zrzka** [comment]
Just searched scene documentation and couldn't find a word about `Color` and default values of 1.0 for all color components. Reported more than one year ago, isn't this obsolete? Anyone knows more about scene module? Closing it. If you know more and I'm wrong, please, let me know and I'll reopen it.
