### ISSUE TITLE
objc_util.parse_types() is not documented

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#153]
http://omz-software.com/pythonista/docs/ios/objc_util.html

There are many others too...

```python
import inspect, objc_util
print('\n'.join(name + '()' for name, func in inspect.getmembers(objc_util)
               if not name.startswith('_') and callable(func)))
```

**Comment by jsbain** [comment]
This is not intended to be user facing, I thnk, in that it is not in __all__ for example.  The docstring is pretty explicit:

def parse_types(type_encoding):
	'''Take an Objective-C type encoding string and convert it to a tuple of (restype, argtypes) appropriate for objc_msgSend()'''
