### ISSUE TITLE
Weird block behavior 

### ISSUE THREAD

**Issue by lukaskollmer** [omz/Pythonista-Issues#155]
I don't know if this is intended or there is a reason I just don't know about but ObjC blocks don't work when they're passed directly to a function

This is my block:

```
def exceptionHandler(_cmd, _context, _exception):
    print("Error:", ObjCInstance(_exception))
```

When I first create an `ObjCBlock` Instance and then use that block, it works fine:

```
exceptionHandlerBlock = ObjCBlock(exceptionHandler, restype=None, argtypes=[c_void_p, c_void_p, c_void_p])
context.setExceptionHandler_(exceptionHandlerBlock)
```

However, when I directly pass the `ObjCBlock` Instance to a function, without storing it, Pythonista crashes:

```
context.setExceptionHandler_(ObjCBlock(exceptionHandler, restype=None, argtypes=[c_void_p, c_void_p, c_void_p]))
```

Is there a reason for this? I think both ways should work.

**Comment by jsbain** [comment]
I think because Blocks are not true objects, they don't get retained by the user.  It is really just a C struct, and the structure gets nuked when you call it the second way, once the ObjCBlock falls out of scope.

    ObjCBlock.from_param(exceptionHandler)
seems to handle this case by storing to ObjCBlock in the method so it does not get deallocated.

**Comment by jsbain** [comment]
You might try argtypes=[c_void_p, c_void_p, ObjCBlock), which seems like ctypes would then call from_param for you.

**Comment by zrzka** [comment]
Behaves as expected, also documented. You have to either store block somewhere or use `from_param`. Closing.
