### ISSUE TITLE
style is 'sidebar' in ui.View.present is handled in correctly 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#158]
Using - py3 beta.
If you pass 'sidebar' as style to ui.View.present rather than default to an unkown style, meaning full_screen, it does create a inaccessible view. I have to hard quit Pythonista, otherwise running the same code I keep getting the error 'View is already being presented....' Yet, if I  pass 'aaa' as the style, it defaults to full_screen same as '' does also.  
Not really a bug as its depreciated but it's a leftover

**Comment by zrzka** [comment]
`sidebar` acts like `panel` in 311014. In other words, it's accessible, closable, ...
