### ISSUE TITLE
editor.reload_files() is not documented

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#159]
There are others too.  It is documented in Editorial but not in Pythonista.

Also, editor.reload_files() is not available in appex but it would be quite useful as in https://github.com/cclauss/Pythonista-and-Working-Copy

**Comment by jsbain** [comment]
reload_files depreciated, it is stubbed out (at least in the beta), because there is a file watcher that mostly works

**Comment by controversial** [comment]
Closing as "fixed" (not relevant to later versions)
