### ISSUE TITLE
ui.ListDataSource init, should exude the need to pass items param 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#160]
I think I am correct in my thinking here. It's a pain to subclass ui.ListDataSource because of the required param items.  It makes sense when you are not sub classing, but when you subclass this param gets in the way.  Well at least I think it does.  It seems to me that you should be able to create a ui.ListDataSource object without any Params. Internally if no Params are passed, it could set up a empty list for items itself...
As far as I can see you need to have something like the below to avoid a error, regardless if you intend to use the passed items param or not.  

Again, I don't think it's a bug. But for me at least this does not seen the right way.

``` python
class MyData(ui.ListDataSource):
    def __init__(self, items = None, *args, **kwargs):
        items = items if items else []
        super().__init__(items, *args, **kwargs)
```

**Comment by cclauss** [comment]
items = items or []  # ;-)

**Comment by Phuket2** [comment]
@cclauss , yeah ok point taken.  But the ListDataSource obj should take care of it by itself.

**Comment by zrzka** [comment]
311014 `ListDataSource.__init__` contains check for `None` and if it's `None`, `items` are set to `ListDataSourceList([])`.
