### ISSUE TITLE
ListDataSource.number_of_lines _ wrong or misleading

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#161]
ListDataSource.number_of_lines, can basically accept, 0, 1 or 2.  But the help file leads you to believe any integer would be ok.  I have a feeling that it's written like this because in the beginning that was the idea of the implementation. It would be great if it was possible 😂😱 But if not, I believe the docs are ambiguous 
#from the docs
ListDataSource.number_of_lines
The number of lines that are used for the list item titles (equivalent to Label.number_of_lines).

**Comment by jsbain** [comment]
Not true.  you just have to set tableview.row_height.

``` 
import ui
items=['bloop'*20,'floop'*30]*3
L=ui.ListDataSource(items)
L.number_of_lines=7
t=ui.TableView()
t.data_source=L
t.delegate=L
t.row_height=30*L.number_of_lines
t.frame=(0,0,100,500)
t.present('sheet')
```

**Comment by Phuket2** [comment]
@jsbain , thanks. you are 100 percent correct.  I will close this
