### ISSUE TITLE
Appex.get_image crashes in Python 3

### ISSUE THREAD

**Issue by cvpe** [omz/Pythonista-Issues#169]
Appex.get_image crashes in Python 3 (not in Python 2) when sharing a photo

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by cclauss** [comment]
Are there workarounds for this bug using .get_attachments(), .get_image_data(), or .get_file_paths() and then opening the file the old fashioned way?  http://omz-software.com/pythonista/docs/ios/appex.html#appex.get_images

**Comment by cvpe** [comment]
I didn't try because the workaround of forcing #!python2 is sufficient to solve my problem. But lukaskollmer said that the same problem occurs with appex.get_input, thus I think this issue could be marked as a bug, isn't?

**Comment by cclauss** [comment]
Yes.  It is a bug.  When looking into fixing a bug it is often helpful to the developer to know what workarounds have been tried and which ones worked and which did not.

**Comment by cvpe** [comment]
Ok, sorry, understood!
I've tried appex.get_file_path but file is None when I try to share a photo

**Comment by cvpe** [comment]
I've tried 
  **f = get_attachments()**
and I receive 
**['/var/mobile/Media/PhotoData/OutgoingTemp/25A5C48E-1D4F-4F30-8286-02BCB17BE7C8.JPG']**
But how to read it to a PIL image to extract its exits?
I tried 
**Img = Image.open(f)** 
but I got error

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/606A7B2D-313E-48DB-BEB5-79336C85A91D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/PIL/Image.py", line 2301, in open
    fp.seek(0)
AttributeError: 'list' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/BC53E549-355D-4E77-BC46-64C3D3E0BDAF/Pythonista3/Documents/t.py", line 5, in <module>
    img = Image.open(f,mode='r')
  File "/var/containers/Bundle/Application/606A7B2D-313E-48DB-BEB5-79336C85A91D/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/PIL/Image.py", line 2303, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'list' object has no attribute 'read'

**Comment by chibill** [comment]
Try replacing f with f[0] as get_attachments returns a list not a string.

**Comment by cvpe** [comment]
Ok, thanks to both of you!
Replacing 
get_image 
by 
f= get_attachments 
img = Image.open(f[0] 
functions in Python 3!

**Comment by Phuket2** [comment]
But fair enough, it's a bug report. A bug is a bug, regardless of the work arounds. Not trying to be disrespectful, but the context here is to report bugs.

**Comment by cclauss** [comment]
Fixed in the current beta?

**Comment by omz** [comment]
@cclauss It doesn't seem to be fixed completely. https://twitter.com/lukas_kollmer/status/777591267186401280

**Comment by omz** [comment]
This should be fixed in the latest beta (build 301006).

**Comment by lukaskollmer** [comment]
@omz works for me
