### ISSUE TITLE
Random Numbers example uses xrange() instead of range()

### ISSUE THREAD

**Issue by JustSid** [omz/Pythonista-Issues#170]
Title pretty much sums it up, however, there is also a usage of the old range() behaviour (just a few lines above the xrange usage), which needs to be wrapped in list() now

**Comment by controversial** [comment]
Does this actually break the example, or is it just not optimal?

**Comment by JustSid** [comment]
It doesn't run at all due to syntax errors

**Comment by zrzka** [comment]
`Examples/Misc/Random Numbers.py` runs just fine in 311014. No more `xrange`, etc.
