### ISSUE TITLE
size_to_fit - nice to have a w, h Params - Enhancement

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#172]
size_to_fit does a good job as it's names suggest. But often you need to adjust the size as the result for a button for example is too tight(looks bad, no padding)  If you could pass params w,h to the function to grow or shrink the resulting overall size would be very helpful.  Like -
btn.size_to_fit(5, 5)

I normally have to do something like this to make it look ok -
btn.size_to_fit()
btn.frame = btn.frame.inset(-5,-5)

**Comment by zrzka** [comment]
`size_to_fit` internally calls [UIView sizeToFit](https://developer.apple.com/documentation/uikit/uiview/1622630-sizetofit?language=objc) and that's okay. It's perfectly clear and it clearly says what it does.

Introducing something like `size_to_fit(5, 5)` says exactly what? I mean, try to read it like a stranger who don't know what you are asking for. Is `5, 5` maximum size? Minimum size? But surely not insets.

I'm going to close this one.

If you want to control insets, there's better way:

* [contentEdgeInsets](https://developer.apple.com/documentation/uikit/uibutton/1624036-contentedgeinsets?language=objc)
* [titleEdgeInsets](https://developer.apple.com/documentation/uikit/uibutton/1624010-titleedgeinsets?language=objc)
* [imageEdgeInsets](https://developer.apple.com/documentation/uikit/uibutton/1624034-imageedgeinsets?language=objc)
