### ISSUE TITLE
Latest Beta 3 -  pyflakes , no console.hud msg if all is ok

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#176]
Not really a bug.  This may have changed also since I last used it.  But if you long press on the run button and select analyze, if all is ok no message is presented. In the past you received a console.hud msg saying something like 'no issues found'.  It's a small thing.  
I did a positive test, import uuid when not using any uuid functions, and it was reported correctly with the yellow fly out note.

**Comment by zrzka** [comment]
Analyze shows No Issues Founds HUD in 311014.
