### ISSUE TITLE
Addition of a animate_action attr - Enhancement 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#179]
Sorry if this is a little over the top or if the implementation idea is wrong.  But my thinking is if you could attach functions that conform to a certain standard/protocol to various events of the different ui elements.  Eg, views showing or closing, a button pressed, showing or closing etc.  so if you had a ui.View , you could add attach a function to when it becomes visible for example.  As well you could add another function for when it's hidden/closed.  The functions you have to supply to the events would have to adhere to your spec.  But I would expect it would return a dict or tuple for example  that contains the uiTransform as well as the duration, delay, completion func and whatever else makes sense.  

Just seems like this takes quite a bit of work at the moment to implement transformations gracefully.  If I just want a button, when pressed to scale 1.0 -1.2 - 1.0 as an effect, would be so nice if you could say do - btn.animation((self.my_scale_transformation_func, event='on_pressed'), (self.my_dissapear_compound_transformation, event='on_close')) or something like that.  I havnt articulated it so well, but I hope you get my general meaning.  

In my ui.view, something like this is needed 😬 I think even if you are very good at doing all the transform stuff, to do a complex view with transforms/animations gets messy very quickly.  If I am wrong because of lack of experience, then that's ok.  Just seems to me if the calling mechanism was built into the ui elements based on events, could save a lot of potential spaghetti code connecting it all up.

**Comment by zrzka** [comment]
Closing this one as I don't think Ole will implement something like this. It will be kind of maintenance, testing, ... nightmare. Write a lib / module for this you'd like to have it.

**Comment by mikaelho** [comment]
I think that since this issue was opened, ui.View.update has been added, making a lot of things easier/more reliable. (Shameless plug: ... and it is even easier with Scripter)
