### ISSUE TITLE
Quick Help not working in version 2.1

### ISSUE THREAD

**Issue by omz** [omz/Pythonista-Issues#18]
Invoking the "Help…" menu from the editor in version 2.1 always shows "no results", regardless of what's selected.

**Comment by zrzka** [comment]
I personally do not have 2.x version installed, but I assume that because it's marked with label `fixed in beta`, it's fixed. Closing. If I'm wrong, please, reopen.

**Comment by dgelessus** [comment]
Yep, it seems to be working in 2.1.1 (211008). Also Pythonista 2 isn't even available in the App Store anymore unless you purchased it already, so I don't think it matters much.

**Comment by zrzka** [comment]
@dgelessus I assume it's no longer supported, but people still do use it. See [this issue](https://github.com/zrzka/blackmamba/issues/29) for example :)
