### ISSUE TITLE
incomplete subprocess on py2.7 interpreter

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#180]
in 2.7, on beta 300106:

> > > dir(subprocess)
> > > ['CalledProcessError', 'PIPE', 'STDOUT', '**all**', '**builtins**', '**doc**', '**file**', '**name**', '**package**', 'errno', 'gc', 'mswindows', 'os', 'signal', 'sys', 'traceback', 'types']
> > > while in 3.3:
> > > import subprocess
> > > dir(subprocess)
> > > ['CalledProcessError', 'CompletedProcess', 'DEVNULL', 'PIPE', 'Popen', 'STDOUT', 'SubprocessError', 'TimeoutExpired', '_PIPE_BUF', '_PLATFORM_DEFAULT_CLOSE_FDS', '_PopenSelector', '__all__', '**builtins**', '**cached**', '**doc**', '**file**', '**loader**', '**name**', '**package**', '**spec**', '_active', '_args_from_interpreter_flags', '_cleanup', '_mswindows', '_posixsubprocess', '_time', 'builtins', 'call', 'check_call', 'check_output', 'errno', 'getoutput', 'getstatusoutput', 'io', 'list2cmdline', 'os', 'run', 'select', 'selectors', 'signal', 'sys', 'threading', 'time', 'warnings']

I am not sure what this looked like in the previous betas?  I am not sure, just noticed that stsh git is giving keyerrors now about subprocess.  I think the old code must have caught OSError but not KeyError.

**Comment by jsbain** [comment]
(old code=dulwich i mean). what i am requesting is that stdlib should at least have the same members, just let the exception get raised rather than removing unsupported functions.

**Comment by zrzka** [comment]
Pythonista 311014.

3.6.1

```
['CalledProcessError', 'CompletedProcess', 'DEVNULL', 'PIPE', 'Popen', 'STDOUT', 'SubprocessError',
'TimeoutExpired', '_PIPE_BUF', '_PLATFORM_DEFAULT_CLOSE_FDS', '_PopenSelector', '__all__',
'__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__',
'_active', '_args_from_interpreter_flags', '_cleanup', '_mswindows',
'_optim_args_from_interpreter_flags', '_posixsubprocess', '_time', 'builtins', 'call', 'check_call',
'check_output', 'errno', 'getoutput', 'getstatusoutput', 'io', 'list2cmdline', 'os', 'run', 'select', 'selectors',
'signal', 'sys', 'threading', 'time', 'warnings']
```

2.7.12

```
['CalledProcessError', 'MAXFD', 'PIPE', 'Popen', 'STDOUT', '_PIPE_BUF', '__all__', '__builtins__', '__doc__',
'__file__', '__name__', '__package__', '_active', '_args_from_interpreter_flags', '_cleanup', '_demo_posix',
'_demo_windows', '_eintr_retry_call', '_has_poll', 'call', 'check_call', 'check_output', 'errno', 'fcntl', 'gc',
'list2cmdline', 'mswindows', 'os', 'pickle', 'select', 'signal', 'sys', 'traceback', 'types']
```

@jsbain current status. Bug? Enhancement? Happy? Unhappy? Keep it open?
