### ISSUE TITLE
ui.convert_point crashing - using py3 beta

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#181]
Not sure this is just related to the beta, I suspect not.  I assume this function returns a pt rather than modifying the pt passed as it's a tuple. But to be sure I checked both ways. 
The following causes an instant crash.
```
my_pt = (10, 10)
np = ui.convert_point(my_pt, self.parent)
```
self.parent is valid. Even if I am not calling it correctly, seems a bit brutal to crash out.

**Comment by omz** [comment]
Should be fixed in the next beta; workaround for now: `ui.convert_point(my_pt, self.parent, None)`

**Comment by Phuket2** [comment]
Sorry, did not try the obvious

**Comment by Phuket2** [comment]
This bug is fixed in py3 beta, but still remains in the latest py2 beta, so I will leave this open.

**Comment by omz** [comment]
This should now be fixed in the latest Pythonista 2 beta as well.

**Comment by Phuket2** [comment]
Thank you, for the cases above this is fixed in py2 beta 211005
