### ISSUE TITLE
ui.DatePicker - crashing when using getattr Beta 3 issue?

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#184]
Not sure what the bug is. But if the below function is called with an instance of ui.DatePicker, Pythonista immediately crashes.  I have tested dir() on the instance and that is ok.  Every other ui class passes though this function without a problem, including the dreaded ui.NavigationView 😬

```python 
def get_full_dict(obj):
	# get all the dict attrs for obj, no filter
	return {k: getattr(obj, k) for k in dir(obj)}
```

**Comment by cclauss** [comment]
The MCS is:

```python
import ui
getattr(ui.DatePicker(), 'date')
```

**Comment by Phuket2** [comment]
Sorry @cclauss what is MCS? Regardless what it is, it just breaks things as this code worked before, but worse still more special casing involved in iterating over ui elements

**Comment by cclauss** [comment]
Startup companies striving for Minimum Viable Products (MVP) so I was striving for the Minimum Crashing Script (knowing full well that you would ask me to expand the acronym).   ;-)

**Comment by Phuket2** [comment]
Yeah, yeah, come to Thailand and have a drink with me and tell me that story😬😬😬😬
I thought either I had gone mad or the rest of the world had gone mad. I was betting on ROW

**Comment by cclauss** [comment]
Perhaps related to https://github.com/omz/Pythonista-Issues/issues/187

**Comment by Phuket2** [comment]
I am not sure as I am on 64bit.  I have a feeling it's a simple typo/ accidental edit that passes though the compiler.  But pretty sure it's about getting an attr.  Hmmm, possibly a type change in INT sizes seen this before when jonb was working with some objc code.  Pretty sure omz will see it straight away.

**Comment by omz** [comment]
Should be fixed in the next beta. The entire `ui.DatePicker.date` attribute is broken in the current build, no matter how it's accessed (via `getattr` or directly, Python 2 or 3, 32 bit or 64…).

**Comment by Phuket2** [comment]
I have checked this in 301010, is fixed.  Also did date assignments as well as iterating over the dict.
Thanks
