### ISSUE TITLE
clipboard.get() gives unicode error - 3.01 using python2

### ISSUE THREAD

**Issue by khilnani** [omz/Pythonista-Issues#185]
i've started getting a clipboard get unicode issue with my scripts that used to work before....  i get this even with a simple script with only print clipboard.get()

Error:

Pythonista3.app/Frameworks/Py2Kit.framework/pylib/site-packages/clipboard.py", line 8, in get
    return unicode(s, 'utf-8')
TypeError: decoding Unicode is not supported

Sample code:

import clipboard
print clipboard.get()

clipboard module:

std module clipboard >>
	"""get() -- Get the clipboard's text content as a unicode string"""
	s = _clipboard.get()
	if s is None:
		return None
	return unicode(s, 'utf-8') <<<<<<<<<<

Interpreter:  2.7
Pythonista version: 3.01 301007
Device: iphone 6 plus on iOS 10.0.2

Thanks!!

**Comment by omz** [comment]
I'll look into it. Workaround for now:

```python
import _clipboard
print _clipboard.get()
```

**Comment by khilnani** [comment]
Thanks!!

**Comment by jsbain** [comment]
Is this closed in the latest beta?  I cannot reproduce this.

**Comment by khilnani** [comment]
Works for me now. Thanks!
