### ISSUE TITLE
ui.ListDataSource new accessory_type radio_button - Enhancement 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#188]
I have probably mentioned this before, if not shame on me 😱 
Maybe I am missing a simple work around, but I don't think so.  A radio button accessory item would make ui.ListDataSource more powerful to the power 10.  

Of course it's not just a radio button graphic, it's the logic being in built to say to say any group that consists of only radio buttons infers that there is only one choice in the group. So you would hope that the implementation took care of the deselection of the other rows in the group as you pressed a radio button.  I can see this is a departure from how things are working now with the accessory items.  They can act independently without any knowledge of the other rows values.  

But it is a common use case senecio in my opinion.  Yes you can do it with ui.TableViewCell, but it's a shame to do all that work when ui.ListDataSource is so close to being able to bridge that last little gap 😬

**Comment by controversial** [comment]
I don't think I've ever seen radio buttons used in an iOS app, and I don't really think they work well in a touch environment. They're much better suited to a desktop computer. Isn't this what a `SegmentedControl` is for?

**Comment by cclauss** [comment]
http://ux.stackexchange.com/questions/78872/what-is-the-ios-alternative-to-a-radio-button

**Comment by Phuket2** [comment]
@controversial , I think radio button conjures the wrong image.  But there are times you want to make one clear selection rather than just the hilited row.  I did an example [here](https://forum.omz-software.com/topic/3547/tip-ui-rect-if-you-are-not-using-it-for-ui-you-should) in forum that uses buttons. It's not in a ui.TableView though

**Comment by Phuket2** [comment]
@cclauss, that's a good link

**Comment by zrzka** [comment]
Ian, please, noooo :) I'd recommend you to read [HIG Controls](https://developer.apple.com/ios/human-interface-guidelines/controls/buttons/) section. Also I don't think Ole is going to introduce radio buttons and I take the liberty of closing this one.
