### ISSUE TITLE
bottle error py2 beta (latest)

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#189]
I don't know enough about this but using the code from the help file as below produces this trace back.  It works in py3 beta.  It does not seem apparent to me what changes I should make to make it  python 2.7x compatible or even if it's possible in this case.

As an aside, the copy button in the py2 beta help file does not show hud, the copy happens just no feedback

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/A83A4237-28DA-41B4-AA91-84BC6770F30C/Documents/Example_7.py", line 7, in <module>
    run(host='localhost', port=8080)
  File "/var/containers/Bundle/Application/9895D35D-0872-46B5-8830-DD153733EA31/Pythonista2.app/Frameworks/Py2Kit.framework/pylib/site-packages/bottle.py", line 3111, in run
    server.run(app)
  File "/var/containers/Bundle/Application/9895D35D-0872-46B5-8830-DD153733EA31/Pythonista2.app/Frameworks/Py2Kit.framework/pylib/site-packages/bottle.py", line 2746, in run
    from wsgiref.simple_server import WSGIRequestHandler, WSGIServer
ImportError: No module named wsgiref.simple_server

```
from bottle import route, run, template

@route('/hello/<name>')
def index(name):
	return template('<b>Hello {{name}}</b>!', name=name)

run(host='localhost', port=8080)
```

**Comment by controversial** [comment]
Might be an issue with bottle and Python 2

**Comment by cclauss** [comment]
In Pythonista v2.1.1 (211003) beta, I think the Minimum Crashing Script looks something like this:

```python
import wsgiref
```

**Comment by cclauss** [comment]
@Phuket2 Should be fixed in today's beta release.

**Comment by Phuket2** [comment]
Confirmed this is working in 301010 (run as 3.5 or 2.7). But will not close it now. Will wait unti it's working in py2 beta

**Comment by Phuket2** [comment]
@cclauss , your msg turned up just as I was hitting the button on my reply, literally. But the most important for me is it works in py2 beta. I assume the py2 is using the same codebase as py3 2.7, meaning it's just a matter of once the py2 beta is updated.  I really hope the both versions remain purchasable, for obvious reasons

**Comment by omz** [comment]
This should now be fixed in the latest Pythonista 2 beta as well.

**Comment by Phuket2** [comment]
Downloading now......is thailand 🙄

**Comment by Phuket2** [comment]
Thank you, for the cases above this is fixed in py2 beta 211005
