### ISSUE TITLE
Using Ionicons images in scene module may crash Pythonista 2.1

### ISSUE THREAD

**Issue by omz** [omz/Pythonista-Issues#19]
From this forum thread: https://forum.omz-software.com/topic/3233/v2-0-vs-v2-1-hard-crash-using-reserved-var-names

> Going forward to 2.1 from 2.0, I have a bunch of "hard crashes" (direct go back to ios, no error, no message) when using certain var names in my scripts (working on 2.0)
> 
> I had tracked the issue and discovered that vars names like "self.target" in scene produce 100% the crash, but using "self.Target" works.
> [...]
> It looks like to crash only if files had been created with 2.0 using the Game/Animation template. If the file is created with 2.1 with the template it works.
> 
> If the file is edited using Sublime Text on Mac, it works after transfer (via drop box) on iPhone
> [...]
> Minimal example that also crashes 2.1:

``` python
import scene
class MyScene(scene.Scene):
    def setup(self):
        self.target = scene.SpriteNode('iob:alert_circled_256', parent=self)
if __name__ == '__main__':
    scene.run(MyScene(), show_fps=False)
```

**Comment by omz** [comment]
This should be fixed in the next beta. I initially thought this had to do with code completion, but it actually seems to be about certain built-in images (primarily in the Ionicons collections).

**Comment by zrzka** [comment]
Attached example doesn't crash in 311014, marked as `fixed in beta`, closing.
