### ISSUE TITLE
ui utility function ViewWalker or equivalent- Enhancement 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#190]
It would be great if a class/function like ViewWalker etc was a utility API of ui module.  Not really important how's it implemented I can imagine it can be done many ways.  But the fact it's part of the Pythonista API is the important thing.  @JonB code works well, it's just you have to include it. For sure you could add some extra functionality, like depth of the object etc. but the basic form would be great also 😬

[forum reference](https://forum.omz-software.com/topic/3381/re-share-ui-view-walker)

**Comment by Phuket2** [comment]
Actually, a func to assign kwargs to a ui object would also be great ui utility func  Yes it's  simple, but often want to use it.  If you want to make a function that creates a view for example, and you want to set the attrs with kwargs then you have a extra 3 redundant lines or you do it outside the function. Meaning the function is not standalone.  I only mention because you often want to use it with ui.  It would be still true even if ui objects dealt with all kwargs.  

But let's say in general there are some common python patterns that you tend to use over and over again when specifically using the ui.  I understand it's not Pythonista specifically it's pure python code, but it does not diminish its value as a utility routine.

Hmmm, ok I still have a feeling not many will agree with me 😂 But sh*t happens

```
def apply_kwargs(obj, **kwargs):
	for k, v in kwargs.items():
		if hasattr(obj, k):
			setattr(obj, k, v)
```

**Comment by Phuket2** [comment]
Also an equivalent of the below.  It covers 9 common ui placements.  What I have done is crap.  But something like this, just better would be great.  Would save a lot of time., well I believe so.

```
class ObjectMove(object):
	def center(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.center = sv.bounds.center()
	
	def topleft(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.x = sv.bounds.min_x 
		obj.y = sv.bounds.min_y
	
	def topright(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.x = sv.bounds.max_x - obj.width
		obj.y = sv.bounds.min_y
	
	def bottomleft(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.x = sv.bounds.min_x
		obj.y = sv.bounds.max_y - obj.height
		
	def bottomright(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.x = sv.bounds.max_x - obj.width
		obj.y = sv.bounds.max_y - obj.height
	
	def centertop(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.center = sv.bounds.center()
		obj.y = sv.bounds.min_y
	
	def centerbottom(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.center = sv.bounds.center()
		obj.y = sv.bounds.max_y - obj.height
	
	def centerleft(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.center = sv.bounds.center()
		obj.x = sv.bounds.min_x
		
	def centerright(obj):
		if not obj.superview : return
		sv = obj.superview
		obj.center = sv.bounds.center()
		obj.x = sv.bounds.max_x - obj.height
	```

**Comment by controversial** [comment]
I think `os.walk` does this well.

**Comment by cclauss** [comment]
@Phuket2 a tighter implementation would use the intersection of two sets...

```python
def apply_kwargs(obj, **kwargs):
    for key in set(vars(obj)) & set(kwargs):  # the intersection of the keys of two dicts
        setattr(obj, key, a[kwargs])
```

I have to say that I am not a fan of adding this to the ui module.  I have never needed this functionality and if I did, it is inexpensive enough to add to my scripts (or a module) by hand.

@controversial `os.walk()` allows me to walk the directories and files of a file system.  @Phuket2 's use case is to update the attributes of a Python object.

**Comment by jsbain** [comment]
We need another category of "enhancement". ... for simple code that users have created to solve specific narrow use cases, i agree with cclaus there is not really any reason to include in the app (and thus potentially create something new that breaks later).  

enhancement should be reserved for things that we rely on omz to create...  for pure python "convienence" functions, @Phuket2, I think maybe you need to create a ui_utils library and populate with some of these tools to be imported when you need them...

**Comment by Phuket2** [comment]
Ok, guys I expect what your saying. My main reason for mentioning it is that when doing ui' you use these small functions all the time.  And doing ui stuff is normally pretty verbose as it is. Yeah, I realise can have utility file I import all the time, but it is nice to make components that don't have any dependencies outside Pythonista.  
 Ok , I voiced my opinion, even if it isn't such a great one 😳

**Comment by Phuket2** [comment]
@cclauss , thanks for the tighter code.  Not sure if it executes faster or not, although I think in this case it's not an issue. Just nice it's 1/3 smaller.  Sounds silly.  As function not a big deal, but when you use it in line make a big difference.  Btw, if omz had considered this I understand he would have done his own implementations of course. Personally, I don't see how they are really any different from the what's listed in the Utility Functions section of the ui API now.  They all directly relate to ui, and omz already supplies pure python code for some things. Anyway, I will keep my fingers crossed 😬

**Comment by zrzka** [comment]
Read all comments and closing this. I also agree that it has no sense to include this in `ui`.
