### ISSUE TITLE
ui elements attrs types

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#197]
It appears that most ui element attrs have a discernible type such as float, bool, Rect (in terms of how to represent the data) etc... I know colours are expressed as tuples, but could they have their own type like RGBA without the underlying data type changing? I can see in your object Inspector, you know it's a color you are displaying.  I assume you don't rely on attr names for that.  Presently if we tried to write some mini-mini version of the object inspector, everytime we come across a tuple we would have to start looking at attr names to try to understand how to make a representation of the data rather than just show a tuple.  

I have no idea regarding the complexities of this under the hood so to speak.  I can only conclude that it would be easier for anyone who wants to make tools for ui that involves parsing/understanding the attrs data type.

**Comment by omz** [comment]
The object inspector actually just uses a simple heuristic for determining whether a tuple represents a color. It just checks if it consists of 4 numbers (rgba), and if the attribute name contains the string `'_color'`.
