### ISSUE TITLE
ui, list of creatable ui elements

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#199]
Currently as far as I know if you want a list of all creatable ui Elements, you have to create the list yourself, something like below. It would be good if the ui module could pass back this list.  To me it makes sense that it would.

```python 
self.ui_list = [
        ui.View, ui.Button, ui.ButtonItem, ui.ImageView, ui.Label, ui.NavigationView, ui.ScrollView,
        ui.SegmentedControl, ui.Slider, ui.Switch, ui.TableView, ui.TextField,
        ui.TextView, ui.WebView, ui.ActivityIndicator, ui.TableViewCell
        ]
       # need to add ui.DatePicker, once its fixed in py3 beta
```

**Comment by cclauss** [comment]
```python
import inspect, ui

def get_ui_classes():
    return [c for _, c in inspect.getmembers(ui) if hasattr(c, 'superview')]

print(get_ui_classes())
```

**Comment by Phuket2** [comment]
@ccc, wow. I wish I either knew or figured that one out that a long time ago. No wonder my scripts get so bloated with crap.  You should share that as a tip on the forum. I am not lazy to do it, it's just a mis representation if I do it.

I will  close this item, it still think it should be considered to be included as part of the API though.
