### ISSUE TITLE
SplitView screen with Extended Keyboard with Numbers option on

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#203]
When the extra row of numbers are added to the extended keyboard by using the Pythonista setting, the keyboard height appears to be mis calculated as the top row remains on screen when the keyboard is hidden/reduced. Happens in the editor and console.  If the setting is turned off, then the keyboard disappears as normal. That was in Portrait mode.  

In landscape mode if the extended keyboard option is on, the side view panel's height is to tall, obscuring a portion of the top row of the Keyboard.  

Makes sense. Appears the top row is not being considered in the calculations for split screen when it's present. I also tried a few apps in the split view, same result.  

I just did a pic of the portrait case, I think it's evident to what's happening.

Py3 beta (301009) , iOS 10.0.2, iPad Pro 12.9'

![](https://www.dropbox.com/s/z1im1u6v4zduzvk/File%204-10-16%2C%2018%2032%2010.png?dl=1)

**Comment by Phuket2** [comment]
Hmmm, sorry, this bug a little bit more strange than I reported. I am a little confused.  But it looks like that extra row of buttons are not suppose to be there when in split view. I mean split view after you resize it so it stays on screen.  So my next best guess is I brought the split screen up in such a way that the top row (extended) was not be being hidden....

Anyway, hopefully that's enough to track down the issue

**Comment by zrzka** [comment]
We no longer have extended keyboard with numbers, closing this one. Also I noted it down and if it will be added back, I'll retest it's functionality and will reopen related issues if they'll be still valid.
