### ISSUE TITLE
New image category - Pythonista

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#204]
This is a small thing, but to have the images used in Pythonista ui/ and the designer in an images category called something like Pythonista.  Or at least the ones that don't appear in other image collections.  At the moment, I am specifically thinking about the images you use in the designer to represent the different ui elements from the popover + menu.  Just would be nice when showing the ui elements in a ui.TableView to be able to also get a named Image from Pythonista.

Understand, this is at the bottom of the list of the list that was eaten by the dog.  But I thought it was worth mentioning.

**Comment by zrzka** [comment]
There are image categories you can use and I assume that they're kind of stable categories and they'll be provided _forever_. If you do use them in scripts, they'll probably work for a long time.

I consider Pythonista images/category as a private one, like private API. If you do allow users to use them easily, Ole will change them, scripts can be break (no images, different color, size, ...). Probably not likely to happen, but it still can happen. Also it will add another burden on Ole forcing him to think even about image removal, rename, change, ... and that's what we do not want.

Tempted to close this one, but will keep it open for another review round ...

**Comment by omz** [comment]
Agreed.
