### ISSUE TITLE
ui.flex some strange results sometimes, maybe a bug or misunderstanding how to use flex

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#207]
Sometimes I get some strange results at runtime setting the flex attr.  The screenshot below is of when presented as a sheet, but as full screen the bottom bar is in the right position but the width is a little inset.  That bottom view has flex='wlrtb'.  
But if apply flex = 'tw' then the flex is correct. 
You can not apply 'tw' as far as I know in the designer.  But in the designer 'wlrtb' works.  
I have looked pretty closely at what I am doing, I can't see why it should be different. If 'tw' didn't work, I wouldn't write this post.

I have just added a pic of the sheet view. 
@omz, I thought maybe this description was enough that it raises a red flag for you. If it's to vague, just kick it back to me. I Didn't include my code as there is too much.  But if this is not clear enough by description, then I will cut it down and try to make a specific case.

![](https://www.dropbox.com/s/nw0iugolbuhoxtu/File%205-10-16%2C%2023%2055%2058.png?dl=1)

**Comment by Phuket2** [comment]
Ok, I made this composite image. Is the full screen versions, side by side. The bottom bar is the issue.  Sorry, if I am just not using flex correctly.  But something does seem wrong to me.
![](https://www.dropbox.com/s/ionj0w2yetaja16/File%206-10-16%2C%2000%2034%2050.jpeg?dl=1)

**Comment by omz** [comment]
@Phuket2 `'tw'` looks like this in the UI designer:

![Screenshot](https://www.dropbox.com/s/c0o0lrrsnxsumio/IMG_0329.jpg?dl=1)

**Comment by omz** [comment]
In short, I think this works as intended. In your example screenshot, you *don't* want the **l**eft, **r**ight, and **b**ottom margins of the bottom bar to be stretchable, so `flex` should *not* include `l`, `r`, or `b`.

**Comment by Phuket2** [comment]
Hmmm, so it does 😂😂😂😂
There is no end to my shame 😱

Sorry, to waste your time.
