### ISSUE TITLE
Custom magic method for completion

### ISSUE THREAD

**Issue by controversial** [omz/Pythonista-Issues#213]
Autocomplete could be made much more powerful and much faster if Pythonista introduced a proprietary magic method like `__complete__`. If present, this attribute would be used to find autocompletions instead of using `dir()`.

This method could return something like the following:

``` json
{
  "property1": "static",
  "method1": "callable"
}
```

etc, mapping property names to a basic type used for autocomplete magic.

Sure, custom `__dir__` functions can be used, but this still means that the exact value of every attribute must be known, not just a general type. Authors could use `__dir__` to just return `lambda: pass` for callables and to return `""` for static attributes, but this requires major compromise on introspectablilty by people actually using `dir()`.

If this were implemented, people building classes with a lot of custom `__getattr__` and `property` logic could vastly improve the autocompletion time for their classes.

Let's make autocomplete great again™

**Comment by Phuket2** [comment]
The more I think about this, the more I like it.  I think I know what it is, primarily a hint for late binding functions or methods to the autocomplete. Maybe I have misunderstood.  But if I haven't , this would be great.  Also Seems like a worthwhile candidate for a PEP.  I know there is something you can do in the param definition to indicate/hint a type in py3.5x , but hint is ignored by the interpreter.  Is basically for tools doing introspection. I just bring it up as it's a similar idea/case.

**Comment by controversial** [comment]
Thanks @Phuket2. I don't quite think it's pep-worthy, since PEPs are **Python** Enhancement Proposals and Python doesn't include a built-in autocomplete engine, but I think it will work fine as a proprietary thing

**Comment by Phuket2** [comment]
@controversial , don't you think [PEP 484](https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-484), is similar? I can see how it could be classified different, attr the same time I could see how it could be considered the same.  Well loosely anyway

**Comment by controversial** [comment]
That's a good point, using type hints for autocompletion sounds like a good idea. However, type hints are very rarely used, and this wouldn't allow customizing the autocompletion to omit some attributes.

I think using type hints when available would be cool, but the `__complete__` method would still override this.

**Comment by Phuket2** [comment]
@controversial , I agree. Just replying to what you said about PEPs only for being Python Enhancement.  PEP 484, seems to be for tools to be introspective, the language ignores the hints.

**Comment by controversial** [comment]
Yep. Type hinting is sort of different because it's a much-requested feature that's common across many languages, but I do see your point.

**Comment by zrzka** [comment]
I don't think there should be something like `__complete__` introduced. Clutter code just because of Pythonista?
