### ISSUE TITLE
Python 2.7 re.sub() issue

### ISSUE THREAD

**Issue by MGageMorgan** [omz/Pythonista-Issues#214]
re.sub() is really jacking up in 2.7, despite working on the Windows version cleanly (I hate Windows with a flaming passion, but our school is full of ITs who know absolutely nothing about technology). I'm going to wireframe a minimalist sample because at the moment the program I'm working on is too complex to just paste here. Stay tuned, and KEEP IT OPEN.

**Comment by jsbain** [comment]
@lukaskollmer why does this have the bug tag?  unless there is an example, this is just unverified, and probably a bug in user code (it is highly unlikely that pythonista introduced a bug in standard library methods)

**Comment by MGageMorgan** [comment]
Yeah close it. Sorry, meant to provide an example. I figured it out and forgot a thread was open.

Cheers!
--MGage Morgan, co-founder and CEO of Christoffen Corporation. Find us online at https://christoffen.com




On Wed, Oct 19, 2016 at 10:55 PM -0400, "jsbain" <notifications@github.com<mailto:notifications@github.com>> wrote:


@lukaskollmer<https://github.com/lukaskollmer> why does this have the bug tag? unless there is an example, this is just unverified, and probably a bug in user code (it is highly unlikely that pythonista introduced a bug in standard library methods)

-
