### ISSUE TITLE
Renaming Folder via UI crashes pythonista

### ISSUE THREAD

**Issue by mithrendal** [omz/Pythonista-Issues#217]
Renaming a folder via the pythonista UI  leads to a crash of the app. After relaunching pythonista the folder has been renamed sucessfully. 

steps to reproduce:
1.tap a folder 
2.tap edit
3.tap the name change icon next to the name
4.alter the name
5.press done
---> crash

iOS 10

**Comment by Phuket2** [comment]
I also checked the above with ver 211005 and 301010,  both apps crash as above. iOS 10.0.2

**Comment by omz** [comment]
Should be fixed in the next beta.

**Comment by Phuket2** [comment]
I found this to work now in py3 ver 301011

**Comment by Phuket2** [comment]
Also 211006 works

**Comment by controversial** [comment]
Closing as fixed in beta.
