### ISSUE TITLE
sys.argv not initialized properly

### ISSUE THREAD

**Issue by balachandrana** [omz/Pythonista-Issues#220]
Consider running the following bug.py program
~~~
import sys
print(sys.argv)
~~~
- Run from editor after starting the application

output: ['']

-  long press run prompt and run with no arguments - returns properly

output:['/private/.../bug.py']

-  copy bug.py to  bug1.py
Restart the application, long press run prompt and run bug1.py with twp arguments "aa bb"

output : ['/private/.../bug1.py', 'aa', 'bb']

- Run from editor bug.py (returns output of bug1.py)

output : ['/private/.../bug1.py', 'aa', 'bb']

You get wrong outputs in step 1 and 4.

**Comment by omz** [comment]
This should be fixed in beta 301011 (I don't think this issue existed in App Store versions).
