### ISSUE TITLE
__init__ of subclassed ui.Views does not appear to work for frame attr - 301011

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#221]
@omz, this is great....  However the frame attr appears to work for a ui.View, but not for a ui.Button as below.

```python 
import ui
def my_action(sender):
	print(sender)
	
btn = ui.Button(frame=(0, 0, 150, 64), title='junk',
		border_color='white', border_width=.5, corner_radius=6,
		tint_color='deeppink', action=my_action)
		
print(btn.frame)

v = ui.View(frame=(0, 0, 300, 400))
btn.center = v.bounds.center()
v.add_subview(btn)
v.present('sheet')
```

**Comment by omz** [comment]
This is basically a "feature" of `ui.Button` in particular, which automatically sizes itself to fit the `title`, if it's provided as a keyword arg, so the width/height of the frame are basically overridden by the `title` argument.

**Comment by Phuket2** [comment]
@omz , ok sorry. I do remember @jonb pointing this out before.  To be honest though, it does not feel like a feature as you have the size_to_fit method, which I guess is being called internally automatically in this case based on the circumstances.  But it seems if you implicitly pass a frame and a title, the frame should take precedence.  Well, that's just my thoughts. It's still a small issue.  But very happy to have this functionality now 😁 If there were not so many people in the bar now, I would  buy them all a drink 😱
