### ISSUE TITLE
ui.NavigationView not honouring **kwargs 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#223]
In beta 301011, ui.Navigation does not honour kwargs.  I have hardly used this ui Element.  Just trying some things now.  I think it's only is supposed to take one param a ui.View.  I am not sure. The documentation does not say much.  But eg. The flex attr does not work when creating a ui.NavigationView.  I thought maybe it inherits from the view that is passed to it, but it does not seem to do so.

**Comment by zrzka** [comment]
Just tried to pass `frame`, `background_color`, ... and it works. This issue is too broad and it's probably fixed. If not, Ian, can you fill new issue with specifics like which kwarg is ignored and doesn't work, thanks.
