### ISSUE TITLE
Add new syntax grammars

### ISSUE THREAD

**Issue by Seanld** [omz/Pythonista-Issues#225]
I've been wishing for a way to add new syntax grammars (keywords, etc.) to Pythonista's syntax highlighter in order to highlight new languages.

I'd be cool to have a syntax page in which users could add and modify new and existing grammars. With this, you'd be able to add support for new languages (even new languages written in and interpreted by Pythonista!)

**Comment by Seanld** [comment]
Thanks. Couldn't find the labels. Barely use GitHub.

**Comment by controversial** [comment]
You can't add labels. Only I can ;)

**Comment by Seanld** [comment]
Oh

**Comment by controversial** [comment]
Is this phrased how you want? I don't think you want to say "themes," rather "syntax grammars," and you should specify that this is useful for editing new languages.

**Comment by Seanld** [comment]
Yeah sure. Edit it.

**Comment by controversial** [comment]
Ok. I'll delete these comments after (just clutter)

**Comment by Phuket2** [comment]
Sorry, I am not behind this.  I am not trying to be rude. But there are only so many hours in a day.  I would like to see those hours go to python/Pythonista development. Ok, it's not up to me. But I would say this is way off point.  Just my 2 cents worth of a comment

**Comment by Seanld** [comment]
@Phuket2 yeah, I agree. I just thought it would be an interesting feature.

**Comment by zrzka** [comment]
Closing, kind of generic issue. I'm not against this completely (love to have reST, ...), but I think we should fill issues per lang/grammar and discuss if it makes sense to add it.
