### ISSUE TITLE
How can I install Python packages?

### ISSUE THREAD

**Issue by tkdchen** [omz/Pythonista-Issues#227]
This is a question as the summary. I don't know how to do it, or is it possible in Pythonista? Thanks in advance.

**Comment by omz** [comment]
Please use the [forum](http://forum.omz-software.com) for general questions like this.

[This thread](https://forum.omz-software.com/topic/3536/how-do-i-load-a-module-from-somewhere-else-eg-dicom) might be a good starting point.
