### ISSUE TITLE
Ui Designer - picking an Image, the scroll view not being updated correctly

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#229]
Py3 ver 301011, In the ui Designer, the image picker scroll view is not updating correctly.  In the screenshot I am choosing an Image for a btn,  the same also happens for a imageview also.  It's not a timing issue.  As I have paused and waited to see if it eventually updates. It does not. 

![](https://www.dropbox.com/s/43zwio3ko0x4ck3/File%201-11-16%2C%2021%2040%2011.png?dl=1)

**Comment by zrzka** [comment]
@Phuket2 can you please retest in 311014 and attach new screenshot? It's not clear to me what's wrong from your description and it appears that almost all images you did attach in the past are broken (this is not first issue with broken image).

**Comment by zrzka** [comment]
No answer for 9 days, retested in designer (pick some images, ...), works. Without the image attached in the first comment and explanation, it's hard to check what was wrong.
