### ISSUE TITLE
Examples contain widget scripts, but widget is gone

### ISSUE THREAD

**Issue by omz** [omz/Pythonista-Issues#23]
The Examples folder still contains examples of using the Notification Center widget, even though the widget was removed in the release version (for those not familiar: it was a feature that was beta-tested, but there were too many stability issues with it).

**Comment by controversial** [comment]
Worth noting that the widget is also in the docs, #108

**Comment by zrzka** [comment]
Seems to me that this issue is invalid, because when I look at the list of available widgets in the notification center, Pythonista is there. Probably added back (I don't use it), right @omz? Examples are there. If yes and widget is/will be back, this one can be probably closed.
