### ISSUE TITLE
Ui Designer - exposing the hidden attr - Enhancement 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#233]
It's not a big deal, but would be nice if you could set the hidden attr of ui elements in the ui Designer. Would be nice also if the designer could visually indicate an object is hidden.  A icon or greying of the item etc, but even less important

**Comment by jsbain** [comment]
you can use the custom attribs to set hidden, or any other Attribute.  it just won't show you any indication in the ui designer.

**Comment by Phuket2** [comment]
@jsbain , hmmm you are right. It crossed my mind to try it. I don't know why I didn't.  Thanks.  I think I will close this.  This is reasonable
