### ISSUE TITLE
Close all editor tabs - super duper enhancement 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#235]
I am sorry to be a pain in the butt. But @omz this issue is a big issue in my mind. Maybe there is a simple monkey patch that can do this. I would love to hear if there was a such a way to close all tabs, maybe except the first tab.  I checked the editor.py just in case you added some undocumented functions there. I could not see anything new.  But with 2 new functions/methods in the editor.py you could help millions of people 😱😬💅🏽 Well, 10's or hundreds or thousands of people 😱
A func that returns a list of open tabs and a close tab func.  Ok, maybe you could have a close all func.  But with those 2 func's , besides just being able to close all the editor tabs which would be a gift from heaven , the smarter guys here could write some nice utilities for managing editor sets/ workspaces etc.
Again, sorry to be a pain.  And if there is a simple code workaround, sorry I missed it or am oblivious how to do it.  I just think for a small update, the potential upside for the users is huge.

**Comment by omz** [comment]
Programmatic tab management is something I want to do eventually, but not right now. For the next beta, I'll add a "Close other tabs" option (not programmatically, but in the normal UI), maybe that'll help as well.

**Comment by Phuket2** [comment]
Ok, that will still be a big leap forward.  Thanks.
