### ISSUE TITLE
A bug in URL scheme with version 300018

### ISSUE THREAD

**Issue by yjqiang** [omz/Pythonista-Issues#238]
HelloWorld.py:
#!python3
#coding: utf-8
print('Hello World')

------------------------------------------------------------
Check.py:
import webbrowser
webbrowser.open('pythonista3://HelloWorld.py?action=run&version=2')

------------------------------------------------------------------------------------------
According to [http://omz-software.com/pythonista/docs/ios/urlscheme.html](url), we can use "version=[2|3]" to use a specific interpreter for running a script. And when I run Check.py, it seems ok, but if I change to "version=3", Check.py doesn't call HelloWorld.py at all whithout any outputs.

**Comment by zrzka** [comment]
Works in 311014, both `versions` arg values tested.
