### ISSUE TITLE
Minimal Runtime for Wdget View

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#240]
Ok so the widget view is finecky we all know that. I purpose a minimal version of the python 3 runtime with unnecessary bits stripped out. Something like http://micropython.org/ but with a lot more functionality.
# Things we can strip out.
* Beautiful Soup
* Argparse
* Distutils
* lib2to3
* Venv
* Unittest
* libmodernize

Also a striped down version of the UI module would also be useful to save on space.

**Comment by dgelessus** [comment]
@scj643 Pure Python modules are not actually loaded until you `import` them, so deleting those files would have absolutely no effect on the widget's performance or RAM usage.

Built-in modules may or may not have an effect on the RAM usage - I don't know if the size of the executable counts towards the RAM limit. I'm also not sure if built-in modules are all loaded by default, or if they are only initialized when `import`ed.

MicroPython is meant for low-level programming on microcontrollers and such. As far as I can tell it's not really meant to run inside an operating system or anything, that's what normal Python is for.
