### ISSUE TITLE
logging ignores .basicConfig(format)

### ISSUE THREAD

**Issue by caedn** [omz/Pythonista-Issues#243]
```
#! python3
# coding: utf-8

import logging

logging.basicConfig(format='%(asctime)s %(message)s')
logging.error('something went wrong')
```

This code works fine on my Mac but fails to properly log under Pythonista 3.

Mac output:  
`2016-12-22 11:07:17,639 something went wrong`

Pythonista 3 with Python 3:
`Error:root:something went wrong`

Pythonista 3 with Python 2:
`2016-12-22 11:09:36,153`

Even if I comment out the `basicConfig` line I get the same results. Is basicConfig not implemented? `help(logging)` does indicate that this function does nothing if the root logger already has handlers configured, is this the case?

**Comment by jsbain** [comment]
your code works fine for me, on the latest py3 beta.

one thing to understand is that when you run a script, logging is not totally reset.  so any existing handlers might continue to exist.  i have found that "standard" cookbook must be modified to either check for and delete existing handlers.

you might try
     logging.root.handlers=[]
before basicConfig

**Comment by controversial** [comment]
Closing in light of @jsbain's solution. Appears not to be a problem with Pythonista.
