### ISSUE TITLE
Better code snippets

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#246]
Having code snippets that have multiple selected items that get replaced at the same time would be nice.

**Comment by jsbain** [comment]
how would that work exactly?  examples of what you want?

**Comment by scj643** [comment]
Say I have a snippet that makes a try block that sets a variable. When that errors I want it to set said variable to None. So instead of typing the variable twice I only need to type it once.

**Comment by omz** [comment]
While I agree that this would *sometimes* be useful, the implementation would be fairly complex for a feature that wouldn't get used very often.
