### ISSUE TITLE
Use WKWebView instead of UIWebView

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#249]
UIWebView is deprecated since iOS 8.0

https://developer.apple.com/reference/uikit/uiwebview

**Comment by omz** [comment]
At the moment, Pythonista still supports iOS 8, and `WKWebView` doesn't do everything `UIWebView` does until iOS 9. Specifically, loading local `file://` URLs isn't possible.

**Comment by mikaelho** [comment]
Even a parallel implementation would be excellent - WKWebView is developed, provides faster JS speeds, supports callbacks to Python code and fixes issues like scroll events only firing when scrolling stops.
