### ISSUE TITLE
UI Designer − Changes to a subview are sometimes discarded

### ISSUE THREAD

**Issue by Jollywatt** [omz/Pythonista-Issues#250]
Upon exiting subviews within the UI Designer, changes are not always saved, but are reverted to their state before the subview was ‘entered’. This seems to happen more often when subviews are nested.
Perhaps subviews should be saved immediately to prevent (incredibly annoying) data loss?

_Using Pythonista 2.1 on an iPhone 6 running iOS 10.2._

**Comment by zrzka** [comment]
Pythonista 2.x is no longer supported. If you have this issue in Pythonista 3, please, file a new issue. Also did test this briefly and it works as expected.
