### ISSUE TITLE
SceneKit classes seem to be missing from objc_util in newest Pythonista 2.1.1 build

### ISSUE THREAD

**Issue by bastikohn** [omz/Pythonista-Issues#256]
As of 2.1.1 I can not get any SceneKit class loaded with objc_util. 

I always get this error message:
![img_0112](https://cloud.githubusercontent.com/assets/673521/22388005/a1ad5e56-e4de-11e6-98db-53db337b603a.PNG)

The same code was working with the last build. Am I missing something?
Thanks!

**Comment by scj643** [comment]
You have to import the SceneKit framework

**Comment by omz** [comment]
Try something like

```python
objc_util.load_framework('SceneKit')
```

**Comment by bastikohn** [comment]
Thanks, got this code from the Slack channel:
```python
ObjCClass('NSBundle').bundleWithPath_('/System/Library/Frameworks/SceneKit.framework').load()
```
Seems to work after that!
