### ISSUE TITLE
Activity on slack

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#261]
@omz hasen't been on Slack for a couple months. Was wondering what happened.

**Comment by Hum4n01d** [comment]
+1

**Comment by scj643** [comment]
@omz can we get some explanation I'm quite dedicated and reliant on pythonista

**Comment by cclauss** [comment]
Some folks like instant messaging but many others folks do not.  The unplanned interrupts from IM often can break a train of thought at just the time when concentration can open new doors (products, features, bug fixes, etc.).  One little ping can make those doors difficult if not impossible to find again and reopen.  I created the Pythonista Slack channel but I very rarely go there.  Slack is great for those who use it but it is not an obligation for anyone.  @omz answers a lot of questions on the forum and he seems to use Twitter so you maybe you should ping him more there.

**Comment by omz** [comment]
Pretty much what @cclauss said. I find it pretty distracting at times, and the forum just works better for me personally – at least right now, my communication preferences change sometimes. :)
