### ISSUE TITLE
do not call retain for NSAutorelease

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#263]

**Comment by jsbain** [comment]
when creating an NSAutoreleasePool ObjCInstance, maybe need a check to not call release, since this causes a crash.  ObjCInstance calls that automatically.  Not sure if this is even possible or useful yet....

**Comment by jsbain** [comment]
i.e something like this:
``` 
        if ptr and not b'NSAutoreleasePool' in class_getName(object_getClass(ptr)):
            # Retain the ObjC object, so it doesn't get freed while a pointer to it exists:
            objc_instance.retain(restype=c_void_p, argtypes=[])
            objc_instance._cached_methods = {}
        return objc_instance
``` 

Alternatively, maybe an optional kwarg to disable calling retain.

**Comment by omz** [comment]
This is implemented in the latest beta, in addition to a convenient context manager that wraps an autorelease pool:

    with objc_util.autoreleasepool():
        # do stuff...
