### ISSUE TITLE
Keyboard frame change watcher outlives script execution

### ISSUE THREAD

**Issue by mikaelho** [omz/Pythonista-Issues#264]
If a ui.View implements `keyboard_frame_*` handlers, they keep watching for the keyboard frame changes even after the script is stopped and even when it is restarted. This causes unpredictable behavior until Pythonista is restarted.

Tested on version 3.1 (301016).

**Comment by jsbain** [comment]
A good workaround is to check `view.on_screen`, and then pass.  
Also, one can implement `close` and then delete the handlers.

**Comment by mikaelho** [comment]
Thank you! Filtering on `on_screen` probably works if I `import ui` in the handler - otherwise it seems to lose those references at some point. 

I am not 100% sure how I would delete the handlers - just `del` them from the `View` instance? Set a flag variable to stop body of the handler method from executing?
