### ISSUE TITLE
I get weird strings when I open a python file in atom

### ISSUE THREAD

**Issue by heecheon92** [omz/Pythonista-Issues#265]
So I opened 2 projects on atom.
All the python files in first folder works fine

but when I open any python files from the other folder
I get message below

Mac OS X        	2��ATTR;�����9�9com.apple.quarantine0083;5898901a;Safari;278957DB-2029-41D9-A430-CF0CE56CB1CCThis resource fork intentionally left blank   ��

please help me.
I am very new to Mac and text editor.

**Comment by dgelessus** [comment]
It looks like you're opening some of OS X's AppleDouble files in a text editor. They usually start with `._` (on external drives that aren't formatted for Mac) or are found in a `__MACOSX` folder (from badly extracted Mac zip files). Those files should not be read or edited directly, they are used by OS X and the Finder to store some extra info about files, like where you downloaded them from (that's what the "quarantine" and "Safari" part is about).

It's not quite clear how Pythonista is related to this - did you copy some files from your Mac to Pythonista, or the other way around? On which side are you seeing the strange file contents?

**Comment by heecheon92** [comment]
Hi thank you for quick response. As you said ive been opening ._ prefix file and i realized i have exactly the same file without the dot prefix. I usually save and open my file from my flash drive. But other than that i dont know how the problem occurred but i really appreciate your reply!
