### ISSUE TITLE
Locale module is not working

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#27]
https://forum.omz-software.com/topic/3163/pythonista-and-locale-module

**Comment by jsbain** [comment]
Perhaps this needs a doctest example?

**Comment by cclauss** [comment]
```python
import locale
locale.setlocale(locale.LC_ALL, 'de_DE')
```

**Comment by Chromecat** [comment]
tried this workaround and get: unsupported locale settings for de_DE any ideas ?
