### ISSUE TITLE
why i can't change print() color

### ISSUE THREAD

**Issue by INFINI7** [omz/Pythonista-Issues#270]
when i use
`print('\033[31m' + 'Hello, World' + \'033[0m')`
in console
the rusult is
`[31mHello, World[0m`
how can i change text color? except use console.set_color()

**Comment by dgelessus** [comment]
Pythonista's console is not a terminal emulator, so it doesn't support ANSI escape sequences for changing the text color. As you already found out, the correct way to change the output text color in Pythonista is with `console.set_color`.

**Comment by INFINI7** [comment]
Thanks,
I c. 
then how do i change color back to default?use console.set_color()

**Comment by dgelessus** [comment]
If you call `console.set_color()` without any arguments, it resets the color back to the default.

**Comment by omz** [comment]
Closing this, as I currently have no plans for full terminal emulation.

**Comment by Kamik423** [comment]
I would urge you to reconsider. The command line is an essential tool for many of us and really shapes the way we use python. A lot of my Python applications have `tqdm` progress bars, colored output or even line overwriting using ANSII. Those are scripts that have to work cross platform. With the use of the `colorama` module they even work on windows. Just iOS is lacking at the moment and it is a real pain to have my program output looking like this

![img](
https://i.imgur.com/g0rpEI0_d.jpg?maxwidth=640&shape=thumb&fidelity=medium).

**Comment by o-murphy** [comment]
@Kamik423 @infini7 @dgelessus

use overloads

[Pythonista console colored ansi print/input example](https://gist.github.com/o-murphy/c18342302a2ab09a9d8bfbf086248797) 

```
import sys
if "Pythonista" in sys.executable:
    import pythonista_ansi
    assert pythonista_ansi

print("\x1b[31mTEXT\x1b[39m")

input("\x1b[31mTEXT\x1b[39m")
```
