### ISSUE TITLE
Ignore subfolders on specific folders

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#273]
I keep the iOS SDK on my device which makes adding a new file take a little while to load. An otpion to exclude folders from the add file prompt would be useful.

**Comment by controversial** [comment]
The create and move file dialogs have long had performance issues. It'd be great if they didn't load the whole file tree at first, but lazy-loaded folders as their parents were opened.

**Comment by zrzka** [comment]
I don't think it makes sense to have configuration option for excluding folders. Also there's another issue for performance in these dialogs.
