### ISSUE TITLE
Ui views native shortcut actions

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#274]
Allow views to have keyboard shortcuts like how they work normally. also a way to add a shortcut that executes a function globally. Doing this in objc_util is unreliable

**Comment by zrzka** [comment]
Going to close this one. Not that I do not want to have this implemented, but because I filled lot of issues about HW keyboard shortcuts too and I will consolidate them as well. Probably will close lot of my issues as well, fill new ones grouped logically (including stuff from this one).
