### ISSUE TITLE
ui.TableView presented as panel crashes upon close

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#28]
Pythonista 3.0 (300018)
iOS 8.4.1 (32-bit iPad3,3)

```
ui.TableView().present('sheet')
```

followed by closing the tab results in a crash

> Objective-C exception details:
> 
> NSInvalidArgumentException: -[SUITableView_PY3 willDismiss]: unrecognized selector sent to instance 0x163ba800

**Comment by dgelessus** [comment]
This happens with some other views (e. g. `ui.ScrollView`) too.

**Comment by jsbain** [comment]
this seems to be fixed now

**Comment by jsbain** [comment]
Whoops, the original code to reproduce should read
    ui.TableView().present('panel')

**Comment by scj643** [comment]
I can confirm

**Comment by nilsj** [comment]
For me `ui.TableView().present('sidebar')` crashes in a similar fashion.

**Comment by zrzka** [comment]
I did check this and I can confirm that it still crashes in 311014. It seems to me that this can be kind of memory management issue?

**Doesn't crash**

```python
import ui

sv = ui.ScrollView()
sv.present('panel')
```

**Crashes**

```python
import ui

ui.ScrollView().present('panel')
```

**Comment by shaun-h** [comment]
Just wanted to add this code crashes it on close
```
import ui

nav = ui.NavigationView(ui.View())

nav.present(style='panel')
```

This is the fault log produced (cut down).

```
Fatal Python error: Aborted

Thread 0x000000016c0b3000 (most recent call first):

------------------------------------------------------------------------

Objective-C exception details:

NSInvalidArgumentException: -[SUINavigationView_PY3 willDismiss]: unrecognized selector sent to instance 0x131791f40

Stack trace:

0   CoreFoundation                      0x0000000185a2237c <redacted> + 148

```

**Comment by jsbain** [comment]
The same should work for SUIScrollView_PY3, etc

**Comment by jsbain** [comment]
The same should work for SUIScrollView_PY3, etc

**Comment by omz** [comment]
This doesn't appear to crash in the current version.
