### ISSUE TITLE
Pythonista location module

### ISSUE THREAD

**Issue by whearst3** [omz/Pythonista-Issues#281]
Sometimes a new call to :

`location.get_location()`

Returns exactly the same dictionary, as evidenced by the timestamp being identical down to the microseconds. For some reason this new call to refresh the location ... doesn't obtain a fresh location but returns the most recent one,  requested previously.

Is there some way to force a fresh update?  I don't need location updates on a short-term basis. Sometimes just once every five or 10 seconds, or after a "button push", mainly to debug my code. But for some reason this doesn't happen.

I find that if I shut down both Pynthonista, and my app, and then cold re-boot them,  I do get a fresh location dictionary.  I'm wondering why the Pythonista call to the iOS location manager is not generating a fresh location?.  

I have a suspicion this problem lies at the iOS level. Is there some trick to force a newly updated dictionary, even if the device physical location has not changed.  Perhaps location module could include an extra function  to reset the iOS layer's location manager?

When I move to a new physical location, sometimes miles away. I still get the old dictionary location, unless I shut down and reboot pythonista.

**Comment by whearst3** [comment]
My app was a small aviation app which would capture Lat/Lon  and convert answer to "Magentic  DIR" and "Distance in NM" from well established VOR locations in USA. Internet access not reliable in flight. And air traffic control (ATC) does not want LAT/LON  but approx location in English.  This voice communication is necessary only intermittently. So this small app had one button, push it, and app  reads geo position from iOS, and returns simple phrase e. g.   < 10 nm NW of OAK VOR>. 
So I need a fresh location, but not very often.

**Comment by jsbain** [comment]
Have you tried location.stop_updates() when you are done needing location, and start_updates() when you do?  That is a similar symptom when updates are stopped.

**Comment by jsbain** [comment]
if start_updates does kick start things, one way to check if updates are enabled would be to always get two locations, and check that the stamps are different

**Comment by whearst3** [comment]
This is the code fragment I have been using.  I will next run a code loop to query location every 10 seconds and capture the dictionary  timestamps.  Perhaps once one calls location.stop.updates ... updates can't be restarted? I will check that too.

def getpos():
   location.start_updates()
   datadict = location.get_location()
   location.stop_updates()
   (lat,lon) = (datadict['latitude'], datadict['longitude])
   return [lat,lon]

**Comment by whearst3** [comment]
Commented out the   `location.stop_updates()`  statement.

And the next calls to   `getpos()`   and  its `datadict = location.get_location()`  statement showed all new timestamps  (Hooray!)

Previously each new call to `getpos()` resulted in the same dictionary, and timestamp.

So,  your comment about :

>  ... similar symptom when updates are stopped.

... was insightful.  When  location is  stopped,  it stayed stopped.   I'd had wanted to stop updates after the Button is Pushed action, and then be able to start again. 

 But at least now I don't have to close Pythonista every time I want an updated location.  I seem to recall a warning about draining battery life if location updates aren't stopped. So I thought it was recommended to stop updates in between requests  ...  I suppose  if I am worried about battery life,  I will just halt Pythonista. Thanks for the note.

**Comment by jsbain** [comment]
Here is another approach that uses objc.  This uses requestLocation, which supposedly starts the updates, gets a location, then stops it.  I dont know if it guarantees a location, or not.  I also register the delegate if there is an error, so i think if you don't get an update, the fail method probably gets called.  
https://gist.github.com/2a69f3dbedd78eb52988afeed00558c3

The tricky bit seems to be that you cannot really use an Event() to hold execution, because this gets called on the main thread, and I could not figure out a way to have it called elsewhere.  But for something where you just want to respond to a button press, this works ok.

**Comment by controversial** [comment]
Feel free to reopen if you don't think your problem is solved
