### ISSUE TITLE
UI script launched from home screen icon ... can't find its .pyui 

### ISSUE THREAD

**Issue by whearst3** [omz/Pythonista-Issues#282]
Short Description: Both the .py and its associated .pyui are in the same folder on my iOS device. And the .py script runs fine. When it encounters ui.load.view('myapp') from inside Pythonista environment, the relevant .pyui view loads ... all is well.

But, when I run this script from an icon on the iPhone home screen. It hangs with a message about 
<can't find my app.pyui file >.

So I assume that when Pythionista loads "cold" it doesn't know where to find the associated .pyui file. Should I put it into a default directory? Which one? Or is there some way to indicate the path to search for .pyui files at runtime?

**Comment by whearst3** [comment]
Ole's suggestion 

> you could add something like this at the beginning of your script:

```
import os
os.chdir(os.path.split(__file__)[0])
```

turned out to be helpful. I moved both the .py script and its .pyui view to the top level of the Documents folder ... and all worked seamlessly.

I'm guessing the script looks for its .pyui file in the same directory where the script lives ... when launched from Pythonista.  

But when launched form the home screen it needs to told "where to look."  Or else defaults to the top level of the documents folder.  Anyway now it all works !

**Comment by cclauss** [comment]
The question is: Which thing made it work?
* Adding the `os.chdir()` call --or--
* Moving the files into the documents directory --or--
* Were _both_ of these steps required to make it work?

**Comment by whearst3** [comment]
The suggestion about `os.chdir()` got me thinking the default " expected location" when the app is launched from the home screen,  is not the same as when launched from Pythonista.  I wanted to use the standard process for creating a  home screen icon. 

So moved I the script and its .pyui into the top level of the documents directory.  A this stage of development, where I wanted to test the logic, and move the iPhone around to different LAT/LON locations,  I just wanted to make sure I could launch the app and it would reliably find its view.  I wanted to debug the logic, not fiddle with launch "modes."  I should go back and fix the script so it can run from anywhere, and still locate its .pyui. 

Also on my "do list" is cleaning up the code, and commenting it better.

**Comment by omz** [comment]
The "expected location" is the directory of the script you're running. It's a bug in Pythonista that this isn't the case when you launch it from the home screen.

@cclauss Either one of those would work. The bug is essentially a race condition – when a script is launched from the home screen or via URL scheme (same thing), with the app not yet running, it can happen that the other (Python 2) interpreter is still being initialized in the background, and the initialization process also changes the working directory... Next beta will fix this.

**Comment by controversial** [comment]
I believe this is a duplicated of #271. I'll close #271 in favor of this since this is a much more clearly phrased issue with more discussion.

**Comment by zrzka** [comment]
Did test with 311014, seems to be fixed.
