### ISSUE TITLE
Latest beta, keyboard does not come back after being dismissed

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#283]
I like the new paste and undo buttons on the extended keyboard!

One issue, though, is that on iPad / ios8.4, after dismissing the keyboard, there is not an easy way to get the kb to appear again.  i found that switching to editor, tapping the search button, then clicking in the find box does bring it back.  I am guessing this is just an artifact of the differences in ios8, or maybe differences in the new extended kb?

Other observations on ios8:  no backslash, (only forward slash), and i feel like a lot fewer dual-use (longpress) keys on the extended kb.

**Comment by omz** [comment]
Is there any way I could convince you to upgrade to at least iOS 9? 😉

Seriously though, it's quite possible that I won't support iOS 8 for much longer.

**Comment by cclauss** [comment]
;-) http://bgr.com/2017/05/03/android-7-0-nougat-update-market-share-may/
