### ISSUE TITLE
Keyboard not showing propely in split view

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#285]
In the latest beta it broke the keyboard on split view
![img_0392](https://cloud.githubusercontent.com/assets/5656510/25454924/02ff0d00-2a9c-11e7-9220-79728b94d0ef.PNG)

**Comment by lukaskollmer** [comment]
What's the problem? Looks fine to me

**Comment by scj643** [comment]
It used to split across the whole screen

**Comment by omz** [comment]
Completely forgot about this issue... It's unfortunately not easy to find a good solution for this – the one I used before [doesn't work very well on iOS 10.3](https://forum.omz-software.com/topic/3973/extended-keyboard-keys-shrunk), but this is no good either – it's even worse when Pythonista is in the narrow part of the screen.

**Comment by zrzka** [comment]
Works fine in 311015.
