### ISSUE TITLE
Calculator widget error.

### ISSUE THREAD

**Issue by wgaylord** [omz/Pythonista-Issues#286]
In the latest beta the calculator widget does not run because in the main method
`appex.set_widget_view(v)` should be `appex.set_widget_view(widget_view)`

**Comment by zrzka** [comment]
Still in 311015.

**Comment by omz** [comment]
Should be gone on a fresh install or when you restore the examples from the settings. I don’t overwrite existing examples on upgrades because it would be somewhat complicated to figure out if the user has made any changes in them.
