### ISSUE TITLE
HTTP Referer misspelling 

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#287]
In the wonderful land of HTTP headers a referrer is always misspelt as referer with one r

**Comment by cclauss** [comment]
Where exactly does this issue manifest itself?  Is this a documentation, API, or ui issue?

**Comment by omz** [comment]
I'm guessing in `appex.get_web_page_info()`.

**Comment by scj643** [comment]
Exactly though now that I think about it, it would be best to keep it as is since the misspelling is only on the http header. JavaScript spells it Referrer

**Comment by omz** [comment]
Agreed.
