### ISSUE TITLE
App sometimes crashes when tapping the file browser search text field

### ISSUE THREAD

**Issue by lukaskollmer** [omz/Pythonista-Issues#289]
I'm on the latest beta (311004).

Note: I can't really reproduce this reliable

**Comment by zrzka** [comment]
@lukaskollmer does this still happen for you? TBH, never experienced this crash.

**Comment by omz** [comment]
Closing this, as the script library is almost a complete rewrite in recent betas, so if a crash is still happening here, it likely is a different bug.
