### ISSUE TITLE
Help file - copy or open in editor (only copies the first 2 lines)

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#290]
In the Pythonista help file, if you use the copy or open in editor buttons imbedded in a code block, only the fist 2 lines are copied/displayed.  Beta 311004

**Comment by maedoc** [comment]
I ran into similar in Py3, nothing was copied or opened.

**Comment by zrzka** [comment]
Closing in favour of #436, where more info can be found.
