### ISSUE TITLE
Console.quicklook() crashes app in py3 when a list is given as a param

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#291]
As per the Pythonista thread [here](https://forum.omz-software.com/topic/4016/console-quicklook-crashes-when-pass-a-sequence-of-paths), the method console.quicklook() crash's Pythonista if a sequence is passed as a param. It's been confirmed it works under 2.7, just not 3.5.1

**Comment by zrzka** [comment]
Works in 311015.
