### ISSUE TITLE
add_subview - accept an iterable (suggestion)

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#293]
Eg.
v.add_subview([btn1, btn2])
Not really a issue, but seems like it should be able accept an iterable as well as the normal single usage

**Comment by cclauss** [comment]
Perhaps `v.add_subviews()` with an `s`.

**Comment by Phuket2** [comment]
cclauss, I suspect your suggestion with v.add_subviews is because the API already exists and it would not be very python like to have a API that both accepts a single value and a list of values in this case.  So to modify the method you would have to break it to keep it pythonetic so to speak.  Meaning the param would just be a list regardless if one view or 10 views.
I am just asserting to make sure I understand why you suggest a new method.

**Comment by zrzka** [comment]
Closing this one, reasoning:

* You can find lot of methods/functions where this should be added
* It will introduce more complexity in documentation, code, ...

Since we have Python, there's lot of other ways how to achieve this:

```python
import ui

views = [
    ui.View(background_color='yellow', frame=(0, 0, 20, 20)),
    ui.View(background_color='red', frame=(20, 20, 20, 20))
]


def functional_approach_with_map():
    v = ui.View()
    list(map(v.add_subview, views))
    v.present('sheet')


def list_comprehension_approach():
    v = ui.View()
    [v.add_subview(x) for x in views]
    v.present('sheet')


def for_approach():
    v = ui.View()
    for x in views:
        v.add_subview(x)
    v.present('sheet')


def apply_approach():
    def _apply(seq, method, *args, **kwargs):
        for obj in seq:
            method(obj, *args, **kwargs)

    v = ui.View()
    _apply(views, v.add_subview)
    v.present('sheet')
```

Some of them are _abusive_ like they create just-throw-away list for example, etc. Anyway, it was an example that there's a lot of ways how to achieve this.
