### ISSUE TITLE
black search color 

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#298]
Font color in search line is now black even in dark theme like Oceanic. I would appreciate a white color font

**Comment by wnMark** [comment]
Problem still exists in Beta 3.11013. In the general search on the upper left side, it works fine (white font and black background)

**Comment by omz** [comment]
@wnMark You're right, I *thought* I had fixed this a long time ago, but apparently not. I'll look into it.

**Comment by wnMark** [comment]
Thank you Ole for fixing this in 3.11014

**Comment by wnMark** [comment]
Solved in 311014.
