### ISSUE TITLE
PyFlakes is incompatible with f-strings

### ISSUE THREAD

**Issue by Dutcho** [omz/Pythonista-Issues#299]
In the most recent beta v3.1.1 (311008), the (included version of) analysis tool 'PyFlakes' (in te wrench menu) is incompatible with the f-strings, which Python 3.6 introduced. 
Analyzing a source containing an f-string raises an `AttributeError` `'Checker' object has no attribute 'JOINEDSTR'`. Temporarily removing the `f` before the string enables further analysis, but that isn't feasible if you have many f-strings.

**Comment by omz** [comment]
That’s listed as a known issue in the beta release notes. Will be fixed in the next build.

**Comment by Dutcho** [comment]
sorry, should have read the release notes
