### ISSUE TITLE
Syntax highlighting breaks on tripple-quoted f-strings

### ISSUE THREAD

**Issue by Dutcho** [omz/Pythonista-Issues#300]
try e.g. below fragment in latest beta
```
a, b, c = 1, 2, 3
s = f'''a\tb\tc
{a}\t{b}\t{c}'''
print(s)
```

This runs without problems, but displays with broken syntax highlighting in the editor

**Comment by omz** [comment]
Good catch!

**Comment by zrzka** [comment]
Looks good in 311015.
