### ISSUE TITLE
Printing to console - unreliable/crashes/stalls if printing modest amount of info

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#303]
This problem has been around for some time actually. If you run the code below, the output is very choppy and will more than likely crash Pythonista.
```python
import pytz
for tz in pytz.all_timezones:
    print(tz)
```

**Comment by dgelessus** [comment]
Strange, when I run this on my iPad mini 1, it is quite choppy (as you'd expect on such an old device) but I don't get any crashes. On my iPhone SE it runs more smoothly, also without crashing, but still takes a second or so.

If it matters, both of my tests are with a freshly launched Pythonista, using Python 3. My iPad uses the latest App Store version (3.1 301016), and my iPhone the latest beta (3.1.1 311008). I also have [this startup script](https://github.com/dgelessus/pythonista_startup/blob/master/customize_sys_hooks.py) enabled, but that should make my REPL *slower*, not faster. (Each `print` returns a `None`, which gets printed out in color and stored in the `Out` list).

**Comment by Phuket2** [comment]
I think the crashing mainly occurs when I touch the screen as sometimes I think it's frozen.  But I have had the above example crash, but also not crash without touching the screen.  It could be possibly a memory thing. I will try on my iPad Air later and see if it's different. I am using the latest beta 311008, but I have seen this behaviour for quite sometime

**Comment by zrzka** [comment]
No answer for 9 days, didn't happenning to me, closing.
