### ISSUE TITLE
Please add ability to sync scripts from dropbox/github repo

### ISSUE THREAD

**Issue by nojvek** [omz/Pythonista-Issues#304]
Editing code on iphone is no fun at all. Ability to sync scripts would make the experience so much more nicer.

**Comment by controversial** [comment]
It used to be the case that this was disallowed under Apple's guidelines. However, as of June 12, it looks like this might be allowed under [this change](https://www.macstories.net/linked/apples-app-store-guidelines-now-allow-executable-code-in-educational-apps-and-developer-tools/)

**Comment by Dutcho** [comment]
Interesting change, @controversial! Hadn't seen before, thanks for sharing.
Just thinking: Perhaps this policy change is a precursor to _Apple_ enabling **Swift** development on iOS (more realistically than in _Playgrounds_)?!

**Comment by zrzka** [comment]
I think this one can be closed in favour of iOS 11, drag & drop, iCloud, open in place from Dropbox for example, ... All these things nicely work in 311014.
