### ISSUE TITLE
ui.DrawString and preserving GState

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#307]
I am not sure if this is a bug/side effect or the way it was designed.  But it seems when you pass a color param to ui.DrawString it affects the ui.GState.  It was not what I expected.  I thought ui.DrawString would call 'with GState()' inside the method hence preserving the current GState. Not hard to work around, but feels incorrect.

**Comment by zrzka** [comment]
It's not a bug, not an enhancement. Developer is responsible for this. If you start drawing, you have to save state and restore it at the end to be a good citizen.

If all these DrawString, ... functions will be called within `GState` context and you'll call tens, hundreds of them, every call will lead to `_save_gstate()` & `_restore_gstate()`, which is not what you want.

Also if you do native apps, you have to do it in the same way.

You can learn more in [Core Graphics](https://developer.apple.com/documentation/coregraphics?language=objc) about this.
