### ISSUE TITLE
External Keyboard - cmd+w to close frontmost window (feature)

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#309]
I have started to using my iPad Pro external Keyboard more.  It seems like a pretty good coverage of key cmds. But it would be great to have a cmd+w to close the frontmost window when running ui apps. I am thinking more about the write/run/debug cycle.  Although, it still would be nice when using a ui app. Maybe there is another way to do it?

**Comment by zrzka** [comment]
Would be nice. But also it would be nice to use Cmd+W to close tabs, like Safari does. Close active tab, close active tab, ... when there's last opened file, close it and display default view with New File, Open Recent, Documentation, ...

**Comment by Phuket2** [comment]
I would like to revise my feature request here.  
For HW keyboards inside the editor, it would seem like a good plan would be to mostly follow safaris keyboard short cuts.
1. Cmd W - close tab (as mentioned above)
2. Ctl tab - show next tab
3. Ctl shift tab - show previous tab
4. Cmd T - New Tab (New file dialog)
5. Cmd I - show file info panel with file renaming ability, clickable go to dir (not invented yet :) )
6. Cmd ` - Can close a ui.View (acting like escape, cmd W is still good)
7.  Selectable key to accept auto complete.  I much prefer return rather than tab to accept the suggestion.

Oh. Just found out cmd L drops the function/method menu

Anyway, i am sure we all feel differently. But this makes sense to me :)

**Comment by zrzka** [comment]
Cmd-W already available in 311014. This issue contains other shortcut requests, but I'll consolidate them with other keyboard shortcuts issues. Noted down this one.
