### ISSUE TITLE
editor.get_path doesn't work for tabs that are not text

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#31]
When a tab shows a file in "info" mode (with the small thumbnail, name and type description, and the "Open In"/"Edit as Text" buttons) `editor.get_path()` always returns `None` instead of the path to the file.

**Comment by zrzka** [comment]
Still returns `None` in 311014.

**Comment by dgelessus** [comment]
Was fixed in build 311015.

**Comment by dgelessus** [comment]
Was fixed in build 311015.
