### ISSUE TITLE
ui.ListDataSource Events bug not fixed yet

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#310]
It seems like this bug should have a high priority as it can be very confusing if you follow the documentation to create a ui.TableView with the easy built in data_source being ui.ListDataSource. Reference forum [thread](https://forum.omz-software.com/topic/3468/subclassing-ui-listdatasource-dealing-with-events)
I have tried this in version 311008, it does not appear to be fixed

**Comment by zrzka** [comment]
I don't see this as a bug. `action` is attribute of `ListDataSource`. Default value is set to `None` and that's okay. That's pretty clear when you read documentation / look at the source code.

I know that Python is powerful, you can basically do whatever you want, but this?

```python
self.action = self.action if hasattr(self, 'action') else None
```

It will add more confusion. There will be examples with `.action = ...`, subclassed data sources with `def action(...)`, etc. And a lot of questions - what's correct? Which one to use?

If you'd like to subclass it and you'd like to provide action as a method of your subclass, Chris did show you how to do it.
