### ISSUE TITLE
Configurable editor swipe gestures

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#313]
While I am on a roll I thought I would mention this.  In the editor, it could be nice to have a preference/icon to control the behaviour of the swipe left/right.  Currently it shows the file navigation view/console respectively.  Personally, more often than not I would like to be able to swipe between the open files in the editor.  I am sure this is easily said, but a lot more difficult in implementation due to differences in iOS device sizes etc. just an idea

**Comment by zrzka** [comment]
I don't know what @omz thinks about this one, but I'm kinda against it. Here's [my favourite site](http://www.productstrategymeanssayingno.com) I'm showing to my guys at work on a daily basis. My nickname is Zrzka, but I have another on at work - no dog :)

It behaves as expected on the iOS. Any other switch, button, configuration option, ... is going to clutter the interface and makes it harder to use the application. Also user tends to forgot that they changed some setting and then they're producing emails, issues, ... that it doesn't work as expected, etc.

Keeping it open, Ole's call, but I would close this one personally.

**Comment by omz** [comment]
I'm against this too.
