### ISSUE TITLE
Keyboard shortcuts not displayed properly (iOS 11B4)

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#318]
Keyboard shortcuts are not displayed properly. It looks like that they are “covered” by Dock area. Happens on iOS 11B4. Don’t know if it was happening on earlier iOS beta versions, was waiting for 4.

![img_0018](https://user-images.githubusercontent.com/1084172/28581478-9580e10a-7162-11e7-8c31-6363e88af886.PNG)

**Comment by Shaolo** [comment]
Appears to work properly now on Beta 6.

**Comment by zrzka** [comment]
Seems to be fixed, no more issues with shortcuts.
