### ISSUE TITLE
HW keyboard shortcut - comment/uncomment lines

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#319]
It would be nice if we can get HW keyboard shortcut for comment/uncomment lines. I read the forum, I know that I can write script for this (already using it), I know that I can add it to the wrench menu, ... But it’s not convenient when I’ve got HW keyboard.

**Comment by jsbain** [comment]
Have you seen the thread re: assigning scripts to HW keys?
https://forum.omz-software.com/topic/3029/keyboard-shortcuts-physical
You can include something like this in your pythonista_startup

**Comment by zrzka** [comment]
@jsbain thanks, I know these threads. But I still think it would be nice to have it in the UI for people who are not aware of iOS SDK / UIKit / ... internals, etc.

**Comment by Shaolo** [comment]
I too badly want this to be a part of the default UI.

I want to hack on my Python scripts. Not the editor.

**Comment by zrzka** [comment]
Closing this in favour of #321. Toggle comments is a script, can be added to wrench and if #321 will be implemented somehow, this one will be done as well.
