### ISSUE TITLE
Outdated version number for Python 3 stdlib under "Modules & Templates"

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#324]
In the current beta (3.1.1 build 311008) under "Modules & Templates", the Python 3 standard library is still called "Standard Library (3.5)", even though the Python 3 version is Python 3.6.

**Comment by Dutcho** [comment]
Same applies to the little version indicator in the documentation browser (top-right of screen, next to documentation home button). The picker states 3.6, the indicator 3.5

**Comment by cclauss** [comment]
Fixed in 311013
