### ISSUE TITLE
Up/down arrow on external HW keyboard crashes Pythonista when its suggests a completion

### ISSUE THREAD

**Issue by Dutcho** [omz/Pythonista-Issues#325]
So:
- I type a few chars on my Apple Bluetooth keyboard
- Pythonista helpfully suggests one or more completions
- I push the (up- or) down-arrow on my external keyboard (intending to go to next suggestion)
- and I find myself at the iOS home screen (springboard)
- luckily my edits were saved

This happens consistently (also after reboot) on latest beta on latest iOS

**Comment by zrzka** [comment]
Works fine in 311015.
