### ISSUE TITLE
help('modules') - in beta 311008

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#326]
If you run help('modules' ), you get the error below before the modules print out.  I did it from a script, and it happens for 2.7 and 3.6. Looks important, maybe it's not.

/private/var/mobile/Containers/Shared/AppGroup/3533032E-E336-4C25-BBC4-112A6BF2AF75/Pythonista3/Documents/site-packages/passlib/crypto/scrypt/__init__.py:127: PasslibSecurityWarning: Using builtin scrypt backend, which is 100x slower than is required for adequate security. Installing scrypt support (via 'pip install scrypt') is strongly recommended
  "is strongly recommended" % slowdown, exc.PasslibSecurityWarning)
/var/containers/Bundle/Application/2A23FD4D-8164-4F78-9144-DD77D005D434/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/matplotlib/cbook.py:135: MatplotlibDeprecationWarning: The matplotlib.delaunay module was deprecated in version 1.4. Use matplotlib.tri.Triangulation instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)

**Comment by Dutcho** [comment]
Didn't know what `help(modules)` was supposed to do, so tried it.
I get the 2nd warning (about `dalenuay` depreciation, but cannot reproduce your first (about `passlib`); for me (latest beta, latest iOS), the command produces a nicely laid-out (4 columns) list of available modules.

The error message you provided, mentions `passlib`; I think this isn't provided in Pythonista, but was added manually (from `https://pypi.python.org/pypi/passlib`), so cannot be solved in Pythonista; the warning suggests installing `scrypt` for it to go away

**Comment by Phuket2** [comment]
@Dutcho, i am sure you are right. I guess I pip installed it with StaSh.  The reason I was looking at help(modules) was to see if it also listed the pip installed modules or just the shipped modules.  After the error msg I also get the 4 col printout.  
I know in StaSh I can do pip list to see what has been pip installed from StaSh.  But I had also upgraded some modules.  I was just looking for a quick way to see the modules Pythonista ships with.  
I didn't occur to me that an installed msg would have been creating that error. But it makes sense now after your post.  

Live and learn i guess.

**Comment by controversial** [comment]
Looks like this isn't a problem with Pythonista.
