### ISSUE TITLE
Initial sys.path contains 3 non-existing entries at end in Pythonista 3.6

### ISSUE THREAD

**Issue by Dutcho** [omz/Pythonista-Issues#339]
At Pythonista startup
```
import sys
print(*sys.path[-3:], sep='\n')
```
prints 3 entries that do not exist:
```
.../Pythonista3.app/Frameworks/Py3Kit.framework/pylib/lib/python36.zip
.../Pythonista3.app/Frameworks/Py3Kit.framework/pylib/lib/python3.6
.../Pythonista3.app/Frameworks/Py3Kit.framework/pylib/lib/python3.6/lib-dynload
```
Insignificant as an issue, as **no harm is done**, but perhaps a remnant from development.

After running a script in the IDE, `sys.path` is reset to the default (loosing both wanted modification from `pythonista_startup.py` and above 3 superfluous entries).

Latest beta (as python3.6 entries suggest), latest iOS

**Comment by zrzka** [comment]
Still there, minor one.
