### ISSUE TITLE
Add ipv6 support to Python interpreter

### ISSUE THREAD

**Issue by ijkim88** [omz/Pythonista-Issues#344]
Hi @omz,

I recently ran into some issues running scripts using requests and socket when I'm on LTE. I wasn't sure why this was happening, but with the help of the Slack chat I think I've narrowed it down. T-Mobile seems to have gone IPv6 only and iOS apps need to adapt to this: [T-Mobile Community Discussions - ios app using IPv4 address will not run  on T-Mobile network](https://support.t-mobile.com/thread/141082)

Some steps I took to help narrow it down to this:
* Running `Show IP Address.py` on LTE produces N/A while it works fine on WiFi.
* None of my scripts using requests or socket runs over LTE, but works fine on WiFi.
* The scripts on my iPad run fine when I use my iPhone as a Personal Hotspot
* Running `import socket; socket.has_ipv6` returns `False` which seems the Python interpreter did not get compiled with the ipv6 option
* The following script produced an exception `OSError: getsockaddrarg: bad family` showing it can't even connect via LTE:
```
import socket
s = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)
s.connect(('http://ipv6.whatismyv6.com/', 80))
s.close()
```

Can you confirm if the Python interpreter you compiled for Pythonista does not have ipv6 support? If so, can you release a new TestFlight version with support so I can verify if this was the issue I was seeing?

Thanks,
Isaac

**Comment by silverjam** [comment]
I'm seeing this as well.

**Comment by omz** [comment]
I can confirm that Pythonista is not compiled with ipv6 support at the moment. I'm not sure yet how much effort it'll be to change that tbqh, but it seems like something that can’t really be avoided.

**Comment by ijkim88** [comment]
Just tried the new beta, no more issues on T-Mobile. Thanks @omz!
