### ISSUE TITLE
Reformat Code (Wrench Item) adds an extra line to the eof

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#345]
This is not a big issue, but when you run reformat code wrench item, it adds an extra line to the end of the file.  This causes Check Style not to pass due to the extra line.

**Comment by cclauss** [comment]
Reformat Code is correct.  Check Style is wrong.  There should be a blank line at EOF.

**Comment by Phuket2** [comment]
Ok, I see.

**Comment by zrzka** [comment]
Closing this in favour of #302.
