### ISSUE TITLE
Crash on load w/ m4a present

### ISSUE THREAD

**Issue by maedoc** [omz/Pythonista-Issues#347]
I downloaded a m4a file into the main directory of Pythonista in the StaSH CLI.  Upon trying to open the file browser, the app closed.  When I press the P icon, the splash screen shows and then it closes back to the home screen.

Will I need to wait for some possible/eventual update fix or is there a way to delete that file?  Maybe running a URL with a script?

**Comment by omz** [comment]
Launching Pythonista by entering `pythonista3://` in Safari will probably do. the trick.

**Comment by maedoc** [comment]
With a URL to edit a script, I see the same behavior.

**Comment by omz** [comment]
@maedoc You mean the same crashing behavior, or that a URL to edit a script also works to fix this issue?

**Comment by maedoc** [comment]
Same crash when I open `pythonista3://awssg` where a script in my Pythonista home folder is `awssg.py`

**Comment by omz** [comment]
Okay, weird. Is this with *all* scripts or just specific ones. Does appending `.py` change anything?

**Comment by maedoc** [comment]
I don't remember names of many scripts to be honest in order to try, but it crashes if I include the `.py` extension or try to run the script.

**Comment by zrzka** [comment]
Just added labels bug, crash, will test tomorrow.

**Comment by maedoc** [comment]
This particular issue was that Pythonista would crash on app launch, and was resolved by an update a few months ago.
