### ISSUE TITLE
Custom views - will_close method - should be able to return False

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#348]
I know this has been brought up before. But i feel it got lost somewhere.  But it seems to me the will_close method on custom views should be able to return something to stop the dismissal of the view.  It can be very hard to control the program flow when someone taps the close X box. Ok, you can display the view without a menu bar and implement your own. But for normal cases, you would hope not have to do that.

**Comment by zrzka** [comment]
Repeating yourself, see #216 :)
