### ISSUE TITLE
Editor module - add analyze function

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#351]
It would be nice if `editor` module can have function like `analyze` (Wrench - Analyze item). Would be super useful for keyboard shortcut and I can think of other scenarios even without keyboard shortcuts.

**Comment by cclauss** [comment]
Overall I would prefer if the editor was ___always___ doing `analyze` and `check style` like Atom (with Python linter plugins installed) and other editors but that might slow things down too much on iOS devices.

**Comment by zrzka** [comment]
Can imagine this on the latest 12.9 iPad Pro. But then I'll fill another issue - ability to configure check style to disable some of them :) Hmm, it would be useful even now :)

**Comment by zrzka** [comment]
Closing this one, doesn't make sense after a while. Applying no dog to myself :)
