### ISSUE TITLE
Ui.TableViewCell - ui.TableView

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#355]
Not sure I am right about this or not, like most things :). 
But ui.TableView is very nice. Gives you a lot for free. But you are tied into using ui.TableViewCell for rows. However you can ***not*** subclass ui.TableViewCell.  
You have 3 different types of cell types currently.  But this just goes to layout.  
It seems to me if you could pass just a custom view as a ui.TableCellView it would be so nice.  You could do some API  enforcement with ABC i think.  
I realise, its possible to do the same using a ui.ScrollView etc... but you start to lose all the free stuff you have already coded. 

As i say, i know you can do it yourself.  But in a framework where you can pass a ui.View or maybe a new base class as a ui.TableViewCell could be so powerful as a built in

**Comment by omz** [comment]
Why not just *add* a custom view to an empty cell? Pretty much the same effect, no?

**Comment by Phuket2** [comment]
@omz, well its not really the same right?  There is no empty ui.TableViewCell. But i still take your point and will try to do that.
