### ISSUE TITLE
Toggle breakpoint shortcut

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#356]
Since I'm syncing Black Mamba shortcuts to well known ones (iOS, Xcode, ...), it would be nice if Pythonista can change `Cmd Shift B` to `Cmd \`. Then I can use `Cmd Shift B` for _Analyze & Check Style_ instead of `Ctrl Shift B`, which is hard to press (it's simply awkward).

**Comment by dgelessus** [comment]
From someone who uses a non-US keyboard layout - please don't use symbols in shortcuts... For example, on a German Mac/iOS keyboard, you type a backslash with Alt-Shift-7, so Cmd-\ would actually be Shift-Alt-Cmd-7.

**Comment by zrzka** [comment]
Sounds reasonable. Going to check the German keyboard layout. I've got Czech one and there's `\|` key.

**Comment by zrzka** [comment]
Applying no dog to myself. We have lot of shortcuts out of sync with Xcode, Xcode doesn't provide shortcuts for some Pythonista functionality, it doesn't make sense to change it after a while. It will puzzle users who already do use `Cmd Shift B`.
