### ISSUE TITLE
PEP8 max line length

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#359]
Default PEP8 max line length is 79. This value is kinda weird, ... I usually enforce myself to use 120. And I can imagine that iPhone users would like to have it shorter for example.

Would be nice if I can say somehow that I want 120 instead of 79.

**Comment by cclauss** [comment]
Settings / Indentation & Coding Style / Line Length

**Comment by zrzka** [comment]
Agree it's too long, but it's perfectly on iPad with keyboard (landscape). Depends on the situation.

Ouch, missed the setting. Thanks!

**Comment by cclauss** [comment]
SUK (Seldom use a keyboard)  ;-)
