### ISSUE TITLE
Do not force .txt extension

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#370]
What you can do if you'd like to create `README.rst` for example?

**One way**

* Tap on +
* Select Plain Text File
* Enter name `README.rst`
* Tap on Create button
* `README.txt` created
* Rename `README.txt` to `README.rst`

Cons - I have to always rename file.

**Another way**

* Do the **One way** in the `Templates` folder
* Tap on +
* Select `README` from `My Templates`
* Enter `README.rst` and extension is kept, `README.rst` is created

Cons - I have to create template for all extensions I do use.

Would be nice if `Plain Text File` selection can keep extension I do enter when I want to create new file.

**Comment by omz** [comment]
The current beta doesn't force any file extension for plain text files.

**Comment by zrzka** [comment]
Ahh, okay, thanks. Doesn't have access to beta, didn't know. Closing it. Would be nice to add label `fixed in beta`.
