### ISSUE TITLE
pythonista_startup.py not executed

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#379]
Kind of weird behavior and I didn't find it sooner, because I have always something opened.

1. Create `site-packages-3/pythonista_startup.py`
2. Put some `print('Hallo 3')` inside
3. Close all files in Pythonista
4. Force kill Pythonista
5. Launch Pythonista
6. Nothing in console, `site-packages-3/pythonista_startup.py` not executed
7. Open any Python file
8. Voilla `site-packages-3/pythonista_startup.py` finally executed

I would expect that if there's `pythonista_startup.py`, it will be executed upon startup and will not depend on opened / not opened files. It renders my features like Open Quickly... useles, because keyboard shortcuts are not registered yet. And I can imagine other tools, scripts, ... can have similar issues.

Or at least it will be executed if I launch full Pythonista (no widget, no share sheet, ...).

**Comment by dgelessus** [comment]
Yep, the Python interpreters only start up when they are first used - that is, when you type/run something in the console, or open a Python file (presumably for the Jedi-based code completion.

As far as I can tell, both start at once, even if only one of them is needed. I wonder if that could be changed - I almost never actively use Python 2 anymore, so maybe it would be possible to only start the Python 2 interpreter when opening a Python 2 file or running something in the Python 2 console. (The same would apply for the Python 3 interpreter of course.)

**Comment by zrzka** [comment]
Then the `pythonista_startup.py` is not a good name, because it's misleading. Probably others will be figuring out what's going on sooner or later.

@omz is there any problem with executing it when app is launched? Talking about app, not widgets, ... Something like ...

* Does `site-packages-3/ps.py` exists? Start Python 3 interpreter upon Pythonista launch.
* Does `site-packages-2/ps.py` exists? Start Python 2 interpreter upon Pythonista launch.
* Does `site-packages/ps.py` exists? Start both? interpreters upon Pythonista launch.

P.S. I no longer use Python 2 as well.

**Comment by omz** [comment]
@zrzka It's a bug. I almost always have a file open, so I didn't notice this for a while, but I'm aware of it.

**Comment by zrzka** [comment]
Works in 311015.
