### ISSUE TITLE
Keychain module - set_password - dict, ...

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#384]
We can store `NSData` in the keychain. Would be nice if `set_password` supports `dict`, ..., not just `str`. Same `dict` can be retrieved via `get_password`. Or at least, allow user to store & retrieve bytes (`NSData`).

**Comment by cclauss** [comment]
Could you use json.dumps() and json.loads() to get the desired functionality?

**Comment by zrzka** [comment]
Yes, I can. But would be nice if Pythonista can do it. `dict` was one example, next is `bytes` (can encode it to `str`), ... Basically nice to have.

**Comment by zrzka** [comment]
No dog to myself, doable even now (not with proposed methods). Anyway, `keychain` needs kind of overhaul, see #383 for example.
