### ISSUE TITLE
Editor module - left/right button items

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#386]
I'm working on some features for Black Mamba, which can be useful for people without external keyboard as well. Because of this, I did add an option to disable keyboard shortcuts registration via configuration. These new features can be accessed via wrench button. But I think that some of these features can perfectly fit left / right bar button items in the editor. IMHO it would be super useful if I can:

* `item = editor.add_left_button_item(ui.ButtonItem())`
* `editor.remove_left_button_item(item)`
* dtto for `_right_`

In this way, Black Mamba can add additional actions to the navigation bar during initialization.

**Comment by omz** [comment]
The main issue with this is that it wouldn't work very well on iPhone, where there's very little extra space in the toolbar, especially on the small models.

**Comment by zrzka** [comment]
Yup, you're right. iPad only? There's plenty of space.

![fd56de16-21d0-4916-9b59-d7d1fa43c37d](https://user-images.githubusercontent.com/1084172/30321408-3a29b4d8-97b6-11e7-895c-cbaf559fa7e0.png)

**Comment by zrzka** [comment]
Closed, reasoning in #387.
