### ISSUE TITLE
Idea: TODO/FIXME etc codetags

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#396]
I tend to use a lot of TODOs, and it would be nice to have an easy way to find them.  I think many IDEs these days have ways of managing/tracking/findng codetags.

This could appear as one of a few ideas:
   * embedded in drop down from filename (i.e include in list of classes/methods) for current file
   * as a separate area in file browser (tap opens up relevant file to proper line)
   * as a separate ui, in the wrench or longpress play menu (with check style)
   * maybe as annotations
Possibly showing all todo/fixme/custom codetags in a single folder, or all in current editor file and its imports.

**Comment by jsbain** [comment]
hey hey, codetags now show up in function browser in the beta! nice

**Comment by dgelessus** [comment]
It seems Pythonista only recognizes TODO/FIXME/etc. if they have a colon after them. For example, `# TODO: implement this` is recognized, but not `# TODO implement this` or simply `# TODO`. I use the last form relatively often, and if I do type a message I don't usually add a colon...

**Comment by omz** [comment]
@dgelessus Fixed in the new beta (build 311014).

**Comment by dgelessus** [comment]
It seems that TODOs etc. are not recognized if they are either right at the end of a line (i. e. directly followed by a newline) or if they are on a line that also has code on it. For example, the following "style" is not recognized:

```python
if condition:
    pass#TODO
```

Another suggestion: similar to the "number of annotations" counter, add a separate counter for the number of TODOs in the file. Perhaps the two counters should have icons next to them, so it's clear which one stands for what.
