### ISSUE TITLE
single quote in folder names prevents running script

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#40]
e.g `Jack's folder`. files under this folder cannot be run from the editor

**Comment by dgelessus** [comment]
Didn't we trace this down to being caused by the folder renaming? (Renaming a folder containing files open in the editor doesn't update the editor tabs to point to the new file names, so they switch into a broken read-only-ish mode.)

**Comment by lukaskollmer** [comment]
@dgelessus no, because files in a folder containing a single quote can't re fun after force quitting and re-opening Pythonista either. (The editor path is correct after the restart)

**Comment by dgelessus** [comment]
Okay, just tried it, and single quotes actually break script running. So these are two separate issues.

**Comment by dgelessus** [comment]
And the quote issue only happens with Python 3. Running the script with Python 2 (either as the default version or using the run menu) works fine.

**Comment by zrzka** [comment]
Just tried it (`Jack's folder/jack.py`) in 311014 and I'm able to run this script from the editor. Both Python 2 and Python 3.

![9154c21f-37be-4375-b912-19a413072977](https://user-images.githubusercontent.com/1084172/31860514-199b05a8-b71b-11e7-831f-6b9a923d839b.jpeg)
