### ISSUE TITLE
pyflakes are not dealing with f strings

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#409]
See this https://github.com/zrzka/blackmamba/issues/25. Whenever I try to analyze code (Black Mamba or Pythonista built-in analyzer), it fails when there're f strings. I think that I already saw this in Pythonista issues, but I can't find it. If it exists and I'm just unable to find, sorry for the duplicate.

**Comment by cclauss** [comment]
>>> import pyflakes
>>> pyflakes.__version__
'1.0.0'

https://github.com/PyCQA/pyflakes/blob/master/NEWS.txt

**Comment by Phuket2** [comment]
@cclauss, just out of interest, pip would installing/upgrading pyflakes using StaSh just solve this problem or is it more tricky than that?  Along the same lines, would it make sense to have a StaSh script that could install all the latest versions of the Pythonista supplied modules?  Or is this a recipe for disaster?  Seems strange to me that Pythonista does not ship with the latest modules (This example seems reasonable as 3.6 is still in beta).  I would had thought from @omz end this would be part of the build process.  Maybe he has to think about backward compatibility issues etc... I am not really sure. I thought it was worth mentioning though.

**Comment by zrzka** [comment]
Depends. AFAIK site-packages* path is before Py3Kit path and Pythonista will import these instead of the bundled ones. If you’ll update to the newer version, you can easily break some Pythonista functionality/scripts. Don’t do this unless you know what are you doing. There’s no point in updating packages without real reason. Just a new version is not a valid reason.

Beta is not bundled with latest packages? Yes, because there’s lot of work behind it. Testing, making sure everything’s working, ... Also it’s beta. Release cycle is long and you can expect outdated packages. There will be outdated packages because of this longer release cycle. Ole can change the model and say: ok, here’s basic Python IDE, use pip to install whatever you want. Then he will be forced to maintain/include StaSH & pip. Or custom pip. Another work. And pip in StaSH kind of works, but I wouldn’t base my app on top of it. Also there’s missing pip3. Lot of stuff doesn’t work with pip.

What about common users / scripters? You do not want to force them to use pip. What we are doing with Pythonista is pretty non standard if you compare it with majority of users.

Just my two cents ...

**Comment by Phuket2** [comment]
@zrzka , thanks for the detailed response.  Interesting to hear, as I just have no idea.  But without casting dispersions, I think some packages should be perpetually updated as the app is updated. The one that comes to mind is ptz. The current version in Pythonista is 2015.7, the current version 2017.x.  I understand its a lot of work, well i was guessing it was.  
Anyway, regardless I am happy for what we recieve, and it seems in most cases we can work around them.  My comments may sounded strange from a guy that never completes anything useful. I guess I hang on to the hope that one day I will.  Also hopefully bringing up some of this stuff in some way helps. It's never about stroking my ego, I am too old for that. I lost that a long time ago :)
But again thanks for talking the time to explain.  I really appreciate your efforts, both with BlackMamba and answers here and the forum.

**Comment by omz** [comment]
I think that this is fixed in the new beta (since build 311013).

@zrzka Can you check if this is still an issue?

**Comment by zrzka** [comment]
Yup, downloading ...

**Comment by zrzka** [comment]
Fixed in 311014.
