### ISSUE TITLE
Show file extension for user made templates

### ISSUE THREAD

**Issue by shaun-h** [omz/Pythonista-Issues#41]
App Version: Pythonista 3 (300018) 
If you create two files with the same name just different extension, example is Test.py and Test.txt

They appear in the My Template section of the new file screen as the same name so you don't know which one is which.

![image](https://cloud.githubusercontent.com/assets/1880053/16173652/c28eaece-35eb-11e6-82d9-32f02e95b3d7.jpeg)

Is it possible to show file extensions in the file screen? Either as test.py or the file extension as the detail line of the cell just below to main label?

**Comment by omz** [comment]
I don't really see a need to change this, as you could easily make your templates distinguishable just by using different names.
