### ISSUE TITLE
docutils not compatible with Python 3

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#410]
My default interpreter is Python 3. I did want to use `docutils` from Python 3, tried to import `docutils` and it failed because of `StandardError` (-> `Exception` in Python 3). Was checking where `docutils` are installed and found them in `site-packages`. Readme in this folder:

> This directory is included in the default import path of both Python interpreters (2.7 and 3.5), so that you can put reusable modules here.

I would expect that:

* current `docutils` package will be moved to `site-packages-2`
* `site-packages-3` will contain another `docutils` package, Python 3 compatible

`docutils` code base is Python 2, but `setup.py` does contain 2 -> 3 conversion if executed under Python 3. Also when you check [pypi](https://pypi.python.org/pypi/docutils/0.14), there're wheels for Python 2 and for Python 3.

**Comment by zrzka** [comment]
P.S. I didn't check other packages, but maybe we have more Python 2 only packages in `site-packages` and maybe even Python 3 only packages in `site-packages` as well. Don't know.

**Comment by dgelessus** [comment]
Pythonista does not install anything into the three user `site-packages` by default. Anything that comes preinstalled with Pythonista can be found in the `site-packages` folders in the two Standard Library folders.

My guess is that the Python 2 `docutils` were installed into the dual `site-packages` by Stash's `pip`. I recall this being an issue with other packages that have different versions for Python 2 and 3.

**Comment by zrzka** [comment]
@dgelessus Hmm, you're right. Not Pythonista issue, kind of tired after 20h.

I wish Pythonista has pip / pip3 bundled somehow, badly wish this ... Or any other way how to **officially** install packages. It's hard to provide _complex_ packages for others with dependencies when we haven't this. Getting tired of reinventing wheel via (`import requests as r; exec(r.get(...`), fixing / missing pip / pip3, ...

@omz What can I do to help with some packaging system for Pythonista? Officially supported? Whatever man, will do whatever, ...

**Comment by zrzka** [comment]
Forgot to close this one
