### ISSUE TITLE
[beta] webbrowser.open_new_tab - doesn't open new tab

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#412]
See my comment here:

* https://forum.omz-software.com/topic/4435/open-multiple-web-browser-tabs/9

When I check the implementation (in app browser), it just sends notification with `URL` and `reveal` in user info, but `new` arg value is not used at all. Subsequent calls open URL, but in the same tab.

**Comment by omz** [comment]
Right now, this only exists for source compatibility with the standard library `webbrowser` module.

Afaik Safari doesn't support controlling whether new tab is opened, but Chrome/iOS does (and it should work with Pythonista's `webbrowser` module).

**Comment by zrzka** [comment]
@omz I got it, but the bug is mainly about in-app browser, which is under full control. Question is if it makes sense to be source compatible when it works with Chrome only.

**Comment by omz** [comment]
@zrzka I guess I could enable multiple tab support for the in-app browser.

With regards to source compatibility, I think it still makes sense, even if it's not supported by most browsers. Even on the Desktop, there's no guarantee for the argument to be respected, and it's better to ignore it than to throw an "unexpected kwarg" exception, I think.

**Comment by zrzka** [comment]
@omz I'm not sure if I agree, but I also don't disagree, because I'm using output of my work in Pythonista / on desktop. I'm just thinking aloud, trying to think like Pythonista beginner, which already has some obstacles and knows nothing about webbrowser. It's more about target audience and which way is Pythonista going.

**Comment by omz** [comment]
The in-app browser now supports opening new tabs in the beta (build 311013).
