### ISSUE TITLE
Files opened from share sheet should go into new tab

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#415]
In the latest beta (build 311013), when opening a file from a share sheet (or from the iCloud Drive app), the new file goes into the last active editor tab and replace the file that was previously open there. This seems counterintuitive to me, because the file opening was triggered from outside the app. (Unlike tapping on a file in Pythonista's built-in file list, where replacing the current file is a more natural default behavior.)

Tested on an iPhone SE with iOS 10.3.3.

**Comment by omz** [comment]
I've implemented this in build 311014.
