### ISSUE TITLE
Allow opening files in a new tab by default

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#416]
When tapping on a file in the file list, it is opened in the current editor tab, replacing the file currently open there. It would be useful to have an option to change the default behavior, to make a single tap open the file in a new tab (and perhaps with "open in current tab" moved into the swipe menu, where "open in new tab" is currently). This is how IntelliJ/PyCharm behaves for example - double-clicking a file in the project view opens it in a new tab rather than replacing the current one.

To clarify, this is not the same topic as #415 - that issue is about the behavior when opening *external* files, this issue is about opening *internal* files.

**Comment by zrzka** [comment]
Seems dupe of https://github.com/omz/Pythonista-Issues/issues/333

**Comment by dgelessus** [comment]
Ah, my bad, thanks for the heads-up.
