### ISSUE TITLE
Buggy edit mode in read-only folders

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#418]
I know the "Modules & Templates" pseudo-folder isn't meant to be editable. However, swiping on a folder in it (as if I wanted to delete it) still does... something. The item moves over to the left slightly, but no buttons are visible and it bounces back once I let go. Then when I tap the file list anywhere, an edit button appears in the toolbar, which wasn't there before and doesn't belong there I think.

The edit button works as expected, more or less. It lets me select multiple folders, but there's nothing I can do with them (which makes sense, since they're read-only). Interestingly, once the edit button is visible, the buggy swipe behavior is gone - swiping on a file now is simply not possible, I always trigger the list scroll gesture instead.

PS: I just noticed that this happens in any read-only folder, for example in the standard library as well. ~~This meas the slide action to open a file in a new tab is broken for read-only folders~~ (no, it happens only when swiping on folders). Also, it might be useful to have the edit button in read-only folders, not to modify them, but to share files or run action scripts on them.

**Comment by omz** [comment]
The weird swiping behavior should be fixed in build 311014. Potentially adding an Edit button in read-only directories for sharing should probably be a separate issue.
