### ISSUE TITLE
Race condition in script library search

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#419]
I have more files than usual in my script library, for example the Python source code and iOS header files. This means that the new script library search, which also searches subfolders, takes a short while. It also seems to have a race condition, when I type fast enough, the search results update "out of order". For example, if I search for "abcd", it might show the search results for "abc", then "abcd", then "ab", then "a". (At least I'm guessing it's a race condition. It seems like every typed letter spawns a new thread that searches the script library for the text typed until that point, and the threads report their search results back in a more or less random order.)

**Comment by omz** [comment]
Should be fixed in build 311014.
