### ISSUE TITLE
No GPS access

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#426]
In Pythonista 3.11013 the possibilty to access GPS is missing (No options in setup available)

**Comment by dgelessus** [comment]
Strange, no issues for me on the 311013 beta (iPhone SE, iOS 10.3.3). When I typed `import location` in the Pythonista console, I got a dialog to allow/deny location access to Pythonista. After that, Pythonista is also listed in the location permissions in the Settings app.

Note: you don't get the permission dialog if you already gave Pythonista location permission before. I recently reset my iPhone's system settings (for a different reason), which also cleared all location permissions, so I got the permission dialog agian for Pythonista. I wouldn't recommend resetting all system settings just to fix Pythonista's location access though :)

**Comment by omz** [comment]
@dgelessus It probably has something to do with iOS 11. I've seen multiple reports of this with the latest beta, and it's the first beta that's built with the iOS 11 SDK.

**Comment by wnMark** [comment]
Problem on iPad with 11.03 and 11.1 Beta 3

**Comment by wnMark** [comment]
I found a workaround for accessing „location“ on IOS 11 and 311014 beta.
Install 311009 or version of App Store. 
Goto Settings of Pythonista 3 and goto location settings.
Install 311014
Run a app accessing location.
In Setup you have the option of „None“ for location of Pythonista.
Go one step back and you will have all options to grant access to location again.

**Comment by omz** [comment]
Interesting workaround. I found the problem now though, so it should be fixed in the next build.

**Comment by wnMark** [comment]
Ole, the workaround only works until I leave the Setup. Good you found the problem

**Comment by wnMark** [comment]
Thank you Ole.
Works fine in 311015
