### ISSUE TITLE
asyncio.get_event_loop().close() requires Pythonista 3 reboot

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#43]
https://forum.omz-software.com/topic/3240/asyncio-doesn-t-work-in-pythonista-3

``` python
loop = asyncio.get_event_loop()
loop.close()  # this will throw a RuntimeError on subsequent runs until Pythonista 3 is rebooted
```

`RuntimeError: There is no current event loop in thread xxx`

Workaround: Don't call `loop.close()`
@jsbain workaround: `loop = asyncio.get_event_loop_policy().new_event_loop()`

**Comment by jsbain** [comment]
Not a pythonista bug.  OP used wrong method to get a new event loop.  s/b
```   loop = asyncio.new_event_loop()
``` 

If you close an event loop from IDLE for example, you will get the same behavior.

**Comment by jeremyherbert** [comment]
Well to be fair, I didn't write any code. I literally open the example from the documentation verbatim: Section 18.5.3.1.1 example hello world coroutine 

All through the documentation it has get_event_loop() in the examples ?

**Comment by cclauss** [comment]
Fixed
