### ISSUE TITLE
Auto Edit as Text for rst

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#433]
Would be nice if Pythonista can open reST files automatically as text files. Forces me to raise my hand and tap on _Edit as Text_. Would be nice to support kind of syntax highlighting, but it's a story for another issue.

![bc6ece92-52fc-4d11-9075-4045cd520f49](https://user-images.githubusercontent.com/1084172/31766039-cb217836-b4c6-11e7-88df-053cf19e9df9.png)

**Comment by omz** [comment]
.rst files should be treated as text in build 311015.
