### ISSUE TITLE
will_close being called for tab switching

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#434]
panels now seem to call will_close when just switching to console, in latest beta.
seems like there should be a will_switch or will_disappear, etc, but will_close ought ti be reserved for clsing things?

**Comment by jsbain** [comment]
(this causes stash issues, since currently we use will_close to cleanup a stash session

**Comment by zrzka** [comment]
`will_disappear` pls (see https://github.com/omz/Pythonista-Issues/issues/392)

**Comment by omz** [comment]
Good catch! The changed behavior is the result of me trying to fix a bug where editor tabs wouldn't get notified of being closed when they were replaced by a different tab...

**Comment by zrzka** [comment]
Fixed in 311015.
