### ISSUE TITLE
Open search bar after „Highlight All“

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#435]
Using „Highlight All“ action should open the search bar and put the hightlighted text in the search bar. This works fine if search bar is opened before.

**Comment by wnMark** [comment]
If search bar is not opened you can not use the error keys. (It was more wired in a earlier version)

**Comment by omz** [comment]
Which "error keys"? I'm not sure what you mean by that.

**Comment by wnMark** [comment]
Arrow key at the end of the search bar

**Comment by wnMark** [comment]
I found another issue
Open search with symbol magnifying glass
Mark a text with action „Highlight All“
The text will be shown in search bar
But the arrow keys does not work until you change the text in search bar

**Comment by omz** [comment]
This should be fixed in the beta (build 311015).

**Comment by wnMark** [comment]
Thank you Ole.
Works fine in 311015
