### ISSUE TITLE
help system action „open in editor“

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#436]
Pressing „open in editor“ in help system, does copy the text, but does not open the editor

**Comment by zrzka** [comment]
Actually it opens the file named `Example_*.py` in the editor, but the issue is, that the help doesn't hide itself and thus you do not see the opened file / example. Just hide it with Cmd-J and you'll see that these files are there.

**Comment by omz** [comment]
Should be fixed in build 311016.

**Comment by wnMark** [comment]
Thank you Ole
