### ISSUE TITLE
Allow importing non-text files using "External Files" > "Open..."

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#439]
At the moment it seems that only text (and code) files can be selected in the "Open..." file picker. It would be useful if other file types could be imported too (perhaps with a separate menu item, if necessary).

**Comment by omz** [comment]
The plan is to add an "import file" option (allowing any type of file) to the "new file" dialog, analogous to (or combined with) the current "import photo" option.

Open-in-place only really makes sense for files that can actually be edited in Pythonista.

**Comment by dgelessus** [comment]
Great, that's basically what I was thinking :)

**Comment by zrzka** [comment]
Or open the whole folder, like git repo. Then you have access to whatever is inside this folder.

**Comment by omz** [comment]
I was just about to mention that. 👍

**Comment by dgelessus** [comment]
I'm on iOS 9/10... how does one "open" a folder rather than simply going into it? (This question sounds ridiculous, but you know what I mean :P)

**Comment by omz** [comment]
@dgelessus Ah sorry, I forgot. That's unfortunately only possible on iOS 11.

**Comment by omz** [comment]
@dgelessus Though it's far from obvious there as well. You'd have to tap the "Select" button in the document picker (which is buggy and sometimes doesn't appear), select the folder, then tap "Open".

**Comment by zrzka** [comment]
@omz yup, took me some time to figure this out as well, because the button is not there by default, but magically appears later when you do specific actions :)

**Comment by omz** [comment]
File import is implemented in build 311016, so I'm closing this.
