### ISSUE TITLE
Add to Home Screen

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#440]
On version 311014 adding to  „Home Screen“ did not work. Safari did not open. This is on iPhone5s with IOS 10.3.3

**Comment by dgelessus** [comment]
Strange, it's working for me (iPhone SE, iOS 10.3.3).

**Comment by wnMark** [comment]
I have retested this. It does work for files on device but not in iCloud

**Comment by omz** [comment]
Ah! That makes sense, thanks!

**Comment by omz** [comment]
Fixed in 311015.

**Comment by wnMark** [comment]
Thank you Ole.
Works fine in 311015
