### ISSUE TITLE
Cannot open a file in a folder that was just renamed

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#441]
Steps to reproduce:

1. Create a new folder called "RenameTest"
2. In the folder, create a new file called "renametest.py"
3. Close the newly created file
4. Rename the folder to "RenameTest0"
5. Without closing the file list, try to open the file again, this produces the error 'The file "thing.py" could not be loaded'

There's also a small bug in the behavior of the error message: it closes the editor tab in which the file would be loaded if it didn't cause an error. Ideally the previously open file should not be closed if the new file cannot be opened.

**Comment by zrzka** [comment]
Looks like it's similar to the #317. Maybe same issue under the hood.

**Comment by omz** [comment]
I think #317 should actually be fixed now. This one should be fixed in the next build.

**Comment by zrzka** [comment]
Okk, will check and close.

**Comment by omz** [comment]
Fixed in 311015.
