### ISSUE TITLE
Shift+Ctrl+Tab behaves oddly when 5-8 tabs are open

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#444]
When I have between 5 and 8 tabs open, have the first tab selected, and press Shift+Ctrl+Tab, Pythonista switches to an incorrect tab:

* ≤ 4 tabs: Everything works properly
* 5 tabs: Shift+Ctrl+Tab on the first tab does nothing at all
* 6 or 7 tabs: Shift+Ctrl+Tab on the first tab jumps to the fourth tab
* ≥ 8 tabs: Everything works correctly

**Comment by zrzka** [comment]
Confirmed, same behavior here.

**Comment by omz** [comment]
I *think* this is fixed in 311015. Could you test this again?

**Comment by dgelessus** [comment]
Yep, appears to be fixed - works on my iPad and iPhone.
