### ISSUE TITLE
Recent Files - highlighted file from previous search

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#451]
See attached screenshot. What I did ...

* Search for _keyb_ in library
* Cancel search in library
* Close all files
* Tap on Open Recent...

... and _keyb_ is highlighted here. Pythonista 311014.

![c450666d-4081-4683-8651-6e1105e443f3](https://user-images.githubusercontent.com/1084172/31876616-953886aa-b7d3-11e7-9eef-c69e16b89076.png)

**Comment by omz** [comment]
Fixed in 311015.
