### ISSUE TITLE
Files are moved even if I tap on Cancel button

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#452]
**How to reproduce**

* Create folder _Test_
* Create some files like _Test/test.pyui_, _Test/test.py_
* Reveal library, go to folder _Test_
* Tap on _Edit_
* Select both files
* Tap on move to folder button (toolbar at the bottom, next to the trash can)
* Do nothing and just tap on _Cancel_

Both files disappeared from the _Test_ folder and I've found them in the _~/Documents_. Basically they were moved even if I tapped on the _Cancel_ button.

**Comment by omz** [comment]
Good catch!

**Comment by omz** [comment]
Fixed in 311015.
