### ISSUE TITLE
Arrows for TableView in UI editor

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#454]
I would appreciate if Pythonista would support a option to add arrows to a TableView. The arrows Pythonista already uses to change the properties of some controls in UI editor.

**Comment by zrzka** [comment]
@wnMark can you elaborate more? What do you mean with _add arrows to a TableView_?

**Comment by Phuket2** [comment]
@  wnMark , have you used ui.ListDataSource as the data_source for a TableView.  ListDataSource accepts a list. Can be a list of strings or a list of dicts. The attrs for the dict are in the Documentation. Simple example below
```python
import ui

def create_tableview(frame, items):
    tv = ui.TableView(frame=frame)
    tv.data_source = ui.ListDataSource(items=items)
    return tv

if __name__ == '__main__':
    f = (0, 0, 300, 400)
    items = [{'title': str(i), 'accessory_type':'disclosure_indicator'}
                for i in range(20)]
    tv = create_tableview(f, items)
    tv.present(style='sheet')
```

**Comment by wnMark** [comment]
![8cd0249d-5db1-435a-a55a-837c64ae26d6](https://user-images.githubusercontent.com/16515557/32005364-62d65e58-b9a4-11e7-9f85-3f5d80320254.jpeg)
I marked the requested arrows

**Comment by zrzka** [comment]
@wnMark many thanks for the clarification. They're already there in 311015 (beta). See attached screenshot. Closing this one.

![24ab9c24-8c4b-4a59-84cb-c2da91c489db](https://user-images.githubusercontent.com/1084172/32005562-e59130ac-b9a4-11e7-89cb-d6fa9d155039.png)

**Comment by omz** [comment]
@zrzka I think what he meant was to make this kind of control available from Python code (i.e. being able to add this to your own `ui.TableView`. Am I getting this right, @wnMark?

Anyway, I have no plans to support this at the moment, so the issue can remain closed.

**Comment by wnMark** [comment]
Ole, thank you for clarifying this
Maybe in Version 5 ;-)

**Comment by zrzka** [comment]
Ahh, okay, thanks for catching this. Anyway, agree with @omz :)
