### ISSUE TITLE
The second extended keyboard row is missing

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#458]
Another issue that you're already aware of and that I just want to add as a reminder. The extended keyboard is quite useful when I don't have a Bluetooth keyboard around, and the second row has a few keys that aren't directly available in single-row mode (most importantly `#` and `>`). The keys are also larger in double-row mode.

I know that there was the issue with iOS blocking some taps when switching between the main keyboard and Pythonista's extra row too quickly. Has that changed in iOS 10/11 perhaps? Even if not, I found the extra row useful to have.

**Comment by omz** [comment]
I've brought it back for iOS 9+10 in build 311016.
