### ISSUE TITLE
Renaming a folder crashes Pythonista

### ISSUE THREAD

**Issue by lukaskollmer** [omz/Pythonista-Issues#46]
Related: #40

**Comment by lukaskollmer** [comment]
Example: http://cdn.kollmer.me/embed/pythonista_crash_rename_folder.mov

**Comment by omz** [comment]
I'm not quite sure why, but I can't reproduce this anymore in the latest betas. Could others check if this is still an issue?

**Comment by skrohmer** [comment]
It works for me on iPad 4 and iPhone 6 plus. BTW, when a file located in the renamed directory is open in the editor and after renaming you execute the file then it crashes (do I have to open a separate issue for that?). Maybe renaming crashes if a file in the directory is being accessed somehow.

**Comment by disorientedperson** [comment]
@omz this sometimes happens for me too on the latest beta.

**Comment by disorientedperson** [comment]
An iOS 10 bug maybe?

**Comment by omz** [comment]
@disorientedperson Hmm, could be. I don't remember if I was running iOS 10 when I tested this, and it was reproducible.

@lukaskollmer Are you running the iOS 10 beta in that video?

**Comment by disorientedperson** [comment]
@omz he must be because Swift Playgrounds is on his home screen

**Comment by omz** [comment]
@disorientedperson Ah, didn't catch that. Then I guess it's likely that it's somehow related to iOS 10. I currently don't have it installed on any of my devices, but that'll probably change soon.

**Comment by zrzka** [comment]
No crash on iOS 11 & 311014. Does anyone still experience this issues? No iOS 10 around.

**Comment by omz** [comment]
I don't think this is still an issue.
