### ISSUE TITLE
File navigator - editing mode is enabled when I swipe on a cell (swipe actions appears)

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#462]
**System Information**

* Pythonista 3.1.1 (311015), Default interpreter 3.6.1
* iOS 11.0.3, model iPad, resolution (portrait) 2048.0 x 2732.0 @ 2.0

**How to reproduce**

Swipe on a file in file navigator / library. It seems that the table view is kind of switched to the editing mode, because _Edit_ -> _Done_ button and rename button appears on the right side of the folder name. Tap on a cell to hide swipe actions, _Done_ -> _Edit_ and rename button disappears.

**Expected behavior**

_Editing mode_ shouldn't be enabled on the table view when I swipe on a cell.

**Screenshot**

![6bdf7f6b-7746-4bc8-a860-f3a1efee3272](https://user-images.githubusercontent.com/1084172/32123510-c3cb5364-bb64-11e7-80a5-a75992c6246e.jpeg)

**Comment by dgelessus** [comment]
This is normal iOS behavior. You can see this in Apple apps too, though it isn't always as obvious as in Pythonista. For example, if you go into the iOS Settings app > General > Keyboard > Keyboards, then swipe left on a keyboard to show the "Delete" button, you can see the "Edit" button in the top right switch to "Done" while the swipe menu is open.

**Comment by zrzka** [comment]
Edit vs Done yup, but the title is jumping because of rename button and it is kind of disturbing. Anyway, this one is minor.

**Comment by zrzka** [comment]
Did more investigation ...

* Whenever you swipe on a cell, iOS (read other apps) shows _Edit_ -> _Done_ (ok)
* Whenever you tap on edit, table view switches to editing mode and iOS shows _Edit_ -> _Cancel_, but there's still _Done_ in the Pythonista, should be _Cancel_ (to keep synced behavior)

... also when I swipe on a cell, I want to do something with the cell itself and I do not want to rename folder, that's what disturbs me. Anyway, as I wrote, this is really minor one.

**Comment by omz** [comment]
I've changed the behavior in build 311016 to hopefully be less confusing.

**Comment by zrzka** [comment]
@omz Nice touch 👍
