### ISSUE TITLE
The search bar at the top of a folder should search only in that folder

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#469]
Currently all search bars search the full filesystem (local and iCloud). I think it would make more sense to have each search bar only search in the current folder (or perhaps provide a ~~multi button thing~~ segmented control to allow switching between "everything" and "current folder").

**Comment by omz** [comment]
Ah, that's a bug. It's supposed to search the current folder (and subfolders), except on the first level (where it's supposed to search everything).

**Comment by omz** [comment]
I've changed the behavior in build 311016, so that the search bar in a folder only searches that folder (and its subfolders).
