### ISSUE TITLE
No notification widget available for pythonista 3

### ISSUE THREAD

**Issue by silvercomet** [omz/Pythonista-Issues#47]
I have just downloaded the app and did not see any new notification widget got added. Does anybody have this issue?

**Comment by controversial** [comment]
Yes, this is intentional. The widget was taken out of the final release due to stability issues, but @omz forgot to take out the examples. The widget may still make it into future versions of Pythonista. 

Happy Pythonista-ing!

**Comment by dgelessus** [comment]
The notification widget was only available in the beta, it was removed in the release version because it crashed often. See #23

**Comment by silvercomet** [comment]
Oh thanks for the quick reply. I saw it in the thread but still saw the examples so I thought it ran well so i thought it somehow went missing.

**Comment by dodekeract** [comment]
Any news on this? It's quite annoying since this would easily be the most convenient feature.

**Comment by omz** [comment]
A new widget is part of the current beta.

**Comment by dodekeract** [comment]
When is the planned/estimate release of that?
