### ISSUE TITLE
Some "special" folders can be renamed

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#470]
Build 311015 (though this issue has been around for a while IIRC).

Some folders that appear in special sections outside of the normal file tree can be renamed. This includes the three user site-packages, the "File Templates" folder, and the "Pythonista 2 Documents". The last one is probably the worst, because I'm guessing once you rename it there's no way to get it back (at least not without moving it back manually via Python). The others aren't that big of an issue, since after you rename them they'll probably appear in the normal file tree, and you can rename them again or move their contents back.

**Comment by omz** [comment]
"Pythonista 2 Documents" can no longer be renamed in build 311016. Renaming Templates or site-packages shouldn't really be a problem.
