### ISSUE TITLE
version URL scheme & shebang conflict - shebang should have higher priority than version parameter

### ISSUE THREAD

**Issue by zrzka** [omz/Pythonista-Issues#476]
**System Information**

* Pythonista 3.1.1 (311015), Default interpreter 3.6.1
* iOS 11.1, model iPad7,2, resolution (portrait) 2048.0 x 2732.0 @ 2.0

**Description**

You have a script with shebang line `#!python3`. When you run it in the Pythonista via run button, Python 3 interpreter is used even if you set Python 2 as default. But when you run the script via URL scheme, `version` is passed, shebang line is ignored and the script is executed under the interpreter specified via `version` parameter.

**How to reproduce**

Change default interpreter to Python 2 in the settings.

Create `demo.py` file:

```python
#!python3

import sys
print(sys.version)
```

Open console and run:

```python
import webbrowser
webbrowser.open('pythonista3://demo.py?action=run&version=2')
```

Console output is:

```
>>> import webbrowser
>>> webbrowser.open('pythonista3://demo.py?action=run&version=2')
2.7.12 (default, Nov 20 2016, 12:12:11) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

**Expected behavior**

I would expect that the shebang has higher priority than the `version` param and Python 3 is used. Also would be nice:

* if Pythonista can print warning to the console that the `version` parameter is ignored because of shebang line,
* or just document that the `version` parameter is ignored if the script contains shebang line.

Not a big deal, `minor` label added.

**Comment by omz** [comment]
The current behavior is intentional, so I've removed the *bug* label.

Using the URL scheme like this is essentially equivalent to holding the run button and selecting "Run with Python 2". In that case, the shebang is ignored as well.

**Comment by zrzka** [comment]
Taking it back, you're right. It's like running Python 2 on desktop with first arg pointing to the script with Python 3 shebang, Python 2 is used. Sorry for the mess.
