### ISSUE TITLE
executable urls not working

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#477]
311015, Ipad 3, ios 9.4
Two issues:
1) The "Create Executable URL' share menu item does not seem to escape everything that is required --  for instance parens are not escaped, but I think might be needed
2) Exec URLs don't seem to *do* anything right now, other than open up the file browser.  The pop up showing the code and offering to run it doesn't seem to work anymore.

**Comment by omz** [comment]
Should be fixed in 311016.
