### ISSUE TITLE
Git diff support

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#48]
The editor should have a way of telling changes using git (though using git is something you have to figure out yourself.)

**Comment by dgelessus** [comment]
You mean a `git diff` without `git`? That could be useful.

**Comment by omz** [comment]
I don't think that I'll implement something like this in the near future. You'd have to implement the rest of Git support yourself anyway, so you could just as well implement your own diff viewer (e.g. using `difflib` and a `ui.WebView`).
