### ISSUE TITLE
Hook/callback into the Run button - enhancement

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#481]
This may sound a bit stupid and maybe there is a solution already built into Python. I think It would be nice if you could set up a handler/callback or whatever the right jargon is.  So when you hit the run button, the first thing that happens, is a check is made to see if a handler has been setup for this purpose. If so that handler is called with some basic info before the run actually executes the file.  
What I have in mind, is basically making my own recents menu. But recents for me, makes most sense when recording the files that have been run/not opened.  Of course, I would have to do my own processing for duplicate runs etc... 
It's a fairly simple thing I am trying to do.  I guess such a hook could help others here about resetting the environment etc... I am not really sure. 
Possibly its too dangerous, again I am not experienced enough to understand the possible ramifications, but on the surface to me it seems like it could be helpful.

**Comment by cclauss** [comment]
I am not a fan of this suggestion.  This hook would not only pose new security dangers but would make it much more difficult to debug the same script running on different devices.

Today when users post to the Forum “_I pressed the run button on script x..._”, before we can help them to debug, we need to understand 1) what is their current default interpreter and 2) what is shebang on line 1 of script x.  We should avoid adding more complexity at this level or debugging will become more complex.

I believe that the results of taping the most important button in this application should be as simple and universal as possible across all machines and all users.

**Comment by Phuket2** [comment]
@cclauss , I also agree with you. But to me its still tempting.  In away its such an important event to be able to capture globally.  But as I say, at the same time I agree with you
