### ISSUE TITLE
Ui Module (set_focus, tab seq number) - enhancement

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#485]

**Comment by Phuket2** [comment]
@omz, with the raising popularity of connected keyboard boards to iOS devices (well the usage of them), it seems like the ui could use a few updates.
1. A set_focus method for any ui.control.  I know you can do this for a textfield by using the begin_updating method.  But you may want another control to have focus.
2. An attr(int) to describe specify the tab order of controls on a view.
 
I realise these are throw back ideas to VB6/HyperCard etc, but they worked well for ui's.  

***Ok, there is still one huge thing missing, a key dispatcher/event for views.*** It also seems to me that you should be able to capture keystrokes in the a custom ui.View. 
I think I understand why It was not implemented, in that for a long time iOS devices were considered primarily touch screen devices.
But this concept of replacing your laptop with a tablet has been gaining a lot of momentum as the screens have got bigger and faster processors. And while it not be there just yet for many ppl, for others it is. 
Anyway, food for thought.  I think ext keyboards being used on iOS devices are only become more common as time goes on not less common

**Comment by zrzka** [comment]
I feel almost guilty closing another of your issues Ian. Hope, you doesn't take it personally. You have interesting ideas, really.

Anyway, your proposal is not compatible with they way how iOS works. I highly recommend to read [UIResponder](https://developer.apple.com/documentation/uikit/uiresponder?language=objc), [Understanding Event Handling, Responders, and the Responder Chain](https://developer.apple.com/documentation/uikit/understanding_event_handling_responders_and_the_responder_chain). You can get some idea how it works from these links.

What you want, is basically another, heavily customised layer, on top of UIKit. And maybe it doesn't sound like a huge amount of work, but it is / will be. And not everything you did mentioned is possible.

It's crucial to remember, that Pythonista leverages iOS & UIKit capabilities. All UI you see, even from designer, simply uses UIKit controls. There are just some wrappers around them to make them easily accessible from your Python code. That's it.

Also remember that Pythonista is an Python IDE, which exposes all these iOS & UIKit things for you. So you can use them. But AFAIK the goal is not to create another UIKit. We should focus on IDE itself, how to make it great, how to integrate more modules, make it extendable for example, ... Lot of ideas. But it really doesn't make sense to write yet another UIKit on top of UIKit.

I take the liberty to close this one as well. If you disagree, feel free to discuss it.

P.S. Also there's no official way how to capture key strokes in the UIView. There is, but private API, ... In other words, Pythonista can't do this.

P.S.S. I highly recommend, although I hate Radar, to [report things like this to Apple](https://developer.apple.com/bug-reporting/). iOS can be enhanced in a way you want and Pythonista can benefit from it.

**Comment by Phuket2** [comment]
@zrzka , of course I dont take it personally.  You are doing a great job for the community by filtering these issues.  On this issue, I think in the future apple may change their direction, hmmm maybe.   
In terms of the keystrokes, I wasn't aware that this was not part of the UIKit (because I know nothing about it).  I just assumed keystrokes would be passed up the event chain.  
Look I am probably wrong, but my view is that iOS was build without the hindsight of how important/integral  physical keyboards would become.  Maybe it has reached that critical mass yet needed for them to think about changes.  But I think it will come.  
I agree with all you say above, should not be inventing new stuff.  For me I just didn't realise it was new stuff.  I am getting old now, I just hope they make some changes before its too late for me :)
