### ISSUE TITLE
Ui Module (Alt to switch control) - enhancement  

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#488]
It would be good to have a ui control like a checkbox.  The ui.Switch makes sense in a ui.TableView.  But sometimes it does not make sense when you are building a view in the ui Designer.  Whilst they are basically equivalent, in a ui sense they are not.  The ui Switch is pretty bulky if you need to have a few options.  Some how a checkbox seems more appropriate in some situations.
Eg, in the below pic, I would prefer to use 2 checkboxes than use the segment control.  Also easier to change the form if for example I wanted to add another source like Dropbox.  Doing the same with ui switches at least in my mind would be pretty ugly.  
![](https://dl.dropbox.com/s/h6tm5xpphvom57w/File%202-12-17%2C%2020%2041%2005.jpeg?dl=1)

**Comment by cclauss** [comment]
Does iOS ui have a checkbox?  I think not.

**Comment by zrzka** [comment]
iOS doesn't have a checkbox. It has toggle button (switch). It has no sense to introduce custom controls in Pythonista IMO. Closing this one, assuming Ole agrees.

**Comment by Phuket2** [comment]
Ok.  I will wait until ios22.x decides check boxes and radio buttons were a good idea again. But ok. I see your point.  I just search around frantically in my apps looking for a checkbox, could not find one :) Still the lack of them can over complicate forms, at least in Pythonista.
