### ISSUE TITLE
pyObject attribute of ObjCInstance should return a py_object

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#492]
Currently, to get a py_object back from an ObjCInstance, the following is needed

``` 
instance.pyObject(argtypes=[], restype=ctypes.py_object)
``` 

rather than just
``` 
instance.pyObject()
``` 

The latter currently crashes, due to bad encoding.

**Comment by omz** [comment]
I consider the `pyObject` property of some ObjC wrapper classes to be an implementation detail. You're not really supposed to call it from Python code, and it's not actually part of `ObjCInstance`, just some specific Objective-C classes that are used internally in `ui` and some other modules.

**Comment by zrzka** [comment]
According to Ole's response, sounds like won't fix -> closing. If anyone disagrees, feel free to comment / reopen.
