### ISSUE TITLE
Multipeer Connectivity support

### ISSUE THREAD

**Issue by mikaelho** [omz/Pythonista-Issues#501]
[Multipeer Connectivity](https://developer.apple.com/documentation/multipeerconnectivity?language=objc) with a nice Python(ic) API would be an excellent and selling feature on a mobile platform with strong support for games.

Built-in implementation might be fairly straight-forward, even though implementation via objc_util has proven [problematic](https://forum.omz-software.com/topic/3280/how-to-support-multipeer-connectivity).

**Comment by mikaelho** [comment]
Sufficient objc_util implementation available through the discussion thread linked in the issue description. Closing for now.

**Comment by bbkiwi** [comment]
On 3.4 the multipeer example no longer works. Gets MultipeerConnectivity Framework error.
