### ISSUE TITLE
Scrolling in file explorer locks up app

### ISSUE THREAD

**Issue by HyShai** [omz/Pythonista-Issues#503]
When scrolling through the file explorer (local *and* iCloud) it slows down and then freezes Pythonista. 

I have a lot of files in the iCloud folder, however I have just one file and the default Pythonista Examples folder in the Local folder. 

(e.g. Scrolling in the local examples folder freezes the app.)

This is on the latest 3.2 from the App Store. I didn't notice the issue in 3.1 beta.

**Comment by HyShai** [comment]
Testing it more - the app UI is in general very janky. Wonder what changed, perhaps we need a `@ui.in_background` 😜

**Comment by omz** [comment]
What kind of device are you using?

**Comment by HyShai** [comment]
iPhone 7 (iOS 11.2.1)

**Comment by omz** [comment]
Are you doing anything with `pythonista_startup`?

**Comment by HyShai** [comment]
I have a `pythonista_startup` in my iCloud folder - which isn't doing anything fancy at all (been the same for a while). Although I was under the impression that it would only be called if in Local files. 

Here's the file:

```python
from objc_util import ObjCClass, ns
ObjCClass('NSUserDefaults').standardUserDefaults().setBool_forKey_(True, 'EditorShowLineNumbersOnPhone')

def can_open(url_scheme):
	url_scheme = url_scheme.replace('://', '')
	LSApplicationWorkspace = ObjCClass('LSApplicationWorkspace')
	workspace = LSApplicationWorkspace.defaultWorkspace()
	url_schemes = workspace.publicURLSchemes()
	print url_schemes
	return ns(url_scheme) in url_schemes
	
import webbrowser
webbrowser.can_open_app = can_open
```

**Comment by omz** [comment]
No, it would only have an effect if it's in the site-packages or local files folder.

**Comment by HyShai** [comment]
Turns out I had ~456 MB of files in iCloud (deeply nested folders). Perhaps there was something weird happening with one of the items because once I remove all the files from iCloud - the app doesn't lock up anymore.

**Comment by zrzka** [comment]
Looks like duplicate of #405?

**Comment by HyShai** [comment]
Yup this seems like the same issue as #405
