### ISSUE TITLE
Extension returns "Script Not Found" when file is in iCloud.

### ISSUE THREAD

**Issue by ElliotLockerman** [omz/Pythonista-Issues#504]
As it says in the title, I tried adding a script in iCloud to the share extension. Selecting this script returns "Script Not Found"; manually locating the script doesn't help. The same file works fine as an extension when stored locally only.

**Comment by Luckjanov** [comment]
I have the same issue. Once I was able to fix it by deleting spaces in file name but soon error appears again.

**Comment by chevell** [comment]
Same issue. This effectively breaks iCloud support for me since I use share sheet extensions fairly heavily

**Comment by fakewaffle** [comment]
Any updates on this?

**Comment by dchevell** [comment]
Is this project still maintained? This is still the most powerful iPhone app by far, but bugs like this make it very frustrating to use across multiple devices

**Comment by macserv** [comment]
I just started using Pythonista (found via Shortcuts app) and I quickly ran into the same issue.  Anyone find a workaround?

**Comment by benubois** [comment]
You can use iCloud Pythonista scripts with the Shortcuts app by using Pythonista’s URL scheme. For example:

```
pythonista://video-url.py?root=icloud&action=run&argv=script_arg
```

The key is the `root=icloud` param. You can add mutiple `argv` params for multiple arguments.

A full example of a shortcut that takes a URL might look like this:

![img_0001](https://user-images.githubusercontent.com/133809/48447967-61dce080-e752-11e8-9aec-44b2c9015f53.png)

**Comment by adib** [comment]
I'm having the same issue with Pythonista 3.2

**Comment by omz** [comment]
This is fairly old, and has been fixed, I think.
