### ISSUE TITLE
ui.View.border_width – only stroke on the inside

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#51]
I am guessing this might be very tricky unless Objective-C supports it natively.

Every line in `ui`, whether it is a `border_width`, a `ui.Path.stroke`, etc, strokes the border by making it grow both on the outside and the inside, so that the line widens in both directions. This is not great in my `ui.View`.

What if negative numbers only grew the line width on the inside? I tried it on `border_width`, and passing a negative width is same as passing zero.

It really doesn't make sense to me to define a bounding rectangle around a `ui.View`, and then to have the rect exceed its boundaries when you apply a stoke to it.

**Comment by omz** [comment]
Since this is pretty much just a wrapper around a UIKit API, I cannot the behavior easily.

You might want to consider adding a "border view" as a subview, and calculating the inset of its frame manually.

**Comment by Phuket2** [comment]
Lol, I may want to consider drinking more before doing that 😱 But understand, just have to live with it and get with the program. Thanks anyway
