### ISSUE TITLE
Error in scene_drawing.py for Python 3

### ISSUE THREAD

**Issue by flashgui** [omz/Pythonista-Issues#52]
The update method of the Layer class doesn't work correctly in python 3 because has_key() was removed in Python 3.x. for dict objects:

``` python
def update(self, dt):
  if (len(self.animations) > 0):
    for animation_key in self.animations.keys():
      if self.animations.has_key(animation_key):
        ...
```

As a key can be remove in the loop, a possible workaround is to work on a copy of the dictionnary key's and to use `in`:

``` python
def update(self, dt):
  for animation_key in tuple(k for k in self.animations.keys()):
    if animation_key in self.animations:
      ...
```

**Comment by zrzka** [comment]
Just check Py3Kit scene_drawing and it's fixed, closing.
