### ISSUE TITLE
notification module - enhancement/bug

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#524]
When a Pythonista created notification gets fired and you are in Pythonista you are presented with a dialog box rather than the standard notification. It would be nice for it to be standard. Maybe there is a setting I am missing. Also the dialog presented only has an 'Ok' button, so if you have set a URL when creating the notification, you have no choice,  action_url is called.

Also, I have had problems cancelling a single notification. I have tried passing the dict returned from schedule as well as the dict passed back from get_scheduled(). cancel_all() works as expected. 
***It should be noted*** that the get_scheduled() method returns dicts with the action_url being of type  __NSCFString. This appears to be a mistake.  The dict passed back from schedule() appears to use normal python types.  Anyway, I have tried different combinations of these dicts with cancel() and I can not get it to work.  Regardless what the issue is here, would be good if get_schedule() returned dicts with python types and thats what cancel() expected.  Eg, saving the dict (JSON) for possible use later. I know you can str() that property, but does not make a lot of sense. After saying all that, it would be so much better if a uuid.x was passed back in the schedule() dict to be able to pass to cancel rather than the whole dict.

Lastly, it would nice to be able to set a notification_group param passed to schedule(). Ideally, you could pass that to get_schedule(group='HellEvents').  But if not, you could just filter yourself.  But I think the group attr would give the notification a lot more context.  

@omz , i know you said already this module needs updating.  Just wanted to mention the above.  I did do a search here in the issues. I could not find any notification items.

**Comment by omz** [comment]
Just a little bit of explanation, I can't offer a fix right now: The `notification` module still uses the relatively old `UILocalNotification` API that has a bunch of limits, compared to the newer (introduced in iOS 10) `UserNotifications` framework. One of the limitations of `UILocalNotification` is that banners can't be shown while the app is active. I expect this problem to go away when I rewrite the `notification` module using the new framework.

**Comment by Phuket2** [comment]
@omz , ok thanks for the explaination. Anyway, its still pretty good in its current condition.  I guess its more when you start pushing it, these issues start to show up. One could say that, notifications are not meant to be used in this particular way,  but then again SMS was never intended for the public in its inception. I will close this item as you have indicated its on your radar already.
