### ISSUE TITLE
Beta Version & App Store Version Sync on AppStore Version release

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#526]
@omz, I am not sure what the normal protocol for this is. But to me at least it seems like it would make sense to update the beta in TestFlight to the latest App Store version when a new AppStore version release occurs.  I know its been said that you can install each version over the other numerous times and more than likely you will not have a problem.  
Hmmm, ok as I am writing this It occurred to me that maybe some of the code still in the beta didn't make it through to the AppStore version.  If thats the case, then it makes sense.  
I guess its just this grey area about what is the latest version.  I would prefer not to have to reinstall over the beta with the store version if I dont have to.  
Maybe the latest beta's codebase is identical to the AppStores Version.  Again, its just about knowing, when reporting issues etc...

**Comment by omz** [comment]
Right now, there isn’t really a beta, and I’d recommend that everyone just installs the latest version from the App Store, as it contains some last-minute changes that weren’t in the beta.

**Comment by Phuket2** [comment]
Ok, thanks.  I will do that. I was just not sure how it worked.
