### ISSUE TITLE
"Pythonista Tasks" app idea

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#54]
I had an idea for another Pythonista app. It would:

- allow a "Today View" widget
- possibly allow background app refresh?
- It would be a stripped down with more optimized and lighter modules.
- `ctypes` and `objc_util` would be included, since that's exposes a lot of important functionality.
- Background app refresh – this would allow a script to run periodically for short amounts of time.
    - If the allowed time is about to run out, an exception would be raised or
    - if memory is running low an exception is raised.

**Comment by controversial** [comment]
Not sure that this is the place for new app ideas. This is about Pythonista bug reports and feature requests. You should probably put this on the forums.
