### ISSUE TITLE
Website update needed: says Python 3.5, not 3.6

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#544]
http://omz-software.com/pythonista/ Says that Pythonista supports Python 3.5 but it supports 3.6.

**Comment by cyberw** [comment]
Why was this closed? It still says 3.5...

**Comment by cclauss** [comment]
I close issues that have been open for a year because I sense that no one is listening.  The real question is why is it Python 3.6 when current Python is 3.8.2?

**Comment by cyberw** [comment]
Ok! I guess whoever maintains the website is not listening then? Seems a small thing to fix :) (the app store page clearly states 3.6)
