### ISSUE TITLE
Ui.TableView - cell divider 

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#55]
A attr to turn off the drawing of the dividing line between cells in the ui.Table. This would be very nice, when doing your own data_source, can make cells that look more more attractive.

**Comment by danrcook** [comment]
@Phuket2 did you try `TableView.separator_color` ? I wonder if you just set it to the same background color of the tableview then you'll have your effect. 

I agree having it built in as a bool would be better.

**Comment by Phuket2** [comment]
@cook, how did you know about tv.separator_color, is not in the docs.  But it does work. Thanks. No need to worry about the background color can just set to tv.separator_color = (255, 0, 0, 0). No alpha, it does not draw. But interested how you knew about that attr

**Comment by Phuket2** [comment]
I will close this after I find out how you knew about the attr. I can't see it in the docs. Then will make another issue about documentation, if it's needed

**Comment by danrcook** [comment]
@Phuket2 no it's not in the docs at all. I found it in `print(help(ui.TableView()))`

**Comment by Phuket2** [comment]
@cook, thanks. In the past the doc strings have not been filled in, well at least for some items, the ones I have checked. But thanks again. It is nice to know about it. Can make lists look ugly sometimes
