### ISSUE TITLE
Need additional keys for navigation

### ISSUE THREAD

**Issue by hemantsathe** [omz/Pythonista-Issues#562]
When using quotes or brackets with automatic character pairing, it is difficult to get out of the quote or bracket without navigation keys. I have always struggled with using touch to do exactly what I want, specially taking the cursor to a position within text. Having navigation keys on the built in touch keyboard will greatly improve usability.

**Comment by dgelessus** [comment]
There are actually multiple features that might help you here:

1. If you use automatic character pairing, Pythonista lets you type "over" the automatically inserted end character. So for example if you type `"hello` and Pythonista inserts a second `"` at the end, you can simply type `"` again to get out of the string (doing so doesn't insert an extra quote). The same works with parentheses, etc.
2. You can slide your finger left and right on Pythonista's extended keyboard to move the cursor left and right in the current line. You can't move the cursor up and down that way, so you need to tap on the correct line first, but that's usually much easier than hitting the exact character position.
3. On iPad, you can drag with two fingers on the touch keyboard to move the cursor freely around a text field, kind of like a laptop trackpad. This is a standard iOS feature, so you can use it in any app, not just Pythonista. It's not supported on iPhone though.

**Comment by iamrecursion** [comment]
Also, on force touch enabled devices you can force-touch the keyboard to enter cursor mode. Moving your finger will move the caret placement and pressing again (without lifting your finger) allows you to select text. It's an absolute godsend for precise editing.

**Comment by hemantsathe** [comment]
Thanks for the replies. I was unaware of these ways of navigation.
