### ISSUE TITLE
Stopped launching pythonista3 app

### ISSUE THREAD

**Issue by takahio** [omz/Pythonista-Issues#567]
Help me.
3days ago, suddenly, pythonista3 stopped running.When I tapped pythonista-Icoin,the app displayed title screen.But, blacked out soon.
What should I do?
information
・iPhone 6s
・iOS 11.4

**Comment by cclauss** [comment]
Type in your browser URL bar... __pythonista://__ and hit return.

**Comment by takahio** [comment]
Thank you for you're a comment.
The pyhonista now starts normally.
When A certain source file is opened, The app  blacks out.
