### ISSUE TITLE
Reformat settings do not save

### ISSUE THREAD

**Issue by ryanpcmcquen** [omz/Pythonista-Issues#569]
I reformat using PEP8 styling, which should use 4 spaces by default. Every time I click reformat I have to switch from tabs to spaces, and then increment 2 spaces to 4 spaces. It would be great if the app ‘remembered’ this setting. Excellent work otherwise!

**Comment by dgelessus** [comment]
As far as I can tell, the reformat settings default to whatever your current indentation settings are. If I go into the Pythonista settings and change my indents to 4 spaces, the reformat dialog also uses those settings by default.

**Comment by ryanpcmcquen** [comment]
@dgelessus, right you are! Thank you.
