### ISSUE TITLE
Ui.TableView.separator_color Documentation update

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#57]
The separator_color attr does not appear in the written documentation. Or course it appears in -print(dir(ui.TableView()))
print(help(ui.TableView()))

But useless unless you know you should go looking for it. I originally asked for a attr to turn it off or on. But with the separator_color attr you can set the color to a RGBA value like (0, 0, 0 ,0). It does not draw. It would still seem that a Bool value would be more consistent

**Comment by omz** [comment]
It looks like this isn't just undocumented, but also doesn't work correctly. Getting the `separator_color` actually returns the `background_color` instead (setting it works fine though). Both should be fixed in the next beta.

**Comment by zrzka** [comment]
`separator_color` is included in the documentation and returns correct value in 311014.
