### ISSUE TITLE
Missing search symbol on iPhone XsMax

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#578]
In Pythonista 3.3 the search symbol is missing in landscape and portrait mode on XsMax
In Pythonista 3.2 the symbol was available in lanscape in iPhone XsMax

**Comment by wnMark** [comment]
In Pythonista 3.3 the search symbol is missing in landscape and portrait mode.
In Pythonista 3.2 the symbol was available in lanscape in iPhone XsMax

**Comment by wnMark** [comment]
I have found the search symbol on the rename menu of filename.

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by wnMark** [comment]
Yes it looks like a better solution now, on previous version the search symbol was missing, if a file had a long file name, now the symbol is always available.
