### ISSUE TITLE
ui.TableViewCell() blank param option , no views added to the content_view

### ISSUE THREAD

**Issue by Phuket2** [omz/Pythonista-Issues#58]
I am pretty sure this is not possible currently. To create a ui.TableViewCell() with a blank content_view. Meaning that it's totally up to the programmer to define the cells contents + flex attrs etc. Even better if you could register that custom made cell under a new name, to make sure that can take advantage of the tricks you are doing behind the scenes to serve up cells very fast. 
So maybe create a ui.TableViewCell('blank'), then save the resulting ui.TableViewCell  as  ui.TableView.MyCustomCell().save('my_custom_cell'), then there after, can call ui.TableViewCell('my_custom_cell). 
Or something like that. But I am sure you get my meaning

**Comment by omz** [comment]
The underlying `UITableViewCell` APIs don't really allow to create a cell that doesn't at least contain one text label, but you're not required to use it at all – you can simply add your own views to the cell's `content_view`.

**Comment by Phuket2** [comment]
Thanks for the answer. In hindsight it does not seem to be a problem. I understand don't need to use the label. I was thinking more about speed and memory. But because of the optimisations under the hood, it does not seem to matter at all
