### ISSUE TITLE
Home Screen Icon does not work on 330003

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#581]
I was hoping to be able to create a „Home Screen Icon“ quicker as before, but now an additional step was introduced with shortcuts and the action „Home Screen“ is missing, despite there is plenty space for this button. It is possible to create an icon, but if calling this, I get an error „Not Found, The file „(null).py“ cound not be found“. And it goes event worse, I can not terminate this hint with the  OK button. For me a reason to go back to APP Store version of Pythonista, at least on my iPhone

**Comment by wnMark** [comment]
Thank you Ole,

It doesn‘t work on iPad and doesn‘t work on iPhone
System Information

Pythonista 3.3 (330003), Default interpreter 3.6.1
iOS 11.4.1, model iPad7,2, resolution (portrait) 2048.0 x 2732.0 @ 2.0

* Pythonista 3.3 (330003), Default interpreter 3.6.1
* iOS 12.1.2, model iPhone11,6, resolution (portrait) 1242.0 x 2688.0 @ 3.312

**Comment by omz** [comment]
Okay, thanks!

**Comment by wnMark** [comment]
Thank you Ole, in version 330004 it works again (but only with the extra click)
