### ISSUE TITLE
Editor context menu is now in german on version 300033

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#582]
Editor context menu is now in german on verison 300033, that is not a problem, because my system is in german. But now the „Highlight All“ is no longer directly available. And this function I am useing very often. A solution, which bring this back for accessing directly would be great

**Comment by omz** [comment]
This is unfortunate, thanks for pointing it out. I think I know why this happens, but I'm not sure about a fix yet.

**Comment by omz** [comment]
The problem is basically that I have to localize certain parts of the app to make spoken output work for Siri shortcuts, even though the app as a whole is not localized. This is probably why the built-in menus assume that the app is localized in German, even though that's mostly not true.

**Comment by wnMark** [comment]
Maybe at least for „Highlight all“ a solution could be, after a selection of a word, all same words should be highlighted. I think Visual Studio do this.

**Comment by wnMark** [comment]
Thank you Ole, in version 330004 the context menu ist english and ‚Highlight all‘ directly accessable
