### ISSUE TITLE
Updating/restoring examples also creates a __MACOSX folder

### ISSUE THREAD

**Issue by dgelessus** [omz/Pythonista-Issues#583]
When the Pythonista examples are updated/restored, a `__MACOSX` folder is also created at the top level. I'm guessing the examples are extracted from a zip file, and the Mac metadata was accidentally included when creating the zip file. (You probably know this already, but the `__MACOSX` metadata is only added by the Finder and Archive Utility; if you create the archive with the command-line `zip` tool no extra files are included.)

This happens with builds 330003 and 330004 (tested on iOS 12, not that it should make a difference).

**Comment by omz** [comment]
Ugh, that's embarrassing. I knew all that, and I used to create the zip differently...

**Comment by omz** [comment]
Okay, this is weird. Your explanation absolutely makes sense, but I can't actually reproduce the issue. Restoring the examples on my iPhone X (iOS 12) does not create a __MACOSX folder. 🤔

I'll look into this.

**Comment by omz** [comment]
Oops, thanks! I experimented with some games in the keyboard earlier on, and apparently forgot to clean up after myself... I develop the sample code directly on the iPad.
