### ISSUE TITLE
The new keyboard is cool (version 330004)

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#584]
The new keyboard is cool (version 330004)

Some ideas
1. Include these libraries also to REPL like done in Calculate to be consitent
from math import *
from random import *
2. Include a calculator with a UI, like the color mixer
3. I am always dreaming about a keyboard with numbers and comma, point and  alphanumeric on one keyboard accessable without switching. Maybe with ‚Special Characters‘
4. Creating morse signs similar to QRC could be funny

**Comment by wnMark** [comment]
5. Decode a QRC image from clipboard to text

**Comment by cclauss** [comment]
1. is frowned upon in PEP8

**Comment by omz** [comment]
Some fun ideas here, but Pythonista is an app to *write* code, so I don't want to do *everything* in the example scripts.

**Comment by wnMark** [comment]
Cool new feature
