### ISSUE TITLE
RequestsDependencyWarning

### ISSUE THREAD

**Issue by ohjartat** [omz/Pythonista-Issues#586]
Hi! This is my first issue report so please bare with me and let me knof if I need to provide more information or post this issue somewhere else.

So, Ive been playing around a bit with the ”requests” package for http requests, the past few days. Then yeterday all of a sudden my code wouldnt run because ”No module named chardet” when trying to import requests. Weird, I thought but resolved the issue by pip install chardet (using stash console).

Then today Im getting a ”No module named idna” and a traceback message (abbreviated):
RequestsDependencyWarning: urllib3 (1.14) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

So, I wanted to try and uninstall chardet and requests and reinstall them, but stash wont let me do anything. Not even pip install simplegist (which is a completely unrelsted package)

Is this a pythonista issue? Or stash? Or pip? Or me installing the wrong version of chardet? And how can I resolve it? 

Thankful for any pointers in the right direction. Thanks!

**Comment by cclauss** [comment]
I would completely reboot the Pythonista app (throw it out of memory) and try again.

**Comment by cclauss** [comment]
https://support.apple.com/en-ca/HT201330

**Comment by ohjartat** [comment]
Oh I see. That doesnt help unfortunately.

Can I unistall chardet and requests somehow? Not using stash, as it seems clogged somehow with is dependency issue.

**Comment by omz** [comment]
@ohjartat You can delete packages you've installed manually from the `site-packages`, `site-packages2`, and `site-packages3` folders. Just go to "Python Modules" in Pythonista. Make sure to completely restart the app afterwards.

**Comment by ohjartat** [comment]
Thanks! That worked.
