### ISSUE TITLE
You can not enter a blank in any field (search, replace, outline filter, help)  except editor (330007)

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#587]
Thank you Ole for the new beta and the new features for hardware keyboards.
I was not able to test all until now, but I figured out the following issue.

You can not enter a blank/space in search, because this is used now for a page down.

**Comment by wnMark** [comment]
As a workaround you can use the software keyboard to enter the space key

**Comment by cclauss** [comment]
I want to search for legacy print statements so I want to look for instances of __print<space>__ but ignore all instances of __print(__

**Comment by wnMark** [comment]
For me the space key is more important as the scrolling. Maybe take the ⌥ Space for scrolling?

**Comment by omz** [comment]
Ah sorry, I think I completely misunderstood the problem because I was thinking about the *new* feature (outline filter), and not the one that has existed for a while (editor search). I'll look into this.

**Comment by wnMark** [comment]
Ole, the missing space in the „old“ search field is now in 330007

**Comment by wnMark** [comment]
Fixed in version 330012
