### ISSUE TITLE
Filter search  with no hardware keyboard (330007)

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#588]
This is a cool new feature. Thank you Ole.

If using no hardware keyboard it is necessary to scroll to the start of the list to enter a filter value. Maybe there could be a direct way? Maybe show the filter always, if the list is open.

**Comment by wnMark** [comment]
Today it looks,like requested and the search filter is visible.
I will observe this and close the issue, if this doesn‘t occure again

**Comment by wnMark** [comment]
Thank you Ole for clarification.
I was in the search field and then the outline is not shown, if you click on file name. For me this is fine.
I will close the issue

**Comment by omz** [comment]
Ah okay, that makes sense. I think it *should* show the filter if you're already typing in the search field, but that case is currently not handled. I've put it on my todo list.

**Comment by wnMark** [comment]
Fixed at least since beta 330025
