### ISSUE TITLE
Shortcut Home Screen Icon does not work on iPhone XsMax with iOS 12.2

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#596]
Shortcut Home Screen Icon does not work on iPhone XsMax with iOS 12.2.
Creating the icon is possible, but if starting the python program brings only the window with the blue background (But in rare times ist works).

I also tested this with the Pythonista 3 App Store version. Same problem!

**Comment by wnMark** [comment]
**System Information**

* Pythonista 3.3 (330007), Default interpreter 3.6.1
* iOS 12.2, model iPhone11,6, resolution (portrait) 1242.0 x 2688.0 @ 3.312

**Comment by omz** [comment]
@wnMark Do home screen shortcuts work in the Shortcuts app for you?

**Comment by wnMark** [comment]
Same problem with Shortcuts app. This was a problem with iOS 12.2 beta 1.
With iOS 12.2 beta 2 the problem is fixed now.

**Comment by omz** [comment]
So this can be closed?

**Comment by wnMark** [comment]
Sorry to early. Under some circumstance still a problem also in iOS 12.2 beta2

**Comment by omz** [comment]
Okay, but if it’s the same with Apple’s own Shortcuts app *and* it’s an iOS beta, it seems more like an iOS bug?

**Comment by wnMark** [comment]
Yes, it all starts with iOS 12.2.
After reboot iPhone, it works one time.

**Comment by wnMark** [comment]
It works again with 12.2 beta3
