### ISSUE TITLE
Canvas not working in Python 3

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#60]
https://forum.omz-software.com/topic/3284/what-s-with-canvas-in-pythonista-3 contains the issue and the workaround

**Comment by omz** [comment]
This should be fixed in the latest 3.0.1 beta.

**Comment by steve-bate** [comment]
I'm seeing the issue about the canvas operations not being displayed with Python 2.7 in Pythonista 3.0. The canvas does work with Python 3.5 (other than the "unicode" issue). Will 3.0.1 also fix the Python 2.7 problem?

**Comment by zrzka** [comment]
Tested in 311015, with Python 2 / Python 3, example from the forum, also added some `draw_text` calls with unicode characters, ... Works fine, closing.
