### ISSUE TITLE
App is chrashing on huge files (330010)

### ISSUE THREAD

**Issue by wnMark** [omz/Pythonista-Issues#602]
App is crashing while try to load a huge files (> 300.000 lines and > 40 MB).
The bad part of this is, you are no longer able to start or use Pythonista.
Maybe Pythonista is crashing by running out of memory?

**Comment by cclauss** [comment]
In Safari type __https://pythonista3__

**Comment by wnMark** [comment]
I try to explain in detail. I have a huge log file and was not able to open this in Pythonista, because Pythonista was crashing while open this file.
After a while I was get rid of this big file and open Pythonista again (I don‘t know how)
- I tried with open a different beta version, to get the welcome file (failed)
- I tried to close the big file pressing the X (failed)
- i tried pressing Alt-W to close the tab (failed)

I solved this problem for me now, by limeting one log file to 100.000 lines

**Comment by wnMark** [comment]
> In Safari type **pythonista3://**
Thank you cclaus, I just tried this with my huge file and  get a blank useable Pythonista after following your hint

**Comment by wnMark** [comment]
Beta 330025 brings a huge improvement.
Select “Diasable automatic switch” in Theme Settings
