### ISSUE TITLE
Cannot see line being typed in console/interpreter mode (iPad)

### ISSUE THREAD

**Issue by maxvonhippel** [omz/Pythonista-Issues#608]
When typing in the console / interpreter mode on my iPad Pro (2018, smaller one), I cannot see the line currently being typed because of the little helper thing that pops up with extra keys.  If I click for it to go down it does go down but when I type more it pops back up so I still can’t see what I’m doing while I’m typing.

![IMG_0036](https://user-images.githubusercontent.com/4683443/58997215-91743880-87c9-11e9-95e1-8ade64613e0f.jpeg)

I really like this app!  I’m happy to try and fix the bug, but lacking a Mac computer I can’t really test any potential fix I write, so it might be easier for someone else to take this on.  (I am an experienced iOS dev though so if nobody has time to do this, let me know and I’ll give it my best shot, and hopefully someone else can test it.). Thanks!

**Comment by huylenq** [comment]
I’m having the same problem. Using Smart Keyboard Folio (or any other external keyboard I suppose), the additional on-screen keys cover the bottom line of the prompt. The problem only appear on horizontal orientation, the prompt is visible entirely on vertical orientation.

iPad Pro 2018 (11-inch)
iOS 12.3.1
Pythonista 3.2

**Comment by gaspo53** [comment]
Same thing here. The only solution is to turn off the Shortcuts keyboards setting in iOS (system wide). 

![image](https://user-images.githubusercontent.com/2250227/60597485-6574b480-9d81-11e9-9d45-3fd4385bca57.png)

**Comment by huylenq** [comment]
@gaspo53 Oh I didn’t know that could be turned off. That at least makes the prompt usable for me, thanks!

**Comment by maxvonhippel** [comment]
Ok, I think that this sounds like something that is a bug at the level of iOS not at the level of the app, so I'm gonna close this out.
