### ISSUE TITLE
Keyboard module 

### ISSUE THREAD

**Issue by machinehistories** [omz/Pythonista-Issues#609]
When I run samples that use the keyboard module I get the following error:
import keyboard
ModuleNotFoundError: No module named 'keyboard'
When I try to add the pythonista keyboard in settings it isn't listed.

**Comment by tommytwoeyes** [comment]
I have the same problem:

I followed the instructions to install the Pythonista keyboard, but when I access Settings -> General -> Keyboard -> Add new keyboard, there is no listing for any Pythonista keyboard. 

I am running iOS 11.3.1. Does this feature require a minimum iOS version?

**Comment by omz** [comment]
Yes, the keyboard requires at least iOS 12, so this is basically the expected behavior, though I guess I could make this clearer.
