### ISSUE TITLE
Beta 330014 under ios13: Home screen shortcuts starts a script twice

### ISSUE THREAD

**Issue by cvpe** [omz/Pythonista-Issues#614]
When I use http://www.editorial-workflows.com/workflow/5872060161064960/e831ijSVsok script to create an home screen icon shortcut, it worked until iOS 13, and now it starts the script twice...
Very easy  to test with a little script appending a text to a file.

When I start the same script in Safari with Pythonista3://test.py?action=run, it is ok
When I start with a shortcut from the Apple app Shortcuts, I is ok

**Comment by skrohmer** [comment]
Same here, iPadOS 13.1.1, Pythonista 320000

**Comment by JacoBezuidenhout** [comment]
I am having the same issue on iPhone 11 Pro Max v13.2 Pythonista 320000
