### ISSUE TITLE
Crash in beta 330018 using statusbar

### ISSUE THREAD

**Issue by cvpe** [omz/Pythonista-Issues#619]
My pythonista_startup.py contains lines
	app = UIApplication.sharedApplication()
	bar = app.statusBar()
and crashes in beta 330018 with error, see below.
I commented process and it is ok, but with beta 330014 under ios13, I didn't have this problem

App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.

**Comment by omz** [comment]
I don't think there's much I can do to fix this, as it's probably caused by building with the iOS 13 SDK.

**Comment by cvpe** [comment]
Understood, and ok
