### ISSUE TITLE
Tabs order does not always save

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#62]
I am not sure if this is a "feature" to prevent issues with a rogue file.
 ... but many operations do not result in storage of the tab order..   If running a script, and the script crashes the app, it appears that 90% of the time the tab order or open tab list is not saved.

i would suggest that pressing Play in the editor should first save the tab order, THEN run the script.  That way, if I just spent time closing 20 tabs, then open a script and press play, if it crashes I can resume editing after opening the app, rather than reclosing everything again

**Comment by omz** [comment]
In the latest 3.0.1 beta, I'm always saving the open tabs before running a script. While it's still possible to lose the tab order with a crash, this should make it a lot less likely.

**Comment by jsbain** [comment]
Are you also saving the active editor tab?  While the tab list does seem to be saved, I always find myself opening up to the first tab, not the last one i was editing.

**Comment by dgelessus** [comment]
@jsbain That has always been the case, when you restart the app it always switches back to the first tab. That has nothing to do with the app crashing.

**Comment by jsbain** [comment]
right on.  i'll open an enhancement request.  I crash **alot**

**Comment by zrzka** [comment]
Tabs are saved/restored. Also selected tab is saved/restored as well in 311014.
