### ISSUE TITLE
330018: crash

### ISSUE THREAD

**Issue by cvpe** [omz/Pythonista-Issues#621]
330018: crash with this message, never seen before:

Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.

Sorry but I can't say more, how and when it occurs

**Comment by iamrecursion** [comment]
I’ve seen this too with trying to run StaSh, but I can’t reproduce it.

**Comment by cvpe** [comment]
If I run this script, then close, then rerun, Pythonista creases with this error
# UIReferenceLibraryViewController
# 	display definition of a word from system dictionaries
#		nb: system display is allowed but not to get the result...
from objc_util import *
import ui

uiview = ui.View()
uiview.frame = (0,0,300,300)
uiview.present('sheet')

objc_uiview = ObjCInstance(uiview)
SUIViewController = ObjCClass('SUIViewController')
vc = SUIViewController.viewControllerForView_(objc_uiview)	

UIReferenceLibraryViewController = ObjCClass('UIReferenceLibraryViewController').alloc().initWithTerm_('bonjour')
UIReferenceLibraryViewController.setModalPresentationStyle_(3) 

vc.presentViewController_animated_completion_(UIReferenceLibraryViewController, True, None)#handler_block)
