### ISSUE TITLE
Sharing with WorkingCopy: really?

### ISSUE THREAD

**Issue by jmmelko** [omz/Pythonista-Issues#632]
In #98, @zrzka said that "We have Working Copy, ... an easy way how to share repos / code”.

I am sorry but this is not easy for me.

I use Pythonista every day and it works fine for editing and running code.
Since Pythonista does not propose uploading to GitHub, what I did since recently was copy-paste each file... which is quite slow because it uses a lot of memory, and "select all" is not it easy to trigger on a tiny phone screen.

I recently installed WorkingCopy, which clones a GitHub repository and allows to edit the code locally, and then fetch/pull/merge changes from/to the GitHub repo.
But... sharing this local WorkingCopy repo with Pythonista is not easy:

1/ WorkingCopy will not store its local repo in iCloud (I have written to the developer to learn more about this)
2/ Pythonista can import ("external files->Open...") one file from WorkingCopy (which is displayed as a "Location" in iOS files system), but not a whole folder in one step, nor a zip file.
3/ Pythonista cannot find modules to be imported within WorkinCopy files location (I mean, if I import main.py in Pythonista, and my code has an "import mymodule" statement, which is a mymodule.py file in the same directory in WorkingCopy local repo, Pythonista will issue an error).
4/ the “This iPhone” location in Pythonista only refers to Pythonista files, not all local files in iOS
5/ WorkingCopy has a “share” button but Pythonista is not proposed anywhere
6/ I can export the WorkingRepo in files as a zip file, but then I will have to uncompress it, open it within Pythonista, make changes, and export the changes files one way or the other to WorkingCopy again

Has someone a working solution?

If yes, then it should be better documented/advertised because it is not straightforward.

Thank you.

**Comment by jmmelko** [comment]
I just had this answer from the developer of WorkingCopy:

Hi Jean-Michel

A change in iOS 13 is that apps can ask the user to pick a file or to pick a folder but there is no way to ask for both. 

Pythonista does ask for both and in iOS 12 this would allow the user to pick single files or whole directories. Now the user can only pick files. 

Pythonista needs to change how it uses the document picker. In all other ways it supports opening directories in-place.

I have written Apple asking them to make the document picker support opening files or directories as it did on iOS 12 but this is months ago. I don’t think they consider this a problem. 

If you write Ole Moritz that makes Pythonista you can tell him that Anders would love to answer any questions about this. 

It pains me that such a small technical detail is preventing the best way for Pythonista and Working Copy to work together. 

Best regards,
Anders

**Comment by mikaelho** [comment]
This is a know issue and fixing it has been stated as a priority by omz.

Meanwhile, Working Copy allows for syncing a repo with an iCloud directory. I use it daily, and while there is an extra syncing step in the background, the workflow is not much different than with opening directories directly.

**Comment by cclauss** [comment]
It would be really helpful if you could post a video of your workflow between Pythonista and Working Copy.  I used to be able to use these tools well together but lately I have lost the thread.

**Comment by mikaelho** [comment]
Might not get to recording video soon, but this [forum thread](https://forum.omz-software.com/topic/5886/basic-workflows-for-git-repos-on-ios/3) describes the steps.

**Comment by jmmelko** [comment]
Indeed, the developer of WorkingCopy told me that the latest Pythonista beta already supports opening folders with the document picker. So the Next App Store update should include a fix.

**Comment by jmmelko** [comment]
I think it can be closed I have been used both apps together for several months Now.
