### ISSUE TITLE
Project live?

### ISSUE THREAD

**Issue by ppskmg** [omz/Pythonista-Issues#636]
iPad Pro 2018 12.9

Экранная клавиатура:

1. Экранная клавиатура закрывает часть консоли
2. С экранной клавиатурой не видно подсказок
3. С экранной клавиатурой нет возможности сделать множественный комментарий

Внешняя клавиатура:
1. Панель быстрого доступа закрывает ввод консоли

**Comment by cclauss** [comment]
Screen keyboard:
- On-screen keyboard covers part of the console
- No prompts visible on screen keyboard
- There is no way to make a multiple comment with the on-screen keyboard

External keyboard:
- Quick access toolbar closes console input
