### ISSUE TITLE
ui.View.present not presenting in full screen

### ISSUE THREAD

**Issue by IAmTomahawkx** [omz/Pythonista-Issues#638]
After updating, pythonista refuses to present my views in full screen.
`screen.present(style="full_screen", hide_title_bar=True)`
Is still showing as a sheet, instead of full screen.

iPadOS 13.3.1
IPad Air 2

**Comment by cclauss** [comment]
Did you try removing the underscore?  `fullscreen`
The [docs](http://omz-software.com/pythonista/docs/ios/ui.html) mention both in different places.

**Comment by IAmTomahawkx** [comment]
Oh... Yeah that worked. Unclear on why there was a breaking change on default behaviour though

**Comment by cclauss** [comment]
It is always tricky to make automated tests on user interface without crazy tools like [selenium](https://www.selenium.dev).
