### ISSUE TITLE
console.set_idle_timer_disabled broken in v 3.3 (330025)

### ISSUE THREAD

**Issue by drgrib** [omz/Pythonista-Issues#639]
This program immediately crashes the app now:

``` python
import console
console.set_idle_timer_disabled(True)
```

**Comment by dgelessus** [comment]
omz has posted a workaround for this on the forums, by the way: https://forum.omz-software.com/topic/5295/new-beta-for-pythonista-3-3/95

> Sorry about the issue with `console.set_idle_timer_disabled`. Please use this workaround for now:
> 
> ```python
> import console
> 
> def fix_set_idle_timer_disabled(flag=True):
>     from objc_util import on_main_thread
>     on_main_thread(console.set_idle_timer_disabled)(flag)
