### ISSUE TITLE
Screen orientation not enforced by run()

### ISSUE THREAD

**Issue by keithrdavis** [omz/Pythonista-Issues#650]
Setting the following in the run method does not result in a locked orientation (example pulled from one of the games included with Pythonista):
```
run(Game(), PORTRAIT, show_fps=False)
```
Pythonista 3.3 executing with python 3.6 on iPad OS 13.4.1

**Comment by treyharris** [comment]
As of iOS/iPadOS 12, apps that support multitasking (SlideOver, etc.) are not allowed to lock the screen orientation. Since Pythonista is the app as far as the OS concerned, it can’t lock the screen without disallowing any usability in the multitasking modes.

**Comment by keithrdavis** [comment]
That is true, is there a way to not have the app support multitasking so the orientation can be locked?
