### ISSUE TITLE
Calling console.set_idle_timer_disabled(True) Crashes 

### ISSUE THREAD

**Issue by jakronz** [omz/Pythonista-Issues#651]
The title really says it all.   Calling this method causes Pythonista to crash in version 3.3.  iPhone 10 running 13.4.1.

It did not crash in previous Pythonista versions.

**Comment by cclauss** [comment]
Dup of #639

**Comment by jakronz** [comment]
My apologies I searched for idle_timer, strange.

**Comment by cclauss** [comment]
Please close this issue.
