### ISSUE TITLE
When editing a .html file, a "view in browser" button would be helpful

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#66]
I understand that HTML editing is not a key selling point for Pythonista but... When I am editing an HTML file in the Pythonista editor, it would be quite useful to have a "view in browser" or "render in browser" button that would open that file in the internal browser or in Safari, etc.

This need not be a builtin capability.  It would be also acceptable if this could be achieved via a script in the action menu.  I have not figured out how to do so.

**Comment by jsbain** [comment]
I would have thought you had this one in ten lines or less:
``` 
import editor,webbrowser
filename=editor.get_path()
webbrowser.open('file://'+filename)
``` 
(run from action menu)

**Comment by cclauss** [comment]
;-) thx
