### ISSUE TITLE
Unknown Action Presented for Pythonista Edit Script / Run Script Actions In Shortcuts on iOS 15

### ISSUE THREAD

**Issue by musicandysmith** [omz/Pythonista-Issues#674]
After upgrading to iOS 15.0, shortcuts which use the Edit Script &/or Run Script actions in Shortcuts will now no longer run. 

The following, Unknown Action block is shown within the shortcut.
![image](https://user-images.githubusercontent.com/50911855/135338971-c7144bcd-6e99-431b-bf7a-6af9128b05c3.png)

Adding new Edit Script &/or Run Script action blocks to the shortcut will result in the Shortcuts app crashing.

Shortcut will not run - a prompt to the user to select an app is present opposed to running the previously configured script within Pythonista.
![image](https://user-images.githubusercontent.com/50911855/135338342-5d7aec45-56d4-47b6-987a-66906abc6dce.png)

Shortcuts app also presents a pop up stating This action requires an app that may not be installed.
![image](https://user-images.githubusercontent.com/50911855/135339006-9b3856d3-70fe-4578-87b1-0713bbfee9d9.png)

**System Information**

* Pythonista 3.3 (330025), Default interpreter 3.6.1
* iOS 15.0, model iPhone12,8, resolution (portrait) 750.0 x 1334.0 @ 2.0

**Comment by omz** [comment]
I can't reproduce this, these actions are still available for me in the current version of Shortcuts (with iOS 16), although Apple has notified me a while ago that they'll be removed at some point.
