### ISSUE TITLE
'Home Screen Icon' not working

### ISSUE THREAD

**Issue by boegh** [omz/Pythonista-Issues#683]
This may be the same issue as #669 but I'm not sure... 

I can't make a `Home Screen Icon` shortcut using `wrench icon` -> `Shortcuts...` -> `Home Screen Icon`. I believe this is the procedure as [described in the documentation](https://omz-software.com/pythonista/docs/ios/pythonista_shortcuts.html#pythonista-homescreen-icon). I have tried with multiple scripts - both from Examples and my own.

After having configured the shortcut (Title, Run/Open and Icon) I press Continue and Safari opens `localhost` at port 50-thousand-and-something, but it shows a blank screen. Adding that to Home Screen does not give me the shortcut...

I'm am not sure if this is a recently introduced issue, as I have never tried making a Home Screen Icon from Pythonista before...

Pythonista version: 3.3 (330025)
iOS/iPadOS version: 15.5

Same behaviour observed on both iPhone (Xr) and iPad (6th gen) running same versions of Pythonista and iOS/iPadOS.

**Comment by omz** [comment]
This feature will be removed in version 3.4. It was always kind of a hack, and now that the Shortcuts app allows creating Home Screen shortcuts in a better way, it's also redundant.
