### ISSUE TITLE
ui.set_color seems to corrupt Pythonista

### ISSUE THREAD

**Issue by TheSwiftster** [omz/Pythonista-Issues#685]
The code below is very simple and draws a red circle a Line and a red circle in the Console. The code seems to work fine until Line 16 is active.

In this case the red circle is shown, the Line is shown (but black not red). But the second circle fails with a TypeError "'str' object not callable" on Line 5. Furthermore, I now have to completely close and re-open Pythonista, as clearing the error commenting out line 16 and re-running the code now returns the same TypeError on the first Circle!

```
import ui 

def circle():
    with ui.ImageContext(375, 701) as ctx:
        ui.set_color('clear') #  Line 5
        ui.fill_rect(0, 0, 100, 100)
        ui.set_color('red')
        circle = ui.Path.oval(10, 10, 80, 80)
        circle.fill()
        img = ctx.get_image()
    return img
    
def line():
    img = None
    with ui.ImageContext(375, 701) as ctx: 
#         ui.set_color = ('red') #  Line 16
        p = ui.Path()
        p.line_width = 3
        p.move_to(10, 10)
        p.line_to(100, 100)
        p.stroke()
        p.close()
        img = ctx.get_image()
    return img
    
circle().show()
line().show()
circle().show()
```

--- SYSTEM INFORMATION ---
**System Information**

* Pythonista 3.3 (330025), Default interpreter 3.6.1
* iOS 16.1.1, model iPad8,5, resolution (portrait) 2048.0 x 2732.0 @ 2.0
--- SYSTEM INFORMATION ---

![IMG_0138](https://user-images.githubusercontent.com/20913556/204035459-995ec2ce-3ecc-493b-b71b-30bbeaf60e1a.PNG)

**Comment by cclauss** [comment]
https://omz-software.com/pythonista/docs/ios/ui.html#ui.set_color

**Comment by cclauss** [comment]
I believe that `clear` is an invalid color.

**Comment by TheSwiftster** [comment]
If 'clear' which works, is changed to 'white' or 'blue' it still fails.

**Comment by mikaelho** [comment]
It should be `ui.set_color(”red”)`, not `ui.set_color = (”red”)`.

**Comment by TheSwiftster** [comment]
Oh god, what an idiot I am.

**Comment by mikaelho** [comment]
For one character, an empire was lost.

Do not be too harsh on yourself, we are all best at spotting others’ mistakes. 😁
