### ISSUE TITLE
See Hidden Files

### ISSUE THREAD

**Issue by OKizikO** [omz/Pythonista-Issues#728]
I like to request being able to see files with a dot prefix, or hidden files in the file browser. 

I use a lot of .env and .gitignore files and at the moment I can't edit them within the app.

**Comment by MufasaRuler** [comment]
Same problem here

**Comment by TFWol** [comment]
Yep, pain in the butt. There absolutely should be a settings toggle for this.

**Comment by TFWol** [comment]
Completed? Where is the setting at?

**Comment by cclauss** [comment]
* #751
