### ISSUE TITLE
Ui.get_screen_size() gets wrong resolution

### ISSUE THREAD

**Issue by Einehordebedrohenie** [omz/Pythonista-Issues#738]
hello!
With the following script I tried to get my screen resolution:

----
import ui
screen_width, screen_height = ui.get_screen_size()

print(screen_width)
print(screen_height)
----

It returns 1366 x 1024 which is not correct, because I am running Pythonista on an iPad Pro with  2732 x 2048 pixels. 

How can I solve that?

thank you!

**Comment by omz** [comment]
`ui.get_screen_size()` returns the size in *points*, not pixels, which is also the unit of measurement for UI elements, and usually corresponds to 2 or 3 real hardware pixels, depending on your device.
You could get the scale factor for your device using `scene.get_screen_scale()` in Pythonista.
