### ISSUE TITLE
Pythonista crashes during tab conversion

### ISSUE THREAD

**Issue by skrohmer** [omz/Pythonista-Issues#76]
When executing "Convert Tabs" with a file which contains tabs and spaces it crashes. I can reproduce it with following code (whitespace before _x_ is a tab, before _print_ it's two spaces, Pythonista set to _Soft Tabs_ = off and _Tab Width_ = 2).

```
def f(x):
  x *= 2
  print x
```

**Comment by robnee** [comment]
This happens for me as well

**Comment by zrzka** [comment]
Tested with Reformat code in 311014 and it doesn't crash.
