### ISSUE TITLE
Can't change a view name's color

### ISSUE THREAD

**Issue by danrcook** [omz/Pythonista-Issues#78]
There doesn't seem to be any possible way to change the color of a views name. It seems like `tint_color` *should* do this but it doesn't.

Example:
	
```
import ui
v = ui.View()
v.name = 'test'
v.tint_color = 1 #doesn't change the color of the name, but changes for everything else
v.present(title_bar_color=0) #black name on black background!
```

**Comment by omz** [comment]
You can pass a `title_color` argument to `ui.View.present()`.

**Comment by danrcook** [comment]
Thanks @omz I soon found that out too...!
