### ISSUE TITLE
editor.get_line_selection() returns wrong values in some cases

### ISSUE THREAD

**Issue by skrohmer** [omz/Pythonista-Issues#82]
When having special characters in the file the function returns wrong values. Example:

```
# coding: iso-8859-1

import editor

# special character: ä
text = editor.get_text()
selection = editor.get_line_selection()
selected_lines = text[selection[0]:selection[1]]

print selection
print selected_lines
```
- Place the cursor in front of the word _text_ at the beginning of line 6 and run the program. It returns line 5, not line 6.
- Do the same with line 8. It returns line 7.
- Place the cursor somewhere else in the line. It returns the correct line.

It seems to have an influence that the special characters need two bytes:

FIrst change line 5 to make it easier to recognize: `#äöü`
- Place the cursor somewhere in line 5. get_line_selection() returns the selection (37L, 44L) = four characters, three of them using two bytes each.
- Place the cursor in front of the word _text_ at the beginning of line 6 -> (37L, 44L)
- Place the cursor between _e_ and _x_ of the word _text_ -> (37L, 44L)
- Place the cursor between _x_ and _t_ of the word _text_ -> (45L, 69L)

**Comment by zrzka** [comment]
When I modify your first line to:

```
# -*- coding: iso-8859-1 -*-
```

It works well in both interpreters in 311014.
