### ISSUE TITLE
Include flake8 instead of pyflakes

### ISSUE THREAD

**Issue by cclauss** [omz/Pythonista-Issues#85]
https://flake8.readthedocs.io says that `flake8` is a wrapper around these tools:
- PyFlakes
- pep8
- Ned Batchelder’s McCabe script

My coding style needs all the help that it can get.

On my Mac, I use the Atom editor with plugins: **linter, linter-flake8, python-autopep8, script, and tabs-to-spaces**.  With these Atom displays the flake8 analysis _as I type!_  That might be overkill for Pythonista but at least flake8 might be a nice step up from pyflakes alone.

**Comment by zrzka** [comment]
+1
