### ISSUE TITLE
Pythonista 3 python2 editor module does not have all the same methods as the py3 interpreter

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#9]
`_get_editor_tab` and perhaps a few others are only directly available in the py3 `editor` module.

**Comment by zrzka** [comment]
It seems to me it's fixed. Just checked it an Py2Kit `editor` imports `*` from `_editor_pythonista` and this module does contain all these methods. Could you please close this issue @jsbain? If I'm wrong, please correct me, thanks.
