### ISSUE TITLE
Can't move files into Pythonista 2 folder from Pythonista 3

### ISSUE THREAD

**Issue by Tkizzy** [omz/Pythonista-Issues#92]
It would be great if you could move files into the Pythonista 2 folder of the shared App group from within Pythonista 3. At first I thought, "Ok, I can see the logic here - to gently coerce users into fully transitioning to Pythonista 3," But I find myself doing this more often than not and having to switch into Pythonista 2 to do this.

**Comment by zrzka** [comment]
I assume that Pythonista 2 is no longer supported and closing this one.
