### ISSUE TITLE
repeated argument names don't work for new objc_util syntax

### ISSUE THREAD

**Issue by jsbain** [omz/Pythonista-Issues#97]
As an example, the following selector has attribute used twice.  duplicate kwargs are not allowed in python, so we need someway of distinguishing these.

```
NSLayoutConstraint.constraintWithItem(ObjCInstance(cell.content_view),
                                    attribute=NSLayoutAttribute.Height,
                                    relatedBy=NSLayoutRelation.Equal,
                                    toItem=ObjCInstance(cell.detail_text_label),
                                    attribute=(NSLayoutAttribute.Bottom),
                                    multiplier=1.0,
                                    constant=20)
```

**Comment by lukaskollmer** [comment]
@jsbain I don't think that's too big of a problem. If the new syntax doesn't work in some scenarios, you'd just have to use the conventional syntax instead.
That's probably better than having some kind of addition to the new syntax where you'd append numbers to kwargs if a selector uses the same keyword multiple times to distinguish between the different instances of the same argument name.

**Comment by jsbain** [comment]
I agree this is low priority (probably impacts exactly one person).  but the new syntax is nice for these huge selectors.  Compare with
``` 
NSLayoutConstraint.constraintWithItem_attribute_relatedBy_toItem_attribute_multiplier_constant_(
									ObjCInstance(v),
									NSLayoutAttribute.Height,
									NSLayoutRelation.Equal,
									ObjCInstance(l),
									(NSLayoutAttribute.Height),
									1.0,
									20)
``` 

Also, the new syntax is a little easier to copy from existing objc reference docs or code, since you just change colons to equals and add some parenthesis.  My thought would be to append or prepend  numbers or underscores-- do objc selector arguments ever contain underscores at the first/last char?  If not, the resolve instance method function could simply discard them.

**Comment by controversial** [comment]
I'm pretty sure there are cases in which it's absolutely impossible to stay within the PEP8 line-length limit, then (excluding `eval`, ofc) 😂😛

**Comment by cclauss** [comment]
Using `eval()` to stay within PEP8 line length guidelines is like jumping out of a window to just cure a hangnail...  My favorite line from PEP8 applies to that approach ;-) https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds ;-)

**Comment by controversial** [comment]
You're right, of course. 😀

**Comment by omz** [comment]
I think this case is rare enough that it's not worth adding a special case to the already-complicated translation from Python function call syntax to ObjC selectors.
